### ISSUE TITLE
App needs to be on PerMonitorV2 DPI awareness to look properly

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftEdge/WebViewFeedback#1]
After following step 3 of the [Getting Started](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/gettingstarted#step-3---create-a-single-webview-within-the-parent-window), I see the WebView2 offset:

![image](https://user-images.githubusercontent.com/24302614/57265649-79c05d80-702d-11e9-8e09-51e5d2a28b17.png)

WinVersion: 17763.437
NuGet: 0.8.149

Resolution/DPI: 2256x1504 @ 150% (Surface Laptop 2)

If I set my DPI to 100% it seems to work fine.

**Comment by david-risney** [comment]
Thanks. I've opened a bug to track this. Perhaps we're missing some DPI awareness calls from the sample and documentation.

**Comment by jamesoli** [comment]
Hi, we're currently working on our documentation. It does indeed have to do with DPI awareness. To fix this, you need to be per monitor DPI aware. You can either set it in the manifest or add a call before you create the HWND:

SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2);

**Comment by liminzhu** [comment]
Have a PR out to update the getting-started walkthrough - https://github.com/MicrosoftDocs/edge-developer/pull/265/commits/ec53ad28ebcff7d953bdc1fc97dd38ee89199dca. Will leave this issue open as long as the behavior remains the same.

**Comment by liminzhu** [comment]
Update - doc PR is merged.
