### ISSUE TITLE
Correct way to determine if the new Edge is installed on a machine?

### ISSUE THREAD

**Issue by cengman7** [MicrosoftEdge/WebViewFeedback#100]
What is the best way to programmatically determine if the Edge/Chrome control is installed on a machine  (c++)?  I can't count on it being installed since my application is put on some corporate environments that (as I understand it) control whether or not to install the new Edge.

**Comment by pagoe-msft** [comment]
Hi cengman7,

Here is a link to GetWebView2BrowserVersionInfo:
https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/webview2.idl#getwebview2browserversioninfo

You can use this to get the browser version on the machine.

**Comment by cengman7** [comment]
This requires the WebView2 package to be compiled into the installer and application to use this call?
