### ISSUE TITLE
Will WebView2 support the old Edge or only the new Edge?

### ISSUE THREAD

**Issue by raix** [MicrosoftEdge/WebViewFeedback#106]
We would like to use WebView2 but there might be a transition period especially for our enterprise customers.
We are considering using WebView1 as a fallback if the new Edge isn't installed (at least getting away from using IE11 would be nice - we are currently using IE11)

**Comment by douglas-jordan** [comment]
I have been unable to find any documentation for a Win32/COM or similar interface for older Edge.
I wanted to support both as well.

**Comment by pagoe-msft** [comment]
WebView2 will not support the old Edge - only the new Chromium powered Edge. 

We have a high priority item to figure out if there is anything we can do to help Evergreen WebView2 developers handle cases where the browser is missing. For now, potential solutions are to prompt the user to install the Chromium Edge browser, to use WebView2's BYO (Bring Your Own) option, to fallback to IE/Spartan WebView or native, or to ask Enterprise to deploy BYO on managed machines if they aren't ready to deploy the browser.

**Comment by raix** [comment]
BYO would be alot additional data to transfer from our systems and to the customer systems - we are considering to use the old WebView1 to fallback to old Edge if new Edge is not on the system (we would have to do some detection of that - etc.) - We would love to only use the webview2 but some of our customers are likely to be on the slow track for rolling out.
For the prompt to simply download the new edge - that is also we have discussed internally if an option - but I would not expect all users to be able to install it. (we are basically trying to limit the friction and still move away from IE11)

**Comment by champnic** [comment]
We're going to be adding an option to include a much smaller installer (bootstrapper) that can be downloaded or packaged with the app for installing the [WebView Runtime](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#understand-the-webview2-runtime-and-installer-preview).

The original question was answered, so closing this issue. Thanks!
