### ISSUE TITLE
Bug WebView2 dpi not updating when moving between screen resolutions?

### ISSUE THREAD

**Issue by raix** [MicrosoftEdge/WebViewFeedback#107]
I experienced going from one monitor setup to an other (with different resolution?) that the WebView2 container was all black and the browser had "popped" out in a larger size.
Moving the application window with the WebView2 container also resulted in the chrome window moving - except in a different resolution resulting in a "parallax" visual effect. Cool - but not as expected.

Did I forget to add some dpi setting somewhere or is this an actual bug?

**Comment by pagoe-msft** [comment]
Hi raix,

What version of the WebView2 SDK do you have?

**Comment by jamesoli** [comment]
Hey raix,

Do you think it is similar to this previous issue: GH-1?
If so, this should have been fixed by SDK version 0.8.314. Can you check if you have an older version?

**Comment by champnic** [comment]
As @jamesoli noted, for now the app needs to be PerMonitorV2 DPI aware. We will be making improvements in this are soon though, to make it easier for the app to control the DPI of the WebView2. Thanks!
