### ISSUE TITLE
add_NewWindowRequested only handles window.open()

### ISSUE THREAD

**Issue by TcT2k** [MicrosoftEdge/WebViewFeedback#108]
Currently there is no way to detect (or deny) new windows requested by the user via: context menu, middle mouse button click or control+click.

I would expect the `NewWindowRequested` event to be triggered or at have another mechanism to detect and/or deny such actions.

**Comment by pagoe-msft** [comment]
Hi TcT2k,

Thanks so much for the feedback! We are aware of this and actively working on it. I'll circle back to this thread once we release a fix.

**Comment by douglas-jordan** [comment]
I reproduced this as well.  I would also like to deny context menu new window/tab and possibly redirect to existing webview.

I tried to use the existing webview for the window open() content in the handler but the window open() content is never displayed.

Perhaps a webview setting that directs all window open(), new window/tab into the existing webview or something similar.

**Comment by pagoe-msft** [comment]
Hi @TcT2k,

We have resolved this issue in our latest SDK update:

https://review.docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/releasenotes?branch=master#09488

**Comment by TcT2k** [comment]
@pagoe-msft 
Thanks, I've confirmed that the event now triggers for new windows from the context menu, but it still **does not** trigger for middle mouse click or shift + mouse click.

Please reopen this issue until it is fixed or I could open a new issue if you prefer.

**Comment by ajtruckle** [comment]
What about clicking hyperlinks in HTML where the target is `_blank`?

**Comment by ajtruckle** [comment]
https://github.com/MicrosoftEdge/WebView2Feedback/issues/4187
