### ISSUE TITLE
Callback to script not working via object added with AddRemoteObject

### ISSUE THREAD

**Issue by GordonFMcCode** [MicrosoftEdge/WebViewFeedback#114]
The IWebView2WebView4 interface contains a description of how to add a remote object through the AddRemoteObject method. There is an example IDL definition for a CallCallbackAsynchronously method that can callback to the javascript code and an example javascript call to this function. However, there is no example of the code needed to call the IDispatch interface passed to the native object.
When I try to call using DispID 1 with no parameters I get an  HRESULT of 0x8002000c (DISP_E_UNKNOWNLCID). I have tried changing the LCID but always get the same result. I have tried to query for the type info through GetTypeInfo but get E_NOTIMPL. I have tried querying for IDispatchEx but get E_NOINTERFACE. Is this functionality available yet? If so, is there any documentation on how to make the call through the dispatch interface?

I have created an ATL based component with the following function definition
	[id(4)] HRESULT CallbackFromNative([in] IDispatch* callback);

An in the implementation:
	HRESULT hr;
	DISPID dispid = 1;
	DISPPARAMS dispparamsNoArgs = { NULL, NULL, 0, 0 };
	hr = callbackInterface->Invoke(
		dispid,
		IID_NULL,
		LOCALE_SYSTEM_DEFAULT,
		DISPATCH_METHOD,
		&dispparamsNoArgs,
		NULL,
		NULL,
		NULL);

**Comment by david-risney** [comment]
Good point that we're missing documentation on this. Thanks for the feedback! We'll work on better documentation for AddRemoteObject generally and including this.

Our [API sample app has an example](https://github.com/MicrosoftEdge/WebView2Samples/blob/3c99c4ec8ca425ae0b42f51c5b8f98c89d69fc38/WebView2APISample/RemoteObjectSampleImpl.cpp#L39) of what you're asking about.

**Comment by champnic** [comment]
Documentation has been updated (function has been renamed to AddHostObjectToScript):
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-538/icorewebview2#addhostobjecttoscript

If you are still running into issue with this please reopen. Thanks!
