### ISSUE TITLE
CreateWebView2EnvironmentWithDetails returns S_OK when Edge is not installed

### ISSUE THREAD

**Issue by karikera** [MicrosoftEdge/WebViewFeedback#115]
CreateWebView2EnvironmentWithDetails returns S_OK without Chromium Edge
I guess it needs to return some error codes

**Comment by douglas-jordan** [comment]
After you get the environment pointer you must call env->CreateWebView and it will be asynchronous in creating WebView2.

**Comment by karikera** [comment]
@douglas-jordan 
It skips the callback without errors when Chromium Edge is not installed
I was confused

**Comment by david-risney** [comment]
The Create method should call the callback and pass out failure in this case. Thanks for reporting it!

**Comment by quietfanatic** [comment]
I don't seem to be able to reproduce this.  When I uninstall Chromium Edge and run the WebView2APISample from https://github.com/MicrosoftEdge/WebView2Samples, I see CreateWebView2EnvironmentWithDetails returning HRESULT_FROM_WIN32(ERROR_FILE_NOT_FOUND).  @karikera Can you provide some more details around your scenario?

**Comment by karikera** [comment]
It was my mistake, I'm sorry to bother you.

I thought 'RAX' always return value but the destructor of Callback filled it with zero.

**Comment by quietfanatic** [comment]
No problem, thanks for following up!
