### ISSUE TITLE
Unexpected window.close() behavior

### ISSUE THREAD

**Issue by nnemkin** [MicrosoftEdge/WebViewFeedback#119]
When a script calls window.close(), WebView2 destroys itself, leaving an empty black window behind. 

I think the reasonable behavior for embedded WebViews would be to fire an event (new API) and do nothing.

**Comment by david-risney** [comment]
Thanks! Yes it looks like if we inject 'close()' the renderer process will end although the browser, GPU, and utility processes remain.

**Comment by douglas-jordan** [comment]
I have a background watchdog thread that monitors for this condition and posts a quit message to the main thread, where everything is released.

**Comment by pagoe-msft** [comment]
@nnemkin and @douglas-jordan,

In our previous SDK release, we added the WindowCloseRequested event that should resolve your scenario. You can check it out here: https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/icorewebview2#add_windowcloserequested

**Comment by douglas-jordan** [comment]
@pagoe-msft 
The watchdog thread also has the advantage of handling browser crash recovery and only needed to be slightly augmented to handle WebView2.

**Comment by shyjusachin** [comment]
Hi @pagoe-msft @douglas-jordan I wanted to get trigger WindowCloseRequested event in one of my WebView2 use case scenario. I have attempted multiple ways but WindowCloseRequested event/event handler is not listing in my WebView2 core libraries. It is a VB.NET application and installed latest nuget version of WebView2 (1.0.1020.30). Could you please let me know how to implement or enable this functionality. Thanks in advance & much appreciated

**Comment by champnic** [comment]
WindowCloseRequested is fired when the page calls `window.close()`. How have you tried to do this so far? I've confirmed that WindowCloseRequested is available in Microsoft.Web.WebView2.Core.dll in the 1.0.1020.30 package:
<img width="352" alt="image" src="https://user-images.githubusercontent.com/45700886/143932238-8a435fc8-5dc5-46a3-ab46-0bbde0de1139.png">

**Comment by shyjusachin** [comment]
@champnic Thank you for the quick response. In my case I have been using WinForms and events are registered like this 

Friend WithEvents WebView21 As Microsoft.Web.WebView2.WinForms.WebView2

And I can able to use some events like this
![image](https://user-images.githubusercontent.com/95209329/144037487-f3e120f5-3700-4934-b443-25ce8b3752c7.png)

But here I couldn't use same for WindowCloseRequested. So could you please let me know same is available in WinForms or may I am wrong with some event usage ?. If then could you please provide me sample code of WindowCloseRequested event usage.

**Comment by champnic** [comment]
@shyjusachin The WindowCloseRequested event is on the `WebView2.CoreWebView2` object, and not the `WebView2` Winforms control itself.
