### ISSUE TITLE
Need a way to block ctrl/alt/shift click and middle click

### ISSUE THREAD

**Issue by jeff-bb** [MicrosoftEdge/WebViewFeedback#124]
I'm not seeing a way to prevent a user from breaking out of our controled WebView2 into a new msedge instance. Issue #57 resolved some of the concerns, but not all. I thought maybe it would be part of NewWindowRequested, but I'm not having luck.

**Comment by TcT2k** [comment]
See #108

**Comment by david-risney** [comment]
Yes you should be able to handle this by NewWindowRequested but as @TcT2k notes there's a known issue #108 where this doesn't work. Thanks!
