### ISSUE TITLE
Access violation with WebView2 v0.9.430

### ISSUE THREAD

**Issue by MarkusSchreiner** [MicrosoftEdge/WebViewFeedback#128]
I'm working on a C++ MFC application with VS 2017 in which I want to embedd the Edge browser.

After the breaking changes of the WebView2's NuGet version 0.9.430 I always get an Access Violation Exeption, after the `ICoreWebView2CreateCoreWebView2HostCompletedHandler` has been executed completely (without any errors).
In the former version (v0.8.355) everything was working correctly.

The exception reads:
`Exception thrown at 0x000007FEB8A54AE9 (EmbeddedBrowserWebView.dll) in TA.exe: 0xC0000005: Access violation reading location 0x0000000000000141. occurred.`

When I bring up the disassembly view of the exception, I see that the exeption is caused by movzx operation, accessing the RCX register - but the register has no valid entry at this point (000000000).

`movzx       edx,byte ptr [rcx+141h]` 

Any suggestions, what is wrong in my setup?

**Comment by david-risney** [comment]
You mean it AVs after the completed handler returns? Do you keep a reference to the ICoreWebView2Host? Can you link to or paste in the code of your handler?

**Comment by MarkusSchreiner** [comment]
Both, yes and yes.
Please wait until next week, then I will provide more detailed information about the problem.

Regards

**Comment by MarkusSchreiner** [comment]
Hello, David,

I've had time to look at the problem again, and I must say that your comment about whether I am holding a reference to ICoreWebView2Host was spot on.

I actually passed a reference of the host to my main app, and forgot to increase the reference counter accordingly.
With the correct reference handling the AV does not occur anymore.

Thanks for the hint!
So this is not a bug!

**Comment by david-risney** [comment]
Glad you figured it out. Please let us know if you have any other feedback!
