### ISSUE TITLE
How to check if Chromium based edge browser is installed (Microsoft Edge Canary)?

### ISSUE THREAD

**Issue by santoshmetri** [MicrosoftEdge/WebViewFeedback#129]
Hi,

I want to query registry to check if the chromium based edge browser is installed in a given system?

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\App Paths\msedge.exe ???

Regards,

**Comment by ysc3839** [comment]
`HKEY_CURRENT_USER\Software\Microsoft\EdgeUpdate`

**Comment by douglas-jordan** [comment]
I wouldn't rely on a registry check, but rather try loading the environment and if it fails, not installed.

**Comment by santoshmetri** [comment]
Dear douglas-Jordan,

Can you elaborate how can we do it?

**Comment by david-risney** [comment]
You can use [GetCoreWebView2BrowserVersionInfo](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/webview2.idl#getcorewebview2browserversioninfo) to find out the version of the Edge binaries that you would load if you were to use [CreateCoreWebView2Environment](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/webview2.idl#createcorewebview2environment). Or if there are no Edge binaries available to use with WebView2 the method will fail.

Alternatively like @douglas-jordan says you can try calling CreateCoreWebView2Environment and if it works you know that there are Edge binaries available to be used with WebView2.

**Comment by douglas-jordan** [comment]
I like @david-risney 's idea better, call GetCoreWebView2BrowserVersionInfo to verify if binaries are loaded.  Probably faster.

**Comment by santoshmetri** [comment]
Thank you. It is more efficient solution.
The issue here is that to use the method "CreateCoreWebView2Environment", I have to include "WebView2.h" and have to link (input) library "WebView2Loader.dll.lib"

Don't we have any other solution?

**Comment by david-risney** [comment]
Are you trying to determine if Edge is installed for the purposes of using it with WebView2? If so, I would imagine that you already have to include webview2.h and link webview2loader.dll.lib. 

There may be other solutions but none that we can guarantee will continue working in the future. Edge may change its install location or registry keys etc.
