### ISSUE TITLE
ICoreWebView2Host objects say they don't implement ICoreWebView2Host 

### ISSUE THREAD

**Issue by michael-russin** [MicrosoftEdge/WebViewFeedback#130]
Bit of a strange question but with the latest 0.9.430 build if you have an **IUnknown** interface for an **ICoreWebView2Host** object you can't QueryInterface it for an ICoreWebView2Host.  I actually get linker errors (unexpected token) when trying to use **IID_ICoreWebView2Host** and had to redefine it.   Was this done on purpose, or is it a bug?      

If you try the following in the WebView2APISample project in AppWindow::OnCreateCoreWebView2HostCompleted  you can see the problem 

```
HRESULT AppWindow::OnCreateCoreWebView2HostCompleted(
    HRESULT result, ICoreWebView2Host* host)
{
    if (result == S_OK)
    {
        m_host = host;

        void* unknown;
        // This will work 
        HRESULT r = host->QueryInterface(IID_IUnknown, &unknown);

        // This fails E_NOINTERFACE
        void* host2;
        r = host->QueryInterface(IID_ICoreWebView2Host, &host2);

}
```
 
I know you wondering why I would want to do this, I'm actually debugging a problem where I can't marshal ICoreWebView2Host to .net

**Comment by david-risney** [comment]
Yes, thanks. It is a bug. It should be fixed in browser versions 82.0.433.0 and higher.
