### ISSUE TITLE
Request - add ICoreWebView2HttpHeadersCollectionIterator.Reset

### ISSUE THREAD

**Issue by hughbe** [MicrosoftEdge/WebViewFeedback#131]
I'm wrapping `ICoreWebView2HttpHeadersCollectionIterator` in a c# `IEnumerator` interface.

The method `IEnumerator.Reset` can't be implemented at the moment, because `ICoreWebView2HttpHeadersCollectionIterator` doesn't allow for resetting after enumeration.

Could we add a `Reset` method to `ICoreWebView2HttpHeadersCollectionIterator`

[AB#27688058](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27688058)

**Comment by david-risney** [comment]
Good suggestion! For our own C# wrapper we're looking to convert back and forth with the COM http interfaces and corresponding .NET http classes so we didn't see this.

**Comment by champnic** [comment]
This should be fixed and available in the latest prerelease package, 0.9.628-prerelease. Thanks!
