### ISSUE TITLE
What's the license for the embedded Edge

### ISSUE THREAD

**Issue by patr0nus** [MicrosoftEdge/WebViewFeedback#133]
Hi,

To my understanding I will want to embed the close-sourced Edge in my application in BYO mode. Where can I find the license of this embedded Edge? I assume [the license of WebView DLL](https://www.nuget.org/packages/Microsoft.Web.WebView2/0.9.430/License) doesn't apply to Edge itself.

**Comment by douglas-jordan** [comment]
There is no embedded version, its the same one that is installed or the path to the BYO binaries when creating the environment.

**Comment by patr0nus** [comment]
@douglas-jordan 

By "embedded" I mean "redistributed", shouldn't there be a license for the edge binary that I want to "bring my own"？

**Comment by douglas-jordan** [comment]
I am sure Microsoft can clarify.
You would have to start with an installed binary set to get the one you want to redistribute, check that license.

**Comment by nmoinvaz** [comment]
What is the license of the DLL? Are we able to embed it as a resource and extract and use on-demand?

> I am not a lawyer but we would like for apps to be able to ship and use the DLL including I expect in the way you describe. If you don't think that meets what's listed in the license please let me know and we'll look into that too.

https://github.com/MicrosoftEdge/WebViewFeedback/issues/12#issuecomment-492043960

**Comment by david-risney** [comment]
We don't have official support for BYO mode yet. The current plan is to provide the set of binaries you'll need to include with your app. Along with that will be the appropriate license or eula or legal artifacts etc necessary to allow that scenario

The [#12 comment](https://github.com/MicrosoftEdge/WebViewFeedback/issues/12#issuecomment-492043960) talks about license for including the DLL from our SDK in your app which is distinct from including the BYO binaries.

More on BYO coming soon when we release the feature.
