### ISSUE TITLE
Add ability to disable certain browser features

### ISSUE THREAD

**Issue by RichardSteele** [MicrosoftEdge/WebViewFeedback#138]
To get more of a simple web view instead of a full-fledged browser, it would be useful to have a way to disable

- save passwords
- automatic translation
- spell check

**Comment by david-risney** [comment]
Thanks for trying out WebView2! Can you explain a bit about your app? Do you have your own text input control and these text related features are getting in the way?

**Comment by ASM-SW** [comment]
I have the same request.  We are have a web interface internal to our product.  We do not want any pop-ups from Edge such as the request to save passwords.  We have our own built-in translation and do not want edge trying to translate things or spellcheck.  There will be technical terms that are not in any dictionary.

We just want a locked down modern browser that displays what we send, no pop-ups, block shortcut keys, and only allow our internal web pages. 

We also want to control when/if the browser is updated.

**Comment by jfgimenezx** [comment]
Me too  ;-)

**Comment by brianclink** [comment]
Me too :)

**Comment by david-risney** [comment]
@brianclink thanks for opening a separate issue with your specific requests. We have to ensure each feature (spellcheck, password saving, and so on) individually can be turned off so its good to call out specifically what you're interested in.

**Comment by JoshuaWeber** [comment]
We are making changes as suggested in this area. We are intending to disable saving of passwords and translate. We also intend to continue to support the spellcheck feature, but there should be an existing straightforward way to disable that as well. https://stackoverflow.com/questions/254712/disable-spell-checking-on-html-textfields

Browser features are something we are actively thinking through currently. We understand well that many WebView2 app developers want a cleaner simple web view experience, not a browser. That said, we are open to thinking about which of these features are valuable and evaluating way to re-enable them in a more dev controlled manner. If one of these features is something you need in your app. Please reach out to us so we can better understand your use case. A new issue filed to ask for support would work best :)

**Comment by champnic** [comment]
These features should be disabled in Edge/Runtime 86.0.586.0+. Please reopen if you continue to run into this.
