### ISSUE TITLE
Publish edge_embedded_browser/client/win/webview2.idl

### ISSUE THREAD

**Issue by joshholmes** [MicrosoftEdge/WebViewFeedback#14]
Please publish the file edge_embedded_browser/client/win/webview2.idl or a corresponding type library.
I intend to use the WebView2 control from another language that C++. For this I can use an idl file or a type library, but not a C++ header file. 

Copied from https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/37630432-publish-edge-embedded-browser-client-win-webview2

**Comment by david-risney** [comment]
I've opened a bug for this and it should get addressed in a future SDK release.

**Comment by liminzhu** [comment]
The IDL file is getting published in the new SDK [update](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/releasenotes#08190).
