### ISSUE TITLE
Color profile inconsistently applied?

### ISSUE THREAD

**Issue by simonbuchan** [MicrosoftEdge/WebViewFeedback#141]
This one is hard to diagnose, so apologies for the vagueness.
When creating a new web view, the colors are displayed without any color profile correction, e.g.:

```c++
  view->NavigateToString(L"<!doctype html><style>body { background: #F00; }</style>");
```

will show a red rectangle that a color picker will show as #ff0000. *Inconsistently*, at some point, sometimes obviously connected to a user interaction, sometimes not (and not always in that application!) color space correction kicks in and the strong red will change to, on my primary monitor which has an aggressive color profile, the much more muted #DB4010, in the same way that Chrome does. It stops doing this if I change the monitor profile to an sRGB profile.

**Comment by david-risney** [comment]
Thanks for letting us know!

What is the corresponding behavior you see in the Edge browser for this same issue? And what version of the browser is the webview running with?

**Comment by simonbuchan** [comment]
Old edge doesn't apply color profiles at all, it seems. Chromium Edge (Chredge?) has the Chrome behavior, immediately applying color profiles as far as I can tell. I'm using `82.0.446.0 dev`.

**Comment by champnic** [comment]
@simonbuchan We weren't able to reproduce the issue on our end. Given we are built on Edge Chromium (Edgium?) we would expect to match the behavior of applying the color profiles. If you continue to run into this issue and it's a blocker for you please re-open this issue and we can take another look. Thanks!
