### ISSUE TITLE
Taskbar button grouping of WebView based sessions

### ISSUE THREAD

**Issue by santoshmetri** [MicrosoftEdge/WebViewFeedback#142]
Hi,

I have an application which uses WebView to display HTML pages. When user creates multiple sessions, all windows are not grouped in the taskbar instead all created sessions are Grouped except parent window.

The issues occurs only when WebView is used. We do not have any grouping related issues when we use WebBrowser ActiveX control.

Can you please help here?

**Comment by douglas-jordan** [comment]
The WebBrowser control is an in process DLL, so any windows created are part of the process that loaded the control.

WebView2 is run in a separate process and those windows are not part of the process that loaded it.

**Comment by david-risney** [comment]
@santoshmetri, do you mean your own application's windows aren't grouped together? Or do you mean windows created by the WebView? 

Do you set the application user model ID of your application or windows?

**Comment by david-risney** [comment]
We do have some current behavior where if the host app doesn't have an application user model ID (AUMID) then one gets set on the host app's window using the host app's executable. This would mean apps that don't set an AUMID and use WebView2 will all be grouped together in the taskbar. You can use SetCurrentProcessExplicitAppUserModelID to explicitly set the AUMID before using WebView2 to avoid this problem.

We will look into this though and see if we can do something else here.

**Comment by santoshmetri** [comment]
Dear David-Risney,

Thank you for the solution. It works if I hard code.
I would like to get the AUMID of underlying/Calling process programmatically.
I think GetCurrentProcessExplicitAppUserModelID() does not work.

is it possible?

**Comment by santoshmetri** [comment]
Dear David-Risney,

Today I observed fishy behavior. Unfortunately the suggested method works only for first session (Window) of a process but not for  Second and their after.

**Comment by champnic** [comment]
Fixed in Edge 84.0.490.0+
