### ISSUE TITLE
Indexed properties are inaccessible from JavaScript

### ISSUE THREAD

**Issue by pontusn** [MicrosoftEdge/WebViewFeedback#143]
We have a legacy COM-api with extensive usage of indexed properties.
Accessing indexed properties from JS yields "Error: The parameter is incorrect.".

For internal APIs we applied a workaround in IDispatchImpl by setting both DISPATCH_METHOD and DISPATCH_PROPERTYGET if any of them where set.

`if ((wFlags & (DISPATCH_METHOD | DISPATCH_PROPERTYGET)) != 0L) {
    wFlags |= DISPATCH_METHOD | DISPATCH_PROPERTYGET;
}`

**Comment by david-risney** [comment]
Thanks for trying out AddRemoteObject with your existing legacy COM API!

I'm not sure I know exactly what you mean. Can you share some example JavaScript that you would like to see working and the sort of call sequence and the parameters you would expect to see on your IDispatch objects?

**Comment by pontusn** [comment]
The Item-property of good old Scripting.Dictionary can serve as an example. (https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/item-property-dictionary-object)

From WebView2 we cannot access the Item-property at all, from my view the call is translated to a method invokation instead of a property get. For our APIs we changed the implementation of IDispatch::Invoke to work around the problem by accepting caller to treat indexed properties as methods, but that is not viable for external components.

David Risney <notifications@github.com> skrev: (24 mars 2020 22:26:33 CET)
>Thanks for trying out AddRemoteObject with your existing legacy COM
>API!
>
>I'm not sure I know exactly what you mean. Can you share some example
>JavaScript that you would like to see working and the sort of call
>sequence and the parameters you would expect to see on your IDispatch
>objects?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/MicrosoftEdge/WebViewFeedback/issues/143#issuecomment-603513540

-- 
Skickat från min Android-enhet med K-9 Mail. Ursäkta min fåordighet.

**Comment by david-risney** [comment]
Thanks. We'll look into this

**Comment by champnic** [comment]
This should be fixed in Edge 84.0.500.0+. Thanks!
