### ISSUE TITLE
WebResourceRequested and NavigationStarting events are not fired when using NavigateToString()

### ISSUE THREAD

**Issue by jfgimenezx** [MicrosoftEdge/WebViewFeedback#149]
Hi,

I'm trying to use the WebView to load contents programatically, by using NavigateToString(). In that scenario, I'm awared that local URIs can't be resolved, because the base URI is about:blank. I.e. src="image.jpg" can't be resolved, while src="https:/myserver/image.jpg" does.

So, I need to supply them through the WebResourceRequested event. But it's not fired at all. If I use src="https:/myserver/image.jpg" then it's fired correctly, but not when using a local URI.

The same happens to NavigationStarting. If the link is a local URL, then the event is not fired.

I belive that this is probably a bug. IMO, those events should be fired always, before determining if the target URI is reacheable or not. Please, fix it.

Meanwhile... is there any way to set a custom base URI in order to make those events to fire? Something like "local://" or so.

TIA

BTW, congratulations for this amazing project. I've been waiting for years for a modern WebView component for Win32, since IE WebBrowser is now deprecated.

**Comment by pontusn** [comment]
For our project we worked around a similar issue by adding a "virtual" folder on out server for any content generated by or loaded directly from the client.

https://<server>/~/<localpath>

Then we push all content via client side events. This also effectively works around problems with CORS.

**Comment by jfgimenezx** [comment]
Hi pontusn,

thanks for your reply, but it's not a solution for me.

I'm trying a hack: I'm loading an unexisting file (file://dummy.html) in order to set it as the base URI. Later, I'm supplying local needed resources through WebResourceRequested event, filtering by "file://dummy.html/*".
However, the main page cannot be served in that way, since the html code is shown as plain text. I have to replace the content via ExecuteScript( "document.documentElement.innerHTML=..." )

It's a dirty hack, and I don't like it. But I've not found any other way yet.

I'd be nice a method to load html an set the base URI, like this: https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.navigatetolocalstreamuri

**Comment by david-risney** [comment]
Hi thanks for trying out WebView2 and this great feedback!

WebResourceRequested is currently only for http(s) URIs and there's no corresponding functionality for other URI schemes. But its a great feature request that we've received before and will look into.

NavigateToString effectively loads in about:blank and then injects the string HTML content. NavigationStarting really should fire but we have a bug where about:blank navigates don't fire the event. 

For changing the base URI, would using a base HTML tag help?

**Comment by jfgimenezx** [comment]
Hi David,
thanks for replying. And thanks for look into these issues.

Respecting the base URI and to use an HTML tag, what is exactly what you're proposing? Adding an explicit tag to fix a base is probably a good solution, but could you tell me more details, please?

**Comment by markFleischmann** [comment]
@david-risney I saw you comment saying that WebResourceRequested is currently only for http(s) URIs, do you think support for Local files will be added? (and if so, when?) When I try this for local html content (i.e. file:///C:/index.html) CoreWebView2WebResourceRequestedEventArgs.Request is null in my WebResourceRequested handler function

**Comment by champnic** [comment]
The NavigationStarting issue has been fixed in Edge 86.0.581.0+. Thanks!
