### ISSUE TITLE
stackoverflow on Redstone4 10.0.17134

### ISSUE THREAD

**Issue by pagoe-msft** [MicrosoftEdge/WebViewFeedback#152]
Copied over from: https://github.com/MicrosoftDocs/edge-developer/issues/280

this event is causing stackoverflow issue on RS4 system with external webview process.
but working on RS5, any idea to workaround this issue on RS4 systems?

**Comment by champnic** [comment]
Haven't heard back in a while. Dexter if you are still running into this please reopen the issue. Thanks!
