### ISSUE TITLE
MSWebViewWebResourceRequested not able to capture all resource requests.

### ISSUE THREAD

**Issue by pagoe-msft** [MicrosoftEdge/WebViewFeedback#153]
Copied over from: https://github.com/MicrosoftDocs/edge-developer/issues/258

Hi, I am trying to use MSWebViewWebResourceRequested to capture all request from my site, and I found that 1. svg resource won't be rendered, 2. font request won't be captured.
I will try to pack my site to inline all svg/font resources in the html it self, but is it possible to know what else limitation this event has?

**Comment by pagoe-msft** [comment]
Hi Dexter,

Could you try to recreate this issue using the new WebView2 control?

https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/icorewebview2webresourcerequestedeventargs

**Comment by champnic** [comment]
Closing as we haven't heard back in a while. Dexter if you are still hitting this issue please reopen. Thanks!
