### ISSUE TITLE
CreateCoreWebView2Host fails for second environment created with different arguments

### ISSUE THREAD

**Issue by pontusn** [MicrosoftEdge/WebViewFeedback#159]
Our client embeds WebView2 in numerous places where two usage are contextually different and use specific arguments for creating the environment.

Environments using the first arguments work as expected while environments created later with different arguments fails with  HRESULT_FROM_WIN32(ERROR_INVALID_STATE) == 0x8007139F when creating the host.

```
    HRESULT hRes = CreateCoreWebView2EnvironmentWithDetails(
        nullptr,
        szAppData,
        startArguments.data(),
        Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(
            [this](HRESULT result, ICoreWebView2Environment* webviewEnvironment) -> HRESULT {
                ATLTRACE(_T("ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler\n"));
                m_spWebViewEnvironment = webviewEnvironment;
                if (!m_spWebViewEnvironment)
                {
                    m_strStatusMessage.Format(L"Failed to create environment. hResult=0x%08x", result);
                    return FAILED(result) ? result : E_FAIL;
                }
                m_spWebViewEnvironment->CreateCoreWebView2Host(m_hWnd, Callback<ICoreWebView2CreateCoreWebView2HostCompletedHandler>(
                    [this](HRESULT result, ICoreWebView2Host* webviewHost) -> HRESULT {
                        ATLTRACE(_T("ICoreWebView2CreateCoreWebView2HostCompletedHandler\n"));
                        m_spWebViewHost = webviewHost;
                        if (!m_spWebViewHost)
                        {
                            // Fails here with hResult = 0x8007139F
                            m_strStatusMessage.Format(L"Failed to create host. hResult=0x%08x", result);
                            return FAILED(result) ? result : E_FAIL;
                        }

                        if (FAILED(result = m_spWebViewHost->get_CoreWebView2(&m_spWebViewWindow)) || !m_spWebViewWindow)
                        {
                            m_strStatusMessage.Format(L"Failed to get view. hResult=0x%08x", result);
                            return FAILED(result) ? result : E_FAIL;
                        }

                        if (FAILED(result = InternalConfigure()))
                        {
                            m_strStatusMessage.Format(L"Failed to configure browser. hResult=0x%08x", result);
                            return result;
                        }

                        return S_OK;
                    }).Get());
                return S_OK;
            }).Get());
```

This issue was first seen at same time as #156 was reported, but most likely they are not related.

For our initial scenario the main difference is that one environment specified debugging port.

**Comment by david-risney** [comment]
Thanks! This is expected behavior. Creating multiple environment objects with the same user data folder must share the same other creation values. If you have the debugging port on the first environment you create the second should succeed. Or if you change the second environment to have a different user data folder.

Is it possible in your case to make either of those changes?

Can you tell me more about your scenario for creating two environments like you described?

**Comment by pontusn** [comment]
Great. Using separate data folder is definitely viable for us, just need to figure out how to keep track of them exactly. Arguments are generated dynamically based on content and purpose. Considering just making a hash from the arguments.

For now I've worked around the problem by using identical arguments again. The difference was accidental due to an underlying design flaw...

I fully understand this limitation, but would expect the call to create environment to fail directly rather than signaling via the callback to create host window. 

Later we will use separate environments depending on both purpose and content. Whatever is loaded from our current server is fully trusted and should preferably be kept separate from other content.
