### ISSUE TITLE
Ability to disable developer tools

### ISSUE THREAD

**Issue by nmoinvaz** [MicrosoftEdge/WebViewFeedback#16]
What is the best way to go about disabling the CTRL+SHIFT+I developer tools?

**Comment by nmoinvaz** [comment]
On another note, I'd like to add that I like how the Developer Tools starts recording instantly. Chrome and others start recording only from the time that you open the Developer Tools.

**Comment by liminzhu** [comment]
Thanks for opening the issue @nmoinvaz ? May I ask what the reasoning is that you want to disable devtools?

**Comment by nmoinvaz** [comment]
I don't want end-users to easily be able to modify the web view or go snooping through the innards of the page.

**Comment by liminzhu** [comment]
That's reasonable. We should look into it.

**Comment by liminzhu** [comment]
Hey @nmoinvaz , thanks for submitting the feedback! We've added new APIs [get_AreDevToolsEnabled](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2settings#get_aredevtoolsenabled) and [put_AreDevToolsEnabled](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2settings#put_aredevtoolsenabled) for disabling DevTools in the new SDK [update](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/releasenotes#08190). Make sure you update the SDK and use the Canary channel for testing, thanks!
