### ISSUE TITLE
Support custom JavaScript proxies for remote objects based on underlying type.

### ISSUE THREAD

**Issue by pontusn** [MicrosoftEdge/WebViewFeedback#160]
**Feature request**

One major difference between embedding legacy WebBrowser-control and WebView2 is performance for the COM-API. Crossing process boundaries add latency.

Our primary usage scenario includes a massive amount for legacy code developed locally for and/or by customers. All aspects of compatibility, including performance, is crucial for end-user acceptance.

For shallow call-chains we have done some prototyping/experiments for type specific marshalling using Json and custom JavaScript-proxies. This approach enable us to efficiently serialize complex structures in native code and then provide hand-coded proxies that shield the legacy code from the gritty details.

For deep or complex call-chains this approach will require us to create proxies for the entire model. This can probably be automated pretty well, but still a supported hook for handling specific COM-interfaces would be of great value.

One approach could be to provide a callback in native code for serializing COM-objects before sending them back to JavaScript, combined with JavaScript-hooks for custom proxies. For our current prototype we handle everything in JavaScript which effectively requires an extra roundtrip to native code for serializing.

**Comment by david-risney** [comment]
When you say a 'callback in native code for serializing COM-objects before sending them back to JavaScript', do you mean that we would send a serialized copy of the COM object to script? Normally we have a live connection between script and native where function calls and property accessors in script will go back to native to perform the operation. Are you asking for a mechanism to send a serialized version of the COM object that then is just a copy of that COM object in script without further function calls or property accessors going back to the original COM object?

**Comment by pontusn** [comment]
For some purposes a plain copy will do fine, especially for new APIs we would probably go for immutable copies. For other scenarios a copy of properties for reading but methods and property writers is more suitable, especially for supporting legacy code.

**Comment by champnic** [comment]
This is being tracked in #93. Thanks!
