### ISSUE TITLE
Turning off SmartScreen reputation checks doesn't work

### ISSUE THREAD

**Issue by tomasstrba** [MicrosoftEdge/WebViewFeedback#162]
I can capture communication to `nav.smartscreen.microsoft.com` domain when navigating to various URLs with WebView2. It looks like reputation checks mentioned in [Privacy Whitepaper](https://docs.microsoft.com/en-us/microsoft-edge/privacy-whitepaper#smartscreen) because requests contain URLs I visited. Requests persist even when I turn SmartScreen off, under Services > Microsoft Defender SmartScreen in `edge://settings/privacy`.

Please, is this an expected behavior?

**Comment by david-risney** [comment]
When you say you turn SmartScreen off in edge://settings/privacy, are you doing that in the browser or in the WebView2?

**Comment by tomasstrba** [comment]
David, thanks for fast response! Your answer pointed me to the right direction. 

After I added `edge` as allowed protocol in [default.js](https://github.com/MicrosoftEdge/WebView2Browser/blob/master/wvbrowser_ui/controls_ui/default.js) of [WebView2Browser](https://github.com/MicrosoftEdge/WebView2Browser) I was able to turn off SmartScreen in the WebView2. Previously, I misunderstood how to access privacy settings described in [WebView2 - Feedback](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2#feedback)

There are no more requests related to visited URLs I mentioned above. Thanks a lot!

Unfortunately, there is still one request to `nav.smartscreen.microsoft.com` every time I start WebView2Browser. The request contains sensitive data (cleared with 0):

`{
	"identity": {
		"caller": {
			"locale": "en-US",
			"process": null
		},
		"client": {
			"data": {
				"customSettings": "0",
				"customSynchronousLookupUris": "0",
				"edgeSettings": "0",
				"synchronousLookupUris": "0",
				"topTraffic": "0"
			},
			"version": "0"
		},
		"device": {
			"architecture": 9,
			"browser": {
				"internetExplorer": "0"
			},
			"cloudSku": false,
			"enterprise": null,
			"family": 3,
			"locale": "en-GB",
			"netJoinStatus": 2,
			"onlineIdTicket": null,
			"osVersion": "0"
		},
		"user": {
			"locale": "en-US"
		}
	}
}`

Please, is there a way to turn the request off?

**Comment by liminzhu** [comment]
@tomasstrba I'm curious, is there a reason you want to turn smartscreen off?

**Comment by tomasstrba** [comment]
@liminzhu I'm just looking at WebView2 from a privacy point of view and experimenting. It's surprising to see the request when I turn SmartScreen off. Does it have a specific purpose?

**Comment by tomasstrba** [comment]
@david-risney, @liminzhu, 

if the communication with SmartScreen subdomain after turning off SmartScreen protection is valid behaviour, we can close this issue. I just wanted to share it with you so you can verify there is no bug.

**Comment by liminzhu** [comment]
Thanks @tomasstrba. This is something we're validating with our privacy folks as well, thanks for bringing this up.
