### ISSUE TITLE
WebView2 for WPF availability

### ISSUE THREAD

**Issue by DominikPalo** [MicrosoftEdge/WebViewFeedback#163]
Is there any rough time estimate when could be the WebView2 control available for WPF? A didn't find any timeline regarding this, so I would like to know if we talk about weeks, months, or even the next year?

**Why am I asking:**
We have a desktop WPF app used by hundreds of our clients, which uses the first Edge-based [WebView](https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/wpf-winforms/webview). Unfortunately, there are a lot of bugs and issues with that old WebView (I reported some of them to the [WebView repo](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues), but I didn't get any helpful feedback - everyone says, that the WebView is deprecated and no longer maintained :(... although I don't really understand how can be something marked as deprecated when there is no newer alternative/replacement). We are thinking about using a different engine for web content (we have already made a few beta tests with [CefSharp](https://github.com/cefsharp/CefSharp) - it works really well, although we would like to use something more "native" like WebView2, which doesn't increase the size of our app by ~100MB like CefSharp).  So, our final decision will be based on the availability of WebView2. If it will be available soon, we will wait... otherwise, we will have to switch to CefSharp. The old IE based WebBrowser control is not an option for us.

**Comment by noxo** [comment]
@DominikPalo while you are waiting for "official" version, here is something for WPF https://github.com/michael-russin/webview2-control

**Comment by michael-hawker** [comment]
@DominikPalo also see the [comment here](https://github.com/MicrosoftEdge/WebViewFeedback/issues/170#issuecomment-622159940) on this other issue:

> We'll release a developer preview for WinForms in just a few weeks! Stay tuned!

I'd imagine that should just be the general .NET preview and include WPF as well.

**Comment by david-risney** [comment]
Thanks for the question @DominikPalo! Yes what @michael-hawker says is true. The .NET preview that @pagoe-msft mentioned will include WPF & WinForms.

**Comment by pagoe-msft** [comment]
We just release our .NET preview for WPF & WinForms!

https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes#09515-prerelease
