### ISSUE TITLE
WebView2 sample app does not work

### ISSUE THREAD

**Issue by Reezaali** [MicrosoftEdge/WebViewFeedback#164]
Copied from: https://github.com/MicrosoftDocs/edge-developer/issues/415

Hi,

I have followed all the instructions from Getting Started with WebView2 (developer preview) to create an app that is using Microsoft Edge (Chromium). However, it is not able to find the Edge browser. I also tried the sample app but with the same results. I have built the app both for 32- and 64-bit.

What I get from calling CreateWebView2EnvironmentWithDetails() is 0x80070002, which is ERROR_FILE_NOT_FOUND (The system cannot find the file specified.)

I have:

Edge Version 79.0.309.60 (Official build) beta (64-bit)
Windows 10.0.17134
Visual Studio 2019 16.4.2
Why isn't it able to find the Edge installation?

**Comment by michael-russin** [comment]
What version of the SDK are you using?   If you are using Edge 79 then you can only use SDK 0.8.270.  ( See: https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/releasenotes )

**Comment by david-risney** [comment]
Yes. The best bet to using the latest SDK is to use the latest Edge canary channel.
