### ISSUE TITLE
Does webview2 supports ResizeObserver

### ISSUE THREAD

**Issue by Reezaali** [MicrosoftEdge/WebViewFeedback#165]
Copied from: https://github.com/MicrosoftDocs/edge-developer/issues/489

Chrome and Firefox supports ResizeObserver which lets one register a callback so that if there are any changes to the height of a container / document, they can get notified.

Does webview2 supports something like this. A quick check tell me that it is not there (followed this - https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver)
if (ResizeObserver) {
console.log('resize observer available');
} else {
console.log('resize observer not available');
}

The requirement is that if i have images that are loaded asynchronously - they will change the height of the document window and my host application needs to get the appropriate height once all the images are loaded.
I tried to tap on to the window.onload() event, but that event is fired even before image download starts. (That could possibly be because of the fact that i also have to intercept the image requests so that i can add relevant headers to the outbound requests).

But, the end picture is that the onload() event is already fired before image downloads. And the initial document height changes once the image gets downloaded. And i am not sure on how to get this notification.

Thanks in advance.

**Comment by david-risney** [comment]
Generally WebView2 has all the same web platform features that the Edge browser does. In this case I do see the ResizeObserver exists at least in the latest canary 84.0.496.0. I'm not sure when the feature was added but I would expect it to exist in WebView2 ever since it appeared in Edge.
