### ISSUE TITLE
Porting CWebView to WebView2

### ISSUE THREAD

**Issue by Reezaali** [MicrosoftEdge/WebViewFeedback#166]
Copied from: https://github.com/MicrosoftDocs/edge-developer/issues/505

I am using the CHtmlView in my application and there, I use a handler for getting Json data from the host when the user presses a Select button.

How can I implement such a handler with the WebView2?

// Handler used in CHtmlView
class CExternalHandler : public CCmdTarget
{
public:
CExternalHandler()
{
EnableAutomation();
}

void BuildupSelect(LPCWSTR str)
{
CHelpers::StoreData(str);
}

private:
DECLARE_DISPATCH_MAP()
};
BEGIN_DISPATCH_MAP(CExternalHandler, CCmdTarget)
DISP_FUNCTION(CExternalHandler, "BuildupSelect", BuildupSelect, VT_EMPTY, VTS_WBSTR)
END_DISPATCH_MAP()

**Comment by michael-russin** [comment]
There is a good demo of passing Json between the WebView2 and the host application in the sample https://github.com/MicrosoftEdge/WebView2Samples/tree/master/WebView2APISample 
look at ScriptComponent.cpp ScenerioWebMessage.cpp and ScenarioWebMessage.html

**Comment by david-risney** [comment]
Thanks yes! You can also read the docs for [PostWebMessageAsJson](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/icorewebview2#postwebmessageasjson) which talks about the method and has code snippets from the same WebView2APISample.

After posting with PostWebMessageAsJson or PostWebMessageAsString, the script in the HTML document can receive that via the window.chrome.webview 'message' event. It can post back via window.chrome.webview.postMessage and then you can receive those events via [add_WebMessageReceived](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/icorewebview2#add_webmessagereceived)
