### ISSUE TITLE
Disable saving passwords

### ISSUE THREAD

**Issue by brianclink** [MicrosoftEdge/WebViewFeedback#169]
We are using the Edge webview2 control in a client application that is sensitive to security.  How can we disable the prompts to save the password?  Is there a programmatic way, or is there a workaround available?  Any thoughts would be appreciated.

![save-prompt](https://user-images.githubusercontent.com/4602264/80515753-7023ba00-8950-11ea-8017-2bb2d50d6a9a.png)

**Comment by david-risney** [comment]
Hi @brianclink, great question! I don't know of any workaround. I'll open a feature request for this. Thanks.

**Comment by brianclink** [comment]
@david-risney - Thank you!  Is there a place where I can see the status or consideration of a feature request?  Would also appreciate if the team could suggest any possible workarounds.

**Comment by david-risney** [comment]
@brianclink this is the best place we have for communicating about WebView2 bugs and features.

I don't know of any workarounds. Reading about that feature in Chromium it seems there's no way to configure it from the web content. I thought maybe there'd be a way to do it via the DevTools Protocol but no and also no on the Chromium command line parameters that I can find.

**Comment by igotbass** [comment]
+1 for it being an issue, you can control it in the Settings of Edge to disable it but not the Webview2. Also checked command line and nothing is there for it. In my scenerio,I need a fresh browser with no cookies, using the workaroud to delete the user directory each time also makes the browser prompt again for saving passwords for specific site.

**Comment by champnic** [comment]
The Password Saving feature has been disabled as of Edge 86.0.586.0+. You can test this out using the latest Edge Canary or Edge Dev.

**Comment by monkeypro** [comment]
Can it be enabled in any way?

**Comment by champnic** [comment]
We are tracking enable/disable controls in #374. I don't think there's currently a way to re-enable.
