### ISSUE TITLE
C# & Winforms support 

### ISSUE THREAD

**Issue by dave-q** [MicrosoftEdge/WebViewFeedback#170]
Hello,

I've seen a few questions reference this and it got discussed briefly in the comments but I couldn't find anything that was very clear.

I'm hoping to embed an Edge Chromium window in my win forms application. Is there a timeline of when this is going to be possible? Even a developer preview?

Thanks :)

**Comment by pagoe-msft** [comment]
Hi @dave-q,

We'll release a developer preview for WinForms in just a few weeks! Stay tuned!
