### ISSUE TITLE
WebView2 WPF not working if Edge Profile Path changed

### ISSUE THREAD

**Issue by joru1407** [MicrosoftEdge/WebViewFeedback#179]
The current WebView2 for WPF is not working and stays blank without any error.

This issue appears if the Profile Path of Edge is changed.
In this case the Profile Path of Edge was changed by Group Policy to AppData\Roaming.

If the Profile Path of Edge stays on default, everything works as expected.

Thanks, Joshua

**Comment by david-risney** [comment]
Good issue, thanks! Can you say which policy that was exactly? Was it the [UserDataDir policy](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#userdatadir)?

**Comment by joru1407** [comment]
Hi David, yes, it's exactly the UserDataDir policy you've mentioned :-)

**Comment by chrisluna** [comment]
I was able to get the [Getting Started app](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf) to work after installing the Canary version of edge - 
which can be found here - https://www.microsoftedgeinsider.com/en-us/download

**Comment by joru1407** [comment]
I'm using the latest Canary Version of Edge (84.0.521.0).
I did a test with a blank profile a few minutes ago: Everything works as expected, but as soon as I apply the mentioned GPO the WebView remains grey without showing the website.

**Comment by champnic** [comment]
This should be fixed in Edge 85.0.531.0+. Thanks!
