### ISSUE TITLE
How to get the installed version number

### ISSUE THREAD

**Issue by nmoinvaz** [MicrosoftEdge/WebViewFeedback#18]
What is the best way to get the version number for the installed version of Edge-chromium? Is there a registry key somewhere that you would recommend reading? I think there is some value possibly getting that information from _IWebView2WebView_, however in my use case I need it before _IWebView2WebView_ is initialized.

**Comment by liminzhu** [comment]
I don't think we have a WebView API for that, but a way (not saying it's the best) to get version number would be calling `window.navigator.userAgent` with ExecuteScript to get the UA string.

**Comment by david-risney** [comment]
We generally try to avoid exposing the version numbers since we want folks to use feature detection rather than hardcoding version checks. What is the use case you referenced?

**Comment by nmoinvaz** [comment]
We try to make that information available to our platform. If we wanted to require a minimum version of Edge chromium, then we would need a way to get the version (I mean we could use the version of the WebView2Loader.dll) but also need to get the version of chromium being used -- then we would need that information before creating a _IWebView2_ instance.

**Comment by nmoinvaz** [comment]
In IE it was possible to get this information via "Software\Microsoft\Internet Explorer" using the svcVersion or Version keys.

**Comment by lingamy** [comment]
Hi Nathan, thanks for submitting the feedback! We’ve added new APIs [GetWebView2BrowserVersionInfo ](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/webview2.idl#getwebview2browserversioninfo) and [get_BrowserVersionInfo ](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2environment2#get_browserversioninfo) for getting the browser version and the corresponding channel name in the new [SDK update](https://www.nuget.org/packages/Microsoft.Web.WebView2/0.8.270). Make sure you update the SDK and use the canary channel for testing.
