### ISSUE TITLE
Microsoft.Web.WebView2.Wpf.dll does not represent a strongly named assembly

### ISSUE THREAD

**Issue by antti-j** [MicrosoftEdge/WebViewFeedback#181]
Microsoft.Web.WebView2.Wpf.dll does not represent a strongly named assembly, which means that it can't be referenced by strong-named assemblies. I think this is against Microsoft policies. Quote from
https://github.com/dotnet/runtime/blob/master/docs/project/strong-name-signing.md

> Because of the viral nature of strong-naming, it is recommended that publicly published .NET libraries are strong-named. Not strong-naming a .NET library excludes anyone who does need to strong-name their application or library from using it.

```
sn -T Microsoft.Web.WebView2.Wpf.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Microsoft.Web.WebView2.Wpf.dll does not represent a strongly named assembly
```

[AB#26466581](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/26466581)

**Comment by david-risney** [comment]
Thanks! We'll look into this.

**Comment by mikemeinz** [comment]
I have the same issue using WinForms.

Tried with both .NET Framework 4.6.2 and 4.8
Microsoft.Web.WebView2 0.9.515-prerelease WinForms
Version 84.0.524.0 (Official build) canary (64-bit)
Visual Studio 2017 Version 15.9.22
Target Platform: x64

**Sign the Assembly checked test**
Compile Release mode
"Sign the ClickOnce manifests" is checked
"Sign the assembly" is checked
```
1>vbc : warning BC41997: Referenced assembly 'Microsoft.Web.WebView2.WinForms, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
1>vbc : warning BC41997: Referenced assembly 'Microsoft.Web.WebView2.Core, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
```
**Sign the Assembly NOT checked test**
.NET Framework 4.8
Target platform x64
Compile Release mode
"Sign the ClickOnce manifests" is checked
"Sign the assembly" is NOT checked
No Warning or Error messages

**Comment by david-risney** [comment]
Yes, this applies to all of our .NET DLLs

**Comment by cuiliang** [comment]
Wish strong named version~

**Comment by monkeypro** [comment]
Is there any workaround for this?
I have been able to strong name sign WebView2.Wpf.dll and WebView2.Core.dll but not WebView2Loader.dll

**Comment by antti-j** [comment]
> Is there any workaround for this?

My _workaround_ is to disable strong name signing for my assemblies.

**Comment by GieltjE** [comment]
> 
> 
> > Is there any workaround for this?
> 
> My _workaround_ is to disable strong name signing for my assemblies.

That's weakening the trustworthyness of your application, this simply needs to be fixed (or sign them yourself....). I find it hard to believe that Microsoft cannot manage such a trivial yet important step in the year 2020.

**Comment by pagoe-msft** [comment]
We really appreciate everyone for bringing this to our attention, this is definitely an error on our part. We will work towards strong signing our assemblies in future releases.

**Comment by jozefizso** [comment]
This is a blocker issue for us. As the **Microsoft.Web.WebView2.WinForms** assembly is not strongly signed, it does not work in our project.

**Comment by GieltjE** [comment]
@pagoe-msft please allow redistribution of edge too, without being able to redistribute and use a forced edge version a lot of commercial implementations will not use it.

**Comment by pagoe-msft** [comment]
@GieltjE 

By a forced edge version - are you referring to the Evergreen distribution model that keeps WebView2 apps on the latest version of Edge? If so, when the control GA's, there will be a 'Fixed' version as well that allows developers to package the browser with the application.

https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#roadmap

**Comment by GieltjE** [comment]
The fixed version is indeed what will be needed, thanks for the links

**Comment by rgup63** [comment]
Is there any update on this?

**Comment by billybooth** [comment]
Hi all.  Any updates on this?  It is also a blocker for us and would be great to see it resolved.

**Comment by champnic** [comment]
This is fixed and available in the latest prerelease package, 0.9.628-prerelease. Thanks!

**Comment by monkeypro** [comment]
@champnic 
I get the following error when calling **WebView.EnsureCoreWebView2Async()** after updating to the latest prerelease
`System.BadImageFormatException: ' is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)'`

**Comment by champnic** [comment]
That's issue #431. Can you try some of the workarounds mentioned there? The easiest is probably to build x64 (instead of x86 and AnyCPU).

**Comment by RRQM** [comment]
I created the project according to the instructions, but can not open any web pages, either Core3.1 or Framework4.6.2, please reply.

<Window x:Class="WpfApp2.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp2"
        xmlns:wpf="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <wpf:WebView2 Source="https://www.baidu.com/"/>
    </Grid>
</Window>


引发的异常:“Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException”(位于 Microsoft.Web.WebView2.Core.dll 中)
引发的异常:“Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException”(位于 System.Private.CoreLib.dll 中)
引发的异常:“Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException”(位于 Microsoft.Web.WebView2.Wpf.dll 中)

**Comment by champnic** [comment]
Hey @RRQM - The WebView2RuntimeNotFoundException means you need to install a WebView2 Runtime (or Microsoft Edge Canary/Dev/Beta) on the machine.
https://developer.microsoft.com/en-us/microsoft-edge/webview2/
