### ISSUE TITLE
Ability to hide the status bar

### ISSUE THREAD

**Issue by nmoinvaz** [MicrosoftEdge/WebViewFeedback#19]
A status bar appears when loading in the bottom left hand corner of the _IWebView2WebView_ instance. It would be great if there was a way to turn this off.

**Comment by david-risney** [comment]
I can see how this would be useful to support cases where the end developer is rendering app-like web content and they don't want it obvious to the end user that its web content or WebView. Is that the scenario you have here?

**Comment by nmoinvaz** [comment]
Yes

**Comment by liminzhu** [comment]
Hey @nmoinvaz , thanks for submitting the feedback! We've added new APIs [get_IsStatusBarEnabled](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2setting) and [put_IsStatusBarEnabled](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2settings#put_isstatusbarenabled) to control the status bar in the new SDK [update](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/releasenotes#08190). Make sure you update the SDK and use the Canary channel for testing, thanks!
