### ISSUE TITLE
[Feature Request] Ability to remote inspect WebView2 components from Edge

### ISSUE THREAD

**Issue by dstaley** [MicrosoftEdge/WebViewFeedback#190]
It would be really nice to be able to use the remote debugging protocol to connect to a WebView2 instance from within Edge. Ideally, you'd see WebView2 instances listed on `edge://inspect`.

[AB#27202919](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27202919)

**Comment by david-risney** [comment]
Thanks! We'll look into this.

**Comment by DavidShoe** [comment]
We have verified that this feature does in fact work.  But there are a couple of caveats.  Only one application at a time can use a particular CDP port.  So if you have an edge instance using  --remote-debugging-port=9222 and open a webview with that port also the webview will fail to open the port (silently).  If you were to use a different port (say 9223) for the webview and then use edge://inspect and configure it to watch 9223 you will see the webview show up.
