### ISSUE TITLE
WebView2 incompatible with low-integrity processes

### ISSUE THREAD

**Issue by forderud** [MicrosoftEdge/WebViewFeedback#198]
I'm unable to add a WebView2 control in my C# WinForms or WPF applications if the process is running in low integrity mode. This makes me unable to display web content with a more modern browser than IE in a security sandboxed .Net application.

## Steps to Reproduce
1. Clone & build https://github.com/MicrosoftEdge/WebView2Samples
2. For the WebView2WindowsFormsBrowser & WebView2WpfBrowser projects:
   - Start command prompt with admin permissions and run "`icacls <appname>.exe /setintegritylevel Low`" so that it will run in low integrity.
   - Start the application
   - Observe that the webpage loading fails silently _if_ the process is running in low integrity.

[Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) can be used to check if a process runs under the low, medium or high integrity.

## Expected behavior
The WebView2 control should start normally, as for medium or high-integrity processes.
The legacy `System.Windows.Forms.WebBrowser` have always supported low-integrity.

**Comment by david-risney** [comment]
Thanks for trying out WebView2!

I'll open a feature request for this. Can you elaborate a bit on your app's scenario? 

Just to confirm: your scenario requires running your app process at low IL and you're not running the app process at low IL just to get the WebView2 to run sandboxed, correct? 

WebView2 uses the same process model and security model as Edge and other Chromium browsers. The initial browser process runs at medium IL and the child renderer processes are sandboxed.

**Comment by forderud** [comment]
> I'll open a feature request for this. Can you elaborate a bit on your app's scenario? 
> Just to confirm: your scenario requires running your app process at low IL and you're not running the app process at low IL just to get the WebView2 to run sandboxed, correct?

My scenario is untrusted applications running in low IL on an embedded medical ultrasound device running Windows 10 IoT Enterprise. Low IL is used as a security mechanism to limit the attack surface. Some of these apps need to display webpages. The old IE-based `WebBrowser` control is currently used for this, but we really need to migrate to a more modern alternative.

> WebView2 uses the same process model and security model as Edge and other Chromium browsers. The initial browser process runs at medium IL and the child renderer processes are sandboxed.

You'll likely need to tweak the initial browser process a bit to make it low IL compatible. I've recently been involved in tweaking [Qt WebEngine](https://doc.qt.io/qt-5/qtwebengine-index.html), which is also Chromium-based, to become low IL compatible, so it should also be feasible for WebView2.

**Comment by david-risney** [comment]
Thanks, that's interesting to hear about your scenario.

We do currently support running the WebView2 from a process in an AppContainer if that's helpful.

**Comment by forderud** [comment]
> We do currently support running the WebView2 from a process in an AppContainer if that's helpful.

In the long run yes, but not at this point. We're currently unable to use AppContainer-based sandboxing due to limitations in Windows' ability to launch out-of-proc COM/OLE controls in an AppContainer process from a "regular" medium IL process. I've previously raised ticket 119040926000131 on this, and have been told that this is on the roadmap for a future Windows release.

**Comment by champnic** [comment]
@forderud We did some testing on our end and believe you may be able to get this to work by disabling SmartScreen. You can do that by adding this to the [AdditionalBrowserArguments ](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-538/icorewebview2environmentoptions#put_additionalbrowserarguments): `--disable-features=msSmartScreenProtection`

Can you give that a try?

**Comment by forderud** [comment]
I just tried the following:
1. Clone https://github.com/MicrosoftEdge/WebView2Samples.git @ a83baa548a33d02ef57d0a69929430fa037b6b41 (dated 2020-07-23)
2. Add a `CHECK_FAILURE(options->put_AdditionalBrowserArguments(L"--disable-features=msSmartScreenProtection"));` call beneath https://github.com/MicrosoftEdge/WebView2Samples/blob/a83baa548a33d02ef57d0a69929430fa037b6b41/SampleApps/WebView2APISample/AppWindow.cpp#L481
3. Build solution in x64 Debug
4. Run `icacls WebView2APISample.exe /setintegritylevel Low` to make the process start in low integrity level
5. Start WebView2APISample.exe

Observations:
* `options->put_AdditionalBrowserArguments(L"--disable-features=msSmartScreenProtection")` succeeded.
* `CreateCoreWebView2EnvironmentWithOptions` succeeded
* `AppWindow::OnCreateCoreWebView2ControllerCompleted` was afterwards called with `E_FAIL` and `nullptr` arguments

Sorry, but this still doesn't work for me. Any clues why?

**Comment by champnic** [comment]
The UserDataFolder also needs to be LowIL. If you are creating your own UserDataFolder you will need to icacls it too. Otherwise, can you try icacls on the whole app folder, rather than just the exe? If you don't provide a folder, we'll create a default one in the app folder (more details: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/userdatafolder)

**Comment by forderud** [comment]
Thanks a lot @champnic . I am now finally able to run WebView2APISample in low integrity level if passing e.g. userDataFolder=`L"C:\\Users\\<username>\\AppData\\LocalLow"` to `CreateCoreWebView2EnvironmentWithOptions`. This means that I now have a work-around 👍 

My next questions then would be if you could look into the following:
* Clearly document that "SmartScreen" is not low IL compatible and provide official advise on how to disable the feature.
* Consider changing defaults for where user-data is stored, so that WebView2 works out-of-the-box also in low IL, like Internet Explorer have done in the past. Maybe you could change the default folder to "AppData\LocalLow" like IE, or possibly adding gracefully fallback to in-memory storage if disk writes fail.

**Comment by champnic** [comment]
Great - glad it's working!

- We have an item tracking this in our backlog. We are currently working on the SmartScreen issue, and hope to instead fix the issue currently crashing SmartScreen in LowIL. If we don't fix that though, we'll definitely include this in our documentation.
- I've added your folder suggestions to the tracking item. Thanks :)

**Comment by champnic** [comment]
The SmartScreen crash in LowIL has been fixed, and should be in a Canary build tomorrow. We still plan to add better documentation for different integrity levels, a better default UserDataFolder experience, and have separate workitems tracking those improvements. I'm going to close out this item, but please reopen if I'm missing anything or you are still running into issues. Thanks!

**Comment by forderud** [comment]
Thanks a lot @champnic .

**Comment by forderud** [comment]
FYI: I just registered a new https://github.com/MicrosoftEdge/WebView2Feedback/issues/1969 issue for a related IFrame problem when running under low IL.

**Comment by szz743** [comment]
Hello,

I've just hit the similar problem, my low integrity process can create WebView2 objects just fine under all OS-es from Win 8 workstation to 2022 servers, but fails under Win 7 and 2008 r2  server..
CreateCoreWebView2Controller returns S_OK on those OS-es but the callback later fails with "access is denied" error.
I debugged the problem down to EmbeddedBrowserWebView!base::LaunchNonElevatedProcess which creates ShellWindows COM object. 
```
5fac6711 6800c2be5f      push    offset EmbeddedBrowserWebView!_GUID_85cb6900_4d95_11cf_960c_0080c7f4ee85 (5fbec200)
5fac6716 6a04            push    4
5fac6718 6a00            push    0
5fac671a 68a451bb5f      push    offset EmbeddedBrowserWebView!CLSID_ShellWindows (5fbb51a4)
5fac671f ff1528e5c35f    call    dword ptr [EmbeddedBrowserWebView!_imp__CoCreateInstance (5fc3e528)]
5fac6725 85c0            test    eax,eax
5fac6727 0f88ec010000    js      EmbeddedBrowserWebView!base::LaunchNonElevatedProcess+0x329 (5fac6919)

0:002> dt 5fbec200 _GUID
ole32!_GUID
 {85cb6900-4d95-11cf-960c-0080c7f4ee85}
```
CoCreateInstance call is the cause of "access is denied" error. which gets propagated up to the callback.
Interesting is that this COM object does not even get created on other OS-es 

Changing process to be "medium level" helps resolving the problem but that is not a solution.
ActiveX based IE engine works fine in the same scenarios.

Any advise how to resolve or workaround the problem?
thanks!
