### ISSUE TITLE
Example should show resizing control on Window resize

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftEdge/WebViewFeedback#2]
The [GettingStarted](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/gettingstarted) example doesn't show how to respond to window resize events and resize the WebView2 control to match.

It'd actually be nice if there was a link to a complete sample rather than having to follow-along to complete the full sample.

**Comment by david-risney** [comment]
Thanks. I've opened a bug for making our complete sample app public - it needs a bit of cleanup first.

I've also opened a bug for updating the GettingStarted example. At least it could have some links to documentation or the full sample app for how to do the resize.

**Comment by liminzhu** [comment]
Great feedback @michael-hawker! Definitely have some plans post //build to update the current sample and upload the completed one to github.

**Comment by liminzhu** [comment]
The [sample](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/gettingstarted) should handle app window resizing now.
