### ISSUE TITLE
LNK1107 for WebView2Guid.lib

### ISSUE THREAD

**Issue by gaborszanto** [MicrosoftEdge/WebViewFeedback#201]
In my Win32 C++ x64 project I get the following linker error:

LNK1107	invalid or corrupt file: cannot read at 0xB070	.....\packages\Microsoft.Web.WebView2.0.9.488\build\native\x64\WebView2Guid.lib

**Comment by david-risney** [comment]
Oh that's surprising!

If you get the [Win32 C++ sample app ](https://github.com/MicrosoftEdge/WebView2Samples/tree/master/WebView2APISample) do you see the same failure? Or if you remove and add back the WebView2 SDK package or update the package to the latest prerelease WebView2 SDK package do you see any difference?

**Comment by gaborszanto** [comment]
Maybe it's user error (me). If I'm doing the recommended WRL way in a simple app it works great.
But I'm trying to put this into a more "classic" context, into a VST plugin (which is a DLL).
In that context WRL causes various load library errors, so I'm trying to implement the create handlers based on IUnknown. In that case I get this strange linker error.

**Comment by gaborszanto** [comment]
More info: I'm trying to use this in a DLL (an audio VST plugin). It builds fine, when I'm loading the WebView using WRL. 
However LoadLibraryW doesn't load the product, it fails with error 126 (can't find the module) in this case.
If I add WebView2Loader.dll to additional linker dependencies, I get the LNK1107 error. So is it possible to use WebView2 in a DLL?

**Comment by gaborszanto** [comment]
This was a user error (me).
