### ISSUE TITLE
add_DocumentTitleChanged crashes

### ISSUE THREAD

**Issue by mariusbancila** [MicrosoftEdge/WebViewFeedback#207]
I have the following code to register a handle for the DocumentTitleChanged event:

```
CHECK_FAILURE(m_pImpl->m_webView->add_DocumentTitleChanged(
  Callback<ICoreWebView2DocumentTitleChangedEventHandler>(
     [this](ICoreWebView2* sender, IUnknown* args) -> HRESULT {
        wil::unique_cotaskmem_string title;
        CHECK_FAILURE(sender->get_DocumentTitle(&title));

        m_strTitle = title.get();
        
        return S_OK;
     })
  .Get(), &m_documentTitleChangedToken));
```

When calling add_DocumentTitleChanged, an Access violation occurs:

```
000000000000000()	Unknown
 	MfcEdgeDemo.exe!Microsoft::WRL::ComPtr<ICoreWebView2DocumentTitleChangedEventHandler>::InternalRelease() Line 176	C++
 	MfcEdgeDemo.exe!Microsoft::WRL::ComPtr<ICoreWebView2DocumentTitleChangedEventHandler>::~ComPtr<ICoreWebView2DocumentTitleChangedEventHandler>() Line 231	C++
>	MfcEdgeDemo.exe!CWebBrowser::RegisterEventHandlers() Line 305	C++
```
This comes from `ComPtr::InternalRelease()` method:
```
    unsigned long InternalRelease() throw()
    {
        unsigned long ref = 0;
        T* temp = ptr_;

        if (temp != nullptr)
        {
            ptr_ = nullptr;
            ref = temp->Release();   // <-------- HERE
        }

        return ref;
    }
```
The reason is that the vtable contains null pointers:
```
◢ | temp | 0x000001d0f01e11a0 {...} | ICoreWebView2DocumentTitleChangedEventHandler *
  | ◢ IUnknown | {...} | IUnknown
  | ◢ __vfptr | 0x000001d0f01c5100 {0x0000000000000000, 0x8800100043239257, 0x0000000000000000} | void * *
  | [0] | 0x0000000000000000 | void *      // <---- AddRef
  | [1] | 0x8800100043239257 | void *      // <---- QueryInterface
  | [2] | 0x0000000000000000 | void *      // <---- Release
```

I don't see the difference between my code and this code from https://github.com/MicrosoftEdge/WebView2Samples:
```
FileComponent::FileComponent(AppWindow* appWindow)
    : m_appWindow(appWindow), m_webView(appWindow->GetWebView())
{
    //! [DocumentTitleChanged]
    // Register a handler for the DocumentTitleChanged event.
    // This handler just announces the new title on the window's title bar.
    CHECK_FAILURE(m_webView->add_DocumentTitleChanged(
        Callback<ICoreWebView2DocumentTitleChangedEventHandler>(
            [this](ICoreWebView2* sender, IUnknown* args) -> HRESULT {
                wil::unique_cotaskmem_string title;
                CHECK_FAILURE(sender->get_DocumentTitle(&title));
                SetWindowText(m_appWindow->GetMainWindow(), title.get());
                return S_OK;
            })
            .Get(),
        &m_documentTitleChangedToken));
    //! [DocumentTitleChanged]
}
```
I have a full fledge app where this is demonstrated, available [here](https://mariusbancila.ro/blog/2020/01/29/using-microsoft-edge-in-a-native-windows-desktop-app-part-2/). 

I am running Edge v83.0.478.37 and WebView2 v0.9.488.

**Comment by david-risney** [comment]
Thanks for trying out WebView2 and for reporting this issue. We'll look into it.

Cool blog post series on WebView2!

**Comment by champnic** [comment]
@mariusbancila We were unable to repro this issue locally. From our investigation, we believe the issue is caused by a versioning mismatch. For the WV2 0.9.488 SDK you'll need to be running on a version of the browser n.n.488.n+. More details can be found here: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/versioning

In this particular case, the COM interface changed at some point between those versions, and so the code is likely not actually calling into the add_DocumentTitleChanged function which is causing the instability.

If you continue seeing this issue after upgrading your brower version, please let us know and we'll reactivate this issue. Thanks!
