### ISSUE TITLE
How to obtain html contents of the page

### ISSUE THREAD

**Issue by SachinL9** [MicrosoftEdge/WebViewFeedback#208]
I have created a winform application and used WebView2 control in it to navigate to a url. 
I would now want to read the whole html content of the page rendered in the WebView2 control. Please guide me how to achieve this?

In WebView control I achieved this using 

```c#
private void Wvc_DOMContentLoaded(object sender, WebViewControlDOMContentLoadedEventArgs e)
        {
            string html = webView.InvokeScript("eval", new string[] { "document.body.outerHTML" });
        }
```

**Comment by ukandrewc** [comment]
For the full html content (excluding Doctype)
`string html = await webView2.ExecututeAsync("document.documentElement.outerHTML");`
You don't need to eval, that is implicit in the call.
If you want access to the whole DOM, see here: https://github.com/ukandrewc/Webview2.Winforms.DOM

**Comment by SachinL9** [comment]
Thank you for the quick reply. Got it working using your suggestion.

Here is the code if anyone needs
```
var html = await webView2.CoreWebView2.ExecuteScriptAsync("document.body.outerHTML");
var htmldecoded = System.Web.Helpers.Json.Decode(html);
```

**Comment by ukandrewc** [comment]
Ah yes, forgot about unescaping the JSON

**Comment by docbaf** [comment]
Loving your DOM implementation.  Using it to remote control a web page.  Can't seem to get the 'checked' attribute of a checkbox.  Can find it and assign it to an WVHTMLElement, but then cannot access the .checked attribute.  Any suggestions?

**Comment by wgtgithub** [comment]
> For the full html content (excluding Doctype) `string html = await webView2.ExecututeAsync("document.documentElement.outerHTML");` You don't need to eval, that is implicit in the call. If you want access to the whole DOM, see here: https://github.com/ukandrewc/Webview2.Winforms.DOM

no reply

**Comment by wgtgithub** [comment]
> Thank you for the quick reply. Got it working using your suggestion.
> 
> Here is the code if anyone needs
> 
> ```
> var html = await webView2.CoreWebView2.ExecuteScriptAsync("document.body.outerHTML");
> var htmldecoded = System.Web.Helpers.Json.Decode(html);
> ```

no reply

**Comment by briangdd** [comment]
If anyone needs to do this in newer versions of .NET (.NET7) - using JSON.NET as System.Web.Helpers doesn't seem to be available for .NET7 in a WPF application.
```
var html = await webView2.CoreWebView2.ExecuteScriptAsync("document.body.outerHTML");
var htmldecoded = JsonConvert.DeserializeObject(html).ToString();
```
Obviously add your own error checking (for null etc.) and you can use System.Text.JSON instead of JSON.NET
