### ISSUE TITLE
[Question] Support rendering for PDF and Word files

### ISSUE THREAD

**Issue by shaggygi** [MicrosoftEdge/WebViewFeedback#21]
Not being familiar with this control and direction being used, I'm assuming it will be included in WinUI 3.0 eventually.

Is the plan to support native rendering for PDF and Word docx files?  If so, will this be able to run on Win7 and Win10.  Lastly, can the control be used in WPF and UWP type apps for development?

Thanks in advance for any help.

**Comment by david-risney** [comment]
Thanks for the questions!
 * UI framework support: We're working on support for WPF and WinForms as well as UWP & XAML. 
 * OS support: We generally intend to support the same set of OSes as the Edge (Chromium) browser which should include support to down to Win7. 
 * File types: We generally intend to support whatever the Edge (Chromium) browser supports. I believe that includes PDF but not sure about docx?

Can you describe your scenarios? Do you have a particular need for PDF, Word doc rendering or Win7 support? Thanks!

**Comment by shaggygi** [comment]
@david-risney Thanks for the reply.  I just found out that we will be migrated to Windows 10 before the development/deployment of the related project we would possibly be using this control.  Therefore, in our case, we would not need the Win7 requirement (but would be nice if it also supported that OS).

We are looking at methods to load/display documents and need to be able to view various types of files.  In most cases, we will be able to save the related files as PDFs.  However, there may be cases where they are in docx and Visio-type format, as well.  All files would be read-only and for viewing purposes only within the app/WebView control.

The docs will be stored in a location on SharePoint server and would like to use the WebView control to load based on url of selected file(s).  We would rather the app (with WebView control) navigate/display the files rather than loading the native viewing app (e.g. Adobe Reader, Word, etc.).  Each machine running the app would have licensed Office, of course (if that was an issue with viewing those types of files).

I thought I read somewhere before that Chrome and Edge had the ability to render docx.  Again, I haven't reviewed this new WebView control in detail since it is in preview.  I'm hoping it can provide what we're trying to accomplish.

Hope this helps with a little more insight of what we plan to use the WebView for.  Thanks again.

**Comment by rajsite** [comment]
@david-risney Do you know when the .NET WinForm Control may be available? I'm interested in using it in the LabVIEW development environment which has some restrictions on what .NET controls and assemblies can be used.

Hopefully if it's known early enough in development then certain use cases could be considered. Some ideas of the environment:
- [.NET Features Unsupported By LabVIEW](https://knowledge.ni.com/KnowledgeArticleDetails?id=kA00Z000000P8iWSAS&l=en-US)
- [Requirements for Using .NET Assemblies in LabVIEW](https://zone.ni.com/reference/en-XX/help/371361R-01/lvconcepts/net_defaults/)
- [Creating .NET Controls in a .NET Container](https://zone.ni.com/reference/en-XX/help/371361R-01/lvhowto/create_dotnet_controls/)

I would love to try it out for our use cases when it's available to test.

**Comment by david-risney** [comment]
.NET support is high on our list of tasks (including WPF & WinForms) but we don't have a fixed date yet. We'll take a look at those links, thanks!
