### ISSUE TITLE
Feature request: Azure AD conditional access?

### ISSUE THREAD

**Issue by llehn** [MicrosoftEdge/WebViewFeedback#211]
I'd love to use WebView2 to create a desktop application which would allow accessing cloud websites, which in turn are protected by Azure AD Conditional Access, requiring a managed device.

Currently this seems impossible to accomplish using neither electron nor webview nor any other way I looked at. 

Is this something that can be done?

**Comment by david-risney** [comment]
Thanks, great feature request!

**Comment by champnic** [comment]
This should be enabled by [SSO support](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-538/icorewebview2experimentalenvironmentoptions#get_issinglesignonusingosprimaryaccountenabled) in the new 0.9.579 SDK. Thanks!
