### ISSUE TITLE
Added js not available after navigation

### ISSUE THREAD

**Issue by johansme** [MicrosoftEdge/WebViewFeedback#220]
In the WinForms version of WebView2, js code added using the `CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync` method is not available by the time the `NavigationCompleted` event is raised. I would like to add a new js namespace with `AddScriptToExecuteOnDocumentCreatedAsync`, and then, in some cases, call functions from that namespace from the `NavigationCompleted` event handler.

In the following example, with a standard Visual Studio WinForms template with WebView2 added, I would expect an alert with 'Test' after navigation completed. However, `window.TestNamespace` is `undefined`.
```
public partial class Form1 : Form
{
	public Form1()
	{
		InitializeComponent();
		InitialiseAsync();
		webView21.NavigationCompleted += HandleNavigationCompleted;
	}

	private async void InitialiseAsync()
	{
		await webView21.EnsureCoreWebView2Async();
		await webView21.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync("TestNamespace = {test_log: function(){ alert('Test')}};");
	}

	private async void HandleNavigationCompleted(object sender, CoreWebView2NavigationCompletedEventArgs e)
	{
		await webView21.ExecuteScriptAsync("window.TestNamespace.test_log()");
	}
}
```
This is with the WebView2 0.9.515-prerelease version, and Edge Canary v85.0.528.0.

**Comment by ukandrewc** [comment]
Not sure if this is down to the Edge version, but I'm doing that to provide DOM access from .net, which is working.
