### ISSUE TITLE
feature request: please add FullScreenChanged, OnClickElement, newWindow events.

### ISSUE THREAD

**Issue by FRsyesCD** [MicrosoftEdge/WebViewFeedback#223]
i'd like u to add almost all winforms webbrowser IE based events like FullScreenChanged, OnClickElement(the clicked html element), newWindow .....

**Comment by david-risney** [comment]
The WinForms WebView2 control has a CoreWebView2 property that exposes the FullScreenChanged and NewWindowRequested events.

We don't have DOM APIs exposed like OnClick but you can use ExecuteScriptAsync to inject script to interact with the DOM and receive synchronous results back or the WebMessageReceived event to receive asynchronous results back.

**Comment by ukandrewc** [comment]
There is an experimental DOM implementation here: https://github.com/ukandrewc/Webview2.Winforms.DOM
It raises mouse, input and keyboard events. They are all passive except for click which can be cancelled.

**Comment by FRsyesCD** [comment]
> There is an experimental DOM implementation here: https://github.com/ukandrewc/Webview2.Winforms.DOM
> It raises mouse, input and keyboard events. They are all passive except for click which can be cancelled.

where did u get it from ? i think that an webdriver alternative for webview2 there is no need to it ?

**Comment by ukandrewc** [comment]
OK, then don't use it ;-)

**Comment by FRsyesCD** [comment]
:/ i'm just asking i like it but it seems that u used a developed framework and it must be developed by someone, anyway the answer for my question is that webview2 has a CoreWebView2 property that exposes the FullScreenChanged and NewWindowRequested events.

**Comment by ukandrewc** [comment]
It's a DOM implementation for Winforms, not a WebDriver alternative.

**Comment by FRsyesCD** [comment]
nice i will take a look at it thanks anyway
