### ISSUE TITLE
Is webrtc supported in WebView2?

### ISSUE THREAD

**Issue by arpftp** [MicrosoftEdge/WebViewFeedback#226]
As per title. Is webrtc supported in WebView2?

**Comment by nicholasdgoodman** [comment]
From the looks of it, yes.

Loading
https://webrtc.github.io/samples/
into a WebView2 instance appears to be mostly working.

**Comment by david-risney** [comment]
Generally we support the same features as the Edge browser including WebRTC.

Please let us know if you find that WebRTC or other DOM features aren't working well in WebView2
