### ISSUE TITLE
Rogue debugger statement on page reload with dev tools open

### ISSUE THREAD

**Issue by smimon** [MicrosoftEdge/WebViewFeedback#233]
I'm launching a WebView2 instance and then opening dev tools programmatically. On first load, all is fine.

However, any subsequent page refreshes cause dev tools to hit a debugger statement in some injected code, the first lines of which are:
![image](https://user-images.githubusercontent.com/2358820/83330870-4dbced80-a2bc-11ea-9e89-0fecc3059fed.png)

Did someone forget to take this out before the package was published? Or can it be popping up for some other reason?

Many thanks

**Comment by david-risney** [comment]
Thanks for reporting this! I'll look into it.

**Comment by smimon** [comment]
Oddly enough, this issue disappeared today - I'm not sure what changed, but evidently whatever was triggering the inclusion of that script with the debugger statement isn't happening any more.

**Comment by champnic** [comment]
This was fixed in Edge 85.0.535.0+. Thanks!
