### ISSUE TITLE
[DMC] I can't reference this namespace on xaml #724

### ISSUE THREAD

**Issue by Reezaali** [MicrosoftEdge/WebViewFeedback#234]
Please see this issue about the WPF Getting started guide: 
https://github.com/MicrosoftDocs/edge-developer/issues/724

Thank you.

**Comment by pagoe-msft** [comment]
Could you let me know what step did not work for you?

Possible issues:
1. Have you installed the Canary Version of Microsoft Edge?
https://www.microsoftedgeinsider.com/en-us/download

2. Are you working on Visual Studio 2017 or 2019?
3. Do you have the correct NuGet package?

**Comment by Reezaali** [comment]
Closing this issue because no feedback was received. Thanks.
