### ISSUE TITLE
webviewWindow not defined !

### ISSUE THREAD

**Issue by Fxztam** [MicrosoftEdge/WebViewFeedback#24]
I am on VS 2017 15.9.13  and  Microsoft.WebWebView2 0.8.190 , 
reading [https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/gettingstarted](url)

- Step 2 - Install WebView2 SDK - incl. 

   _// include WebView2 header
   #include "WebView2.h"_
   
![image](https://user-images.githubusercontent.com/5808032/59914819-7d604600-941b-11e9-90d0-89f6be74e111.png)
 
works for me.

After including the Webviewer code between:

   _// <-- WebView2 sample code starts here -->_ ..

I am getting : **_" .. webviewWindow not defined .. "_**

![image](https://user-images.githubusercontent.com/5808032/59914606-032fc180-941b-11e9-805b-c6a5b304f582.png)

What is wrong and how to define it ?

Thanks,
Friedhold

**Comment by bgrainger** [comment]
You're missing these lines of code from the sample:

https://github.com/MicrosoftEdge/WebView2Samples/blob/7a10488116ad4af0fbe529fb00ff48c7ef46736a/WebView2Sample/HelloWebView.cpp#L26-L27

**Comment by Fxztam** [comment]
Yes, now it works.
Thanks
