### ISSUE TITLE
Cannot change pointer

### ISSUE THREAD

**Issue by mqudsi** [MicrosoftEdge/WebViewFeedback#242]
In a WinUI 3 project with WebView2 loading an HTML document, the shape of the mouse pointer/cursor does not change in the same way it would in WebView 1 or in a native Edgium session. It does not change when hovering over a link and using the CSS `cursor` property (e.g. on hover over a certain element) does not actually result in any updates to the mouse cursor.

**Comment by pagoe-msft** [comment]
@mqudsi 

WinUI is an open source project and has a separately managed feedback repo. Could you repost this issue here: https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose

Thanks!

**Comment by mqudsi** [comment]
I assumed the issue is with the WebView2 control (associated with this repo) and is just packaged alongside WinUI.

**Comment by codendone** [comment]
This is a WinUI issue -- we need to hook up to the underlying support from the core WebView2.  Thanks for logging the issue over in that repo, which we'll update when the task is complete.
