### ISSUE TITLE
WebView.CapturePreviewToStreamAsync in webview2

### ISSUE THREAD

**Issue by FireCubeStudios** [MicrosoftEdge/WebViewFeedback#244]
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.capturepreviewtostreamasync?view=winrt-19041

will this be coming to webview 2 in the future. its the only thing preventing me from transitioning to webview 2 completely.

**Comment by liminzhu** [comment]
We have [CapturePreview](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-538/icorewebview2#capturepreview) in C++ that should let you do this. There is corresponding [.NET API](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/dotnet/0-9-538/namespace-microsoft-web-webview2-core#corewebview2capturepreviewimageformat) as well.

**Comment by liminzhu** [comment]
Closing this issue as the functionality exists today. Feel free to re-open if this is not what you have in mind.
