### ISSUE TITLE
Question about accessing window.chrome.webview.postMessage from Angular

### ISSUE THREAD

**Issue by frazierb2112** [MicrosoftEdge/WebViewFeedback#247]
I am prototyping a planned re-write of the UI of my application to Angular and everything works great with hosting it in the WebView2.  My problem\issue\"I'm just plain dumb" it that I can't figure out how to get the my Angular app to "talk to" the hosting WPF application.  I've follow the several examples\suggestions using window.chrome.webview.postMessage on the web side and WebMessageReceived on the WPF side with no luck. So on the WPF side:

`await webView.EnsureCoreWebView2Async(null);
 webView.CoreWebView2.WebMessageReceived += Ping;`

..
..

`void Ping(object sender, CoreWebView2WebMessageReceivedEventArgs args)
        {
            string message = args.TryGetWebMessageAsString();
            ShowMessage(message);
        }`

and on the Angular side, Javascript function:

`var interopFunctions = function(){
    var sendMessage = function(message){
        window.chrome.webview.postMessage(message);
        return true;
    };
    return {
        sendMessage : sendMessage
    }
}();`

Used like so:

`declare const interopFunctions: any;`
..
..
`interopFunctions.sendMessage("Loaded");`

And I get the following error in the console:

ERROR TypeError: Cannot read property 'postMessage' of undefined.

Any direction would be helpful.

Thanks.

**Comment by shawty** [comment]
I can't quite make out what your doing from the code in your post above, it's difficult to read with the formatting you've used.

However, I'm working on a C# winforms (NOT WPF) application, and I've made a lot of use of post message for some of the features I'm adding.

First up on the C# side:

in my main windows form constructor I have this
![image](https://user-images.githubusercontent.com/1876454/83969984-eb22ad80-a8ca-11ea-9213-a0aaac14ed0f.png)

Specifically, line 18 is the important line.

The core ready handler referenced in line 18 looks as follows
![image](https://user-images.githubusercontent.com/1876454/83970024-2ae99500-a8cb-11ea-887b-f5e6322f6e8e.png)

I'm storing my JS files as resources in the compiled binary, so don't worry about the resource loader call, the important line is line 63 that sets up the web message received  event handler.

For now I just have a dummy handler in my web message received handler, as I'm busy building out a better more object orientated way of doing it, which is not ready to be published yet.

![image](https://user-images.githubusercontent.com/1876454/83970078-9895c100-a8cb-11ea-9f72-6619413fe889.png)

If you use "e.WebMessageAsJson" as I have here, then you get a JSON string that's ready to de-serialize back to an object using Newtonsoft JSON or the Core JSON text handlers.

Sending data using "PostWebMessageAsString" does exactly what the name suggests, it sends the exact string you tell it to, and it sets the media type as plain text.

If you use "PostWebMessageAsJson" and give it a serialized string, it will send it exactly as a JSON string, which you will then get as a JSON object on the JS side.

On my JS side of things (BrowserInternals.js as seen in the image above) I have the following

First off, the code to receive the messages sent to the JS
![image](https://user-images.githubusercontent.com/1876454/83970210-69cc1a80-a8cc-11ea-92b5-a918efc168f5.png)

e.Data will hold whatever was sent from the C# call either as a string or a JSON object.

Sending from JS is just as easy, although I seem to have lost the JS file I had with some code showing it in.  It's just a one liner though, same as calling from CSharp, and when it executes it should hit the C# message received event above.

**Comment by mikemeinz** [comment]
Insert this line after setting the event handler for CoreWebView2Ready at line 19.
`            InitializeAsync();`

Add this method into your program.
```
        async private void InitializeAsync()
        { 
            await webview.EnsureCoreWebView2Async(); // Wait for coreWebView2 initialization
        }
```

**Comment by frazierb2112** [comment]
@shawty, sorry about the formatting, but you got what I was asking.   I added the handler for CoreWebView2Ready as you had done on line 18 and moved my WebMessageReceived hookup there, your line 63.  Funny thing is, that WebView_CoreWebView2Ready method is never hit, even after my window is loaded and the control has navigated to my url. So I moved it to a window "Loaded" event and from there it is properly wired up and is hit, which is good. 

![image](https://user-images.githubusercontent.com/25672825/84024063-32ef1680-a957-11ea-86c5-c898f133e811.png)

![image](https://user-images.githubusercontent.com/25672825/84024156-5b771080-a957-11ea-83e0-30bdab828693.png)

![image](https://user-images.githubusercontent.com/25672825/84024218-79dd0c00-a957-11ea-997a-bf0bdf07ee4a.png)


But, my C# still does't "catch" any of the messages sent form the web page, JavaScript below:

![image](https://user-images.githubusercontent.com/25672825/84023928-f6231f80-a956-11ea-8550-3a98e74f94a0.png)



@mikemeinz, I do have you suggested method and I did move the call to after the webView.CoreWebView2Ready += WebView_CoreWebView2Ready; , but didn't help.

**Comment by shawty** [comment]
@frazierb2112 the reason your not catching any of the messages you post from your java-script is because your using the wrong API.

Replace your 

```
window.postMessage(message);
```

with

```
window.chrome.webview.postMessage(message);
```

and everything should start to work.

Everything you need to know is in the .NET getting started guide:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms

**Comment by frazierb2112** [comment]
Well I'll be damned, that worked  I had tried that before (prior to your suggestions) and from within the browser console, I get this message (and still do):

ERROR TypeError: Cannot read property 'postMessage' of undefined

I guess I can "ignore" that error.

Thanks for your help!

**Comment by shawty** [comment]
@frazierb2112 I've no idea why that error shows up for you in the browser console, it works perfectly fine from the console for me :-)

Glad you got it working anyway.

Keep an eye on my github, because I'll be releasing the project I'm working on once I'm happy with a first version, and a lot of these techniques I'm using to implement extended browser API's and event services.

I'm building a custom desktop browser that implements the OIPF Smart TV API's so I can use my PC to develop HTML Based TV applications that conform to HbbTV 2.0

I'm using post message to allow my C# code to raise various JavaScript events such as low memory and video play state calls.

I do this essentially by sending a custom json message that holds a message type "event" and an event name EG : "onLowMemory" along with a data payload.

I then have a single handler in my JS polyfill code that intercepts these messages, and re-raises a new even eg "document.displatchEvent(payload.eventName, payload.data)" which I then look for in the API classes that need to know about it.

It works really well.

**Comment by subhashreesahu1999** [comment]
where u write java script can please upload your code  Shawty in git hub...i am new to .net and also i don't js ...

**Comment by subhashreesahu1999** [comment]
> @frazierb2112 the reason your not catching any of the messages you post from your java-script is because your using the wrong API.
> 
> Replace your
> 
> ```
> window.postMessage(message);
> ```
> 
> with
> 
> ```
> window.chrome.webview.postMessage(message);
> ```
> 
> and everything should start to work.
> 
> Everything you need to know is in the .NET getting started guide: https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/

> @frazierb2112 I've no idea why that error shows up for you in the browser console, it works perfectly fine from the console for me :-)
> 
> Glad you got it working anyway.
> 
> Keep an eye on my github, because I'll be releasing the project I'm working on once I'm happy with a first version, and a lot of these techniques I'm using to implement extended browser API's and event services.
> 
> I'm building a custom desktop browser that implements the OIPF Smart TV API's so I can use my PC to develop HTML Based TV applications that conform to HbbTV 2.0
> 
> I'm using post message to allow my C# code to raise various JavaScript events such as low memory and video play state calls.
> 
> I do this essentially by sending a custom json message that holds a message type "event" and an event name EG : "onLowMemory" along with a data payload.
> 
> I then have a single handler in my JS polyfill code that intercepts these messages, and re-raises a new even eg "document.displatchEvent(payload.eventName, payload.data)" which I then look for in the API classes that need to know about it.
> 
> It works really well.

can please upload your cod ein git hub

**Comment by shawty** [comment]
My code IS already in github for this project, it has been for years now.

https://github.com/shawty/hbbtvbrowserEXPERIMENTAL
