### ISSUE TITLE
Setting request header on NavigationStarting has no effect

### ISSUE THREAD

**Issue by bgrainger** [MicrosoftEdge/WebViewFeedback#25]
[Documentation of `IWebView2HttpRequestHeaders`](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2httprequestheaders#interface_i_web_view2_http_request_headers) says:

> Used to inspect or modify the HTTP request on WebResourceRequested event and NavigationStarting event.

I took the sample web view application and modified the navigation starting event handler (from step 4) to set a header: https://github.com/bgrainger/WebView2Samples/commit/4a1950b4a205d4c6eb3a8ff01a1ff1f0c670cc35

```csharp
IWebView2HttpRequestHeaders* headers = nullptr;
args->get_RequestHeaders(&headers);
HRESULT hr = headers->SetHeader(L"X-Test", L"test");
headers->Release();
```

But I can't see any evidence that the new header is being sent with the outgoing HTTP request. Fiddler doesn't show it, and Dev Tools doesn't show it (in the Network tab).

Microsoft.Web.WebView2 0.8.190

**Comment by bgrainger** [comment]
It does work when using the WebResourceRequested event:

```csharp
PCWSTR all_urls[] = { L"*" };
WEBVIEW2_WEB_RESOURCE_CONTEXT all_contexts[] = {
	WEBVIEW2_WEB_RESOURCE_CONTEXT_ALL };
webviewWindow->add_WebResourceRequested(all_urls, all_contexts, 1, Callback<IWebView2WebResourceRequestedEventHandler>(
	[](IWebView2WebView* webview, IWebView2WebResourceRequestedEventArgs* args) -> HRESULT {
		IWebView2WebResourceRequest* request = nullptr;
		args->get_Request(&request);
		IWebView2HttpRequestHeaders* headers = nullptr;
		request->get_Headers(&headers);
		HRESULT hr = headers->SetHeader(L"X-Test", L"test");
		headers->Release();
		request->Release();
		return S_OK;
	}).Get(), &token);
```

With this code, the header is added to all outgoing requests. However, I expected to be able to do it from the `IWebView2NavigationStartingEventHandler`, based on the documentation.

**Comment by yildirimcagri** [comment]
Hi, thanks for the feedback. The documentation is actually wrong on this one, the HttpRequestHeaders was not intended to be changed on NavigationStarting event and you are right to use the WebResourceRequested event. If you only need to change the headers for navigations, you could specify the WEBVIEW2_WEB_RESOURCE_CONTEXT_DOCUMENT resource filter to the WebResourceRequeseted event. Will update the documentation.

**Comment by liminzhu** [comment]
@bgrainger hopefully this works for you! If you do have a scenario that needs this to work in navigationStarting, let us know!

**Comment by bgrainger** [comment]
I just used `NavigationStarting` because it seemed easier. As it turns out, I'll want to add a custom HTTP header to all requests for a particular domain, so `WebResourceRequested` is the right event to handle anyway.

If this is a known documentation issue that'll be addressed, this case can be closed.
