### ISSUE TITLE
(Suspected Bug) Cannot set the response type in a web resource request event

### ISSUE THREAD

**Issue by shawty** [MicrosoftEdge/WebViewFeedback#254]
I'm working with a scenario where I want to load a custom request into an image tag on a web page, and the image is to be generated by the C# app hosting the WebViewControl.

In my app set up, I have the following:

![image](https://user-images.githubusercontent.com/1876454/84200285-64262e80-aa9e-11ea-9d88-4121d07ba117.png)

In javascript code in the page loaded into the control, I have this javascript

![image](https://user-images.githubusercontent.com/1876454/84200359-86b84780-aa9e-11ea-8b6f-ceb4b65421d8.png)

When the resource is requested by the page, the event handler in my app is fired (As Expected), my C# code in the handler looks like this

![image](https://user-images.githubusercontent.com/1876454/84200616-06461680-aa9f-11ea-95c2-46c77f59deba.png)

When the handler runs, this seems to set ok, no errors, no compile time problems etc, but soon after the entire app stops at the main entry point with a null reference.

![image](https://user-images.githubusercontent.com/1876454/84200858-45746780-aa9f-11ea-9dc8-2451846eacdb.png)

If I breakpoint on my handler app, and inspect the event object just before it returns, you can clearly see that "e.Response" is null, despite my code assigning a value to it.

![image](https://user-images.githubusercontent.com/1876454/84201054-984e1f00-aa9f-11ea-92bb-1a0a73d67fd2.png)

It seems to me that this is the correct process for handling a web resource request, can the team confirm if it is?

I'm currently working in .NET 4.7 with a WinForms app, but have been testing in Core too.

**Comment by pagoe-msft** [comment]
Closing this issue because it is being tracked in #219

**Comment by shawty** [comment]
I thought I'd already closed this one myself :-)

Oh well... I blame friday :-)
