### ISSUE TITLE
Handling of userDataFolder when multiple WebView2-Instances are created

### ISSUE THREAD

**Issue by Urmeli0815** [MicrosoftEdge/WebViewFeedback#257]
Can you clarify the handling of the `userDataFolder` parameter of `CreateCoreWebView2EnvironmentWithOptions`?

In one use-case it works to use the same folder for multiple instances of the WebView. In another use-case I get this error:
`HResult=0x8007139f, Error=The group or resource is not in the correct state to perform the requested operation.`

In the second use-case I use `additionalBrowserArguments` in a `CoreWebView2EnvironmentOptions` object to pass a proxy to the control, so this seems to make the difference. But it would be helpful to make this clear in the documentation.

**Comment by pagoe-msft** [comment]
@Urmeli0815 

Yes, this is something we need to do a better job documenting. It is possible to use the same user data folder for multiple instances of WebView2. Could you provide steps for me to follow to repro the error you're running into?

**Comment by Urmeli0815** [comment]
I hoped you could tell what goes wrong as `CreateCoreWebView2Controller` returns this error. So I basically have code similar to this:

```
...
	hr = m_webViewEnv->CreateCoreWebView2Controller(
		m_hWnd,
		wrl::Callback<ICoreWebView2CreateCoreWebView2ControllerCompletedHandler>(
			&EdgeBrowserControl::OnCreateCoreWebView2ControllerCompleted, this).Get());

	return hr.GetValue();
}

HRESULT EdgeBrowserControl::OnCreateCoreWebView2ControllerCompleted(ComHResult hr, ICoreWebView2Controller* controller)
{
	RETURN_IF_FAILED(hr, L"CreateCoreWebView2Controller");
...
```

which then returns this error when the second webview is opened:
```
EdgeBrowserControl::OnCreateCoreWebView2ControllerCompleted: CreateCoreWebView2Controller failed with [HResult=0x8007139f, Error=The group or resource is not in the correct state to perform the requested operation.]
```

This does not happen when I use a different userDataFolder for each webview so the error seems to be related to that.

I tried to reproduce it with the WebView2 samples but failed, so I can't give you more details.
In which cases does `CreateCoreWebView2Controller` return 0x8007139f?

**Comment by pagoe-msft** [comment]
@Urmeli0815:

We just published documentation on Managing the User data folder: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/userdatafolder

WebView2 controls that share the same user data folder must use the same options - does this cause the error?

**Comment by Urmeli0815** [comment]
@pagoe-msft Yes, this is the problem as we pass a different "--proxy-server" strings as additional command line arguments. Thank you for the clarification!

**Comment by pagoe-msft** [comment]
That's great to hear @Urmeli0815! Closing this issue now.
