### ISSUE TITLE
0.9.538 NuGet package missing Lib

### ISSUE THREAD

**Issue by jpalo** [MicrosoftEdge/WebViewFeedback#258]
When updating from 0.9.515-prerelease (or 0.9.538-prerelease) to 0.9.538, it adds no References. The references missing can be seen in the picture. Works fine up to 0.9.538-prerelease.

![image](https://user-images.githubusercontent.com/6917905/84300150-95643480-ab5a-11ea-91e9-d77da5ccf082.png)

And obviously it will throw a lot of errors, as in this pic.
![image](https://user-images.githubusercontent.com/6917905/84300423-f0962700-ab5a-11ea-826d-5d87b789207f.png)

Looks like it's just missing the Lib folder.
![image](https://user-images.githubusercontent.com/6917905/84300827-76b26d80-ab5b-11ea-850b-4b44eb90ab95.png)

**Comment by rkacharov** [comment]
Same here. I downloaded the [WebView2WindowsFormsBrowse](https://github.com/MicrosoftEdge/WebView2Samples/tree/master/WebView2WindowsFormsBrowser) project, initially `0.9.538 prerelease` is in use and its works fine until I updated the package to `0.9.538`. Now I get ```Error	CS0234	The type or namespace name 'Web' does not exist in the namespace``` and few more "type or namespaces not found" exceptions.
Not working even on new Windows Forms project (WebView2 control is not in the toolbox).

**Comment by mikemeinz** [comment]
I reported this same issue earlier this week. My issue has been closed. The response was that 0.9.538 was not meant for use by  .NET developers. They said to use 0.9.538-prerelease.

**Comment by jpalo** [comment]
Thank you @mikemeinz, closing this.

**Comment by TriSysBusinessSoftware** [comment]
I have just installed 0.9.538 in Windows 10 64-bit using Nuget in Visual Studio 2019 in a WinForms .Net 4.7.2 project and I can confirm that the WebView2 does NOT appear in the toolbox.
