### ISSUE TITLE
0.9.538-prerelease is missing .NET Core WinForms dll

### ISSUE THREAD

**Issue by MatthewBeardmore** [MicrosoftEdge/WebViewFeedback#262]
![image](https://user-images.githubusercontent.com/808932/84399914-64721700-abcf-11ea-9f92-acbb6697b7a5.png)

.NET Framework has Microsoft.Web.WebView2.WinForms.dll, however, .NET Core does not have this unlike the previous 0.9.515-prerelease package. Since this is missing, none of the WebView2 code for WinForms exists in this release.

[AB#26932700](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/26932700)

**Comment by oggy22** [comment]
Hi Matthew, thank you for reporting the issue. It is entirely our fault that we accidentally removed netcore from the control. We will fix it with the next release, but in meantime you can use the previous version which does support netcore: 

https://www.nuget.org/packages/Microsoft.Web.WebView2/0.9.515-prerelease

**Comment by shawty** [comment]
@oggy22 would this be the reason that the current NuGet build doesn't show up in the VS Toolbox when trying to use the control in a Windows Forms Dotnet Core project?

At the moment I can only get the control to show up in the toolbox for a Windows Forms project based on the older full fat .NET framework.

**Comment by pagoe-msft** [comment]
@shawty - yes this would be the reason it doesn't appear in the VS Toolbox

**Comment by shawty** [comment]
@pagoe-msft awesome, thanks... I'll just keep an eye on this one then.

Works perfectly fine under standard .NET Winforms, just not under Core WinForms

**Comment by MatthewBeardmore** [comment]
This is expected, until later this year. The problem I reported was that even in the prerelease package, the WinForms dell was missing in 0.9.538-prerelease.
