### ISSUE TITLE
Need some way to get page/document title

### ISSUE THREAD

**Issue by dd8** [MicrosoftEdge/WebViewFeedback#27]
MsHtml WebBrowserControl has DISPID_TITLECHANGE event
MFC CHtmlView has OnTitleChange event handler
Windows.UI.Xaml.Controls.WebView has DocumentTitle property
macOS WkWebView has title property

Needed for apps that display page title in their UI

Executing a script to get DOM document.title is not equivalent - what happens if scripting is disabled or document is not HTML (e.g. PDFs)

**Comment by david-risney** [comment]
That makes sense. Great feedback. We'll look into this. Thanks!

**Comment by dd8** [comment]
The property has the advantage of being simple, but there's no way to notify the app of a change (e.g. when view content fetched by XmlHttpRequest sets document.title) and you probably need locking to avoid accessing property during an async update.

The event handles changes to document.title naturally and might not require locking, but might not fit so well with the WebView2 event model.

**Comment by david-risney** [comment]
Thanks. Just offhand I was imagining a DocumentTitle property and a DocumentTitleChanged event. We'll look into what works best.

**Comment by lingamy** [comment]
Hi Mark, thanks for submitting the feedback! We’ve added new APIs [get_DocumentTitle](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview3#get_documenttitle) and [add_DocumentTitleChanged ](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview3#add_documenttitlechanged)for getting the title of the current top level document and getting notification for the document title change in the new [SDK update](https://www.nuget.org/packages/Microsoft.Web.WebView2/0.8.270). Make sure you update the SDK and use the canary channel for testing.
