### ISSUE TITLE
WebView2 RemoveScriptToExecuteOnDocumentCreated

### ISSUE THREAD

**Issue by ansalc** [MicrosoftEdge/WebViewFeedback#274]
After 

            jsCode = File.ReadAllText("JavaScript1.js");
            await WebView.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync(jsCode);

I need to remove the added Script.

I am thus using:

  jsCode = File.ReadAllText("JavaScript1.js");
 WebView.CoreWebView2.RemoveScriptToExecuteOnDocumentCreated(jsCode);

However, the Script removal does not work. The first Script is still in effect in new navigations.

What is the correct way to remove the added script?

**Comment by ukandrewc** [comment]
AddScriptToExecuteOnDocumentCreatedAsync, returns an ID, you need to use that.

**Comment by ansalc** [comment]
> AddScriptToExecuteOnDocumentCreatedAsync, returns an ID, you need to use that.

Indeed! It works great.

This is what I am using: 

string AddScriptId = await WebView.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync(jsCode);
   WebView.CoreWebView2.RemoveScriptToExecuteOnDocumentCreated(AddScriptId);

The only documentation about this is what I found at
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-538/icorewebview2#addscripttoexecuteondocumentcreated

Can one learn from the above documentation that the AddScriptToExecuteOnDocumentCreatedAsync returns the ID to be used in the removal?

I am asking in case I am missing how to interpret correctly the information provided in that documentation.

Many thanks indeed @ukandrewc

**Comment by ukandrewc** [comment]
Everything is beta, so nothing is complete yet, you can also get some insight by checking the auto-complete help in VS.

**Comment by ansalc** [comment]
Yes. I can feel the newness of these tools. But I can also see their potential. Well worth the effort.

I look forward for a fully developed Webview2 control.

Thank you again
