### ISSUE TITLE
[DMC] Missing "Getting Started with WinUI 3" #737

### ISSUE THREAD

**Issue by Reezaali** [MicrosoftEdge/WebViewFeedback#281]
A customer opened an issue regarding documentation here: 
https://github.com/MicrosoftDocs/edge-developer/issues/737
Please review the issue and update the documentation as necessary. Thanks.

[AB#27044578](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27044578)

**Comment by pagoe-msft** [comment]
Thanks for posting this, adding a Getting Started topic with WebView2 in WinUI 3 is on our radar!

**Comment by jasonstephen15** [comment]
Our team recently released a guide located here: https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winui
