### ISSUE TITLE
[DMC] How to use WebView2 with UWP docs needed #713

### ISSUE THREAD

**Issue by Reezaali** [MicrosoftEdge/WebViewFeedback#282]
A customer opened an issue regarding documentation here:
https://github.com/MicrosoftDocs/edge-developer/issues/713
Please review the issue and update the documentation as necessary. Thanks.

[AB#27044875](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27044875)

**Comment by champnic** [comment]
https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winui
