### ISSUE TITLE
When adding Microsoft.Extensions.Hosting WebView2 reports Microsoft.Web could not be found.

### ISSUE THREAD

**Issue by ChrisPulman** [MicrosoftEdge/WebViewFeedback#285]
Using a WPF application, net48 / netcoreapp3.1
When adding Microsoft.Extensions.Hosting WebView2 reports Microsoft.Web could not be found.

**Comment by pagoe-msft** [comment]
@ChrisPulman 

The .NET DLLs are currently in the pre-release package while we are in Preview. Could you try using the pre-release version? I will update our documentation to make this more clear.

**Comment by ChrisPulman** [comment]
So I need to use the pre release build of Microsoft.Extensions.Hosting for both to work together? Currently 3.1.6 pre release

**Comment by pagoe-msft** [comment]
Are you using the WebView2 NuGet package?

**Comment by arepp23** [comment]
I am having the same issue when I follow the steps here: https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf and add Microsoft.Web.WebView2 as a NuGet package.

**Comment by ChrisPulman** [comment]
Yes the latest Preview version

**Comment by champnic** [comment]
@ChrisPulman You need the pre-release build of the WebView2 Nuget package - so[ 0.9.538-prerelease](https://www.nuget.org/packages/Microsoft.Web.WebView2/0.9.538-prerelease) or [0.9.515-prerelease](https://www.nuget.org/packages/Microsoft.Web.WebView2/0.9.515-prerelease).

**Comment by ChrisPulman** [comment]
I was definitely using the right packages.
I believe got to the bottom of this issue, adding any package with Microsoft in the namespace causes the package to stop functioning.
I had a package with the namespace MyCompany.Microsoft.Extensions.Hosting.Reactive included in my project as well as Microsoft.Extensions.Hosting, it seems that any assembly with a namespace containing Microsoft causes it to fail *.Microsoft.*
Removing the Microsoft section of the namespace from the included Reactive extensions package solved the issue.
it became MyCompany.Ms.Extensions.Hosting.Reactive
Are you using MEF to load additional assemblies?

**Comment by champnic** [comment]
We aren't, but we only own the WebView2 package. If you think there's a collision or something similar happening with your package and the Microsoft.Extensions.Hosting package, I think you can open an issue in this repo:
https://github.com/dotnet/core/tree/master/release-notes (found by following the release notes link here: https://www.nuget.org/packages/Microsoft.Extensions.Hosting/5.0.0-preview.7.20364.11)

If you think this is still related to the WebView2 package, please reopen and we'll take a look. Thanks!
