### ISSUE TITLE
Windows Server 2012R2 support?

### ISSUE THREAD

**Issue by MojoDK** [MicrosoftEdge/WebViewFeedback#287]
Will it eventually support Windows Server 2012R2? I have tons of clients logging into 2012R2 via remote desktop and our app need to use a new web control since current Web control is IE11 and outdated.

**Comment by liminzhu** [comment]
Thanks for opening the issue. It's supported today. See https://docs.microsoft.com/en-us/microsoft-edge/webview2/#supported-platforms. 

I consider this issue closed, but feel free to reopen if there is more question.
