### ISSUE TITLE
Sandbox support?

### ISSUE THREAD

**Issue by davidchisnall** [MicrosoftEdge/WebViewFeedback#29]
I wasn't able to find any reference in the documentation to how sandboxing is exposed to consumers of the web view.  Currently Windows is the only mainstream platform whose default native web view control does not support sandboxing out of the box (Android, macOS, and iOS all do), so any vulnerability in the web view can compromise the integrity of the host program.  Are there plans to address this with WebView2?  How are the APIs for handling cross-process interactions going to be surfaced?  How much control over the sandboxing policy are you going to expose to WebView2 consumers?

**Comment by david-risney** [comment]
Great question. Our docs should talk about this but don't currently. I'll open an issue to fix that. In short our process model and security model including sandboxing exactly match the Edge browser.

**Comment by champnic** [comment]
Here are some docs:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/security
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/process-model

If you are looking for something more specific please reopen this issue with what's missing. Thanks!
