### ISSUE TITLE
Microsoft.Web.WebView2 nuget package does not contain Microsoft.Web.WebView2.Wpf assembly

### ISSUE THREAD

**Issue by jozefizso** [MicrosoftEdge/WebViewFeedback#294]
I'm trying the WebView2 tutorials for WPF and WinForms from Microsoft Docs. When I added the **Microsoft.Web.WebView2** nuget package to C# WPF application project, it does not reference **Microsoft.Web.WebView2.Wpf** assembly. This assembly is not included the the nuget package release 0.9.538.

```xml
<packages>
  <package id="Microsoft.Web.WebView2" version="0.9.538" targetFramework="net472" />
</packages>
```

```
1>------ Build started: Project: WpfApp1, Configuration: Debug Any CPU ------
1>C:\Users\jozef\source\repos\WpfApp1\WpfApp1\MainWindow.xaml(11,10): error MC3074: The tag 'WebView2' does not exist in XML namespace 'clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf'. Line 11 Position 10.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

Tutorial: https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf

PS: The same happens for WinForms project in which I cannot use WebView2 control.

**Comment by mikemeinz** [comment]
You have to install the 0.9.538-prerelease NuGet package the 0.9.538 package is not complete.

**Comment by champnic** [comment]
Thanks @mikemeinz! @jozefizso I'm going to close this issue - if using the pre-release package doesn't fix your issue please reopen. Thanks!
