### ISSUE TITLE
IME is not display inline

### ISSUE THREAD

**Issue by sayurin** [MicrosoftEdge/WebViewFeedback#30]
IME is display as out of window. But it should be inline.

**Comment by liminzhu** [comment]
Thanks for reporting the issue! It's indeed off. Just to make sure, is this the behavior you're referring to?

![Capture](https://user-images.githubusercontent.com/1158954/60628872-49d0d480-9da8-11e9-8a06-1333d7b403fb.PNG)

**Comment by sayurin** [comment]
@liminzhu , Yes, that's right.

**Comment by liminzhu** [comment]
Thanks, we'll indeed look into it.

**Comment by pagoe-msft** [comment]
Happy to report that we just shipped IME support in 0.8.55. Closing the issue for now and feel free to re-open the issue and let us know if you have additional feedback.
