### ISSUE TITLE
Can't load latest updated WebView2 in WPF

### ISSUE THREAD

**Issue by RickStrahl** [MicrosoftEdge/WebViewFeedback#301]
I have an existing sample Window page I created with an earlier preview. I updated to the latest package, but now I don't seem to be able to load the WebView anymore - the compiler complains that the namespace can't be resolved.

![image](https://user-images.githubusercontent.com/1374013/85476071-1d7f0c80-b553-11ea-95a5-3a44a63e0de9.png)

Docs haven't changed and I can't actually find any binaries when I compile (presumably because no binary output folder is generated yet?).

It seems that this is no longer working with `0.9.538`?

This comes straight out of the [WPF docs](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf):

```xml
xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
```

**Comment by champnic** [comment]
Hey @RickStrahl, WPF is only supported in the prerelease packages for now. Can you try using 0.9.538-prerelease and see if that resolves your issue?

**Comment by RickStrahl** [comment]
Duh... yup that's it. Not real clear that we need to use the pre-release one, just assumed we could use either. Thanks it works now...
