### ISSUE TITLE
webview2 v0.9.538

### ISSUE THREAD

**Issue by cgeier** [MicrosoftEdge/WebViewFeedback#303]
![Microsoft Web WebView2 0 9 515-prerelease](https://user-images.githubusercontent.com/34412039/85622675-36f88500-b635-11ea-885d-b65e3f174a6a.JPG)
![Microsoft Web WebView2 0 9 515-prerelease_lib](https://user-images.githubusercontent.com/34412039/85622678-37911b80-b635-11ea-921f-a01245a76047.JPG)
![Microsoft Web WebView2 0 9 515-prerelease_lib_net462](https://user-images.githubusercontent.com/34412039/85622680-37911b80-b635-11ea-9955-aae60f48f04f.JPG)
![Microsoft Web WebView2 0 9 538](https://user-images.githubusercontent.com/34412039/85622682-37911b80-b635-11ea-874e-131023401ad4.JPG)

In the NuGet package for WebView2 v0.9.538, the "lib" folder (as well as it's contents) appears to be missing when installed using  Manage NuGet Packages (VS 2017), and therefore doesn't work. Both v0.9.515-prerelease and v0.9.538-prerelease have the lib folder and work.

**Comment by mikemeinz** [comment]
You must use the NuGet package version 0.9.538-prerelease. The version 0.9.538 package is incomplete.
