### ISSUE TITLE
Can't get result from CallDevToolsProtocolMethodAsync

### ISSUE THREAD

**Issue by ukandrewc** [MicrosoftEdge/WebViewFeedback#304]
Trying to call devtools protocol but not getting any results, I have Dev channel installed

```
Public Async Sub Test()
	Dim r = Await CoreWeb.CallDevToolsProtocolMethodAsync("DOM.getOuterHTML", "{}")
	Console.WriteLine(r)
End Sub
```

[AB#27258673](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27258673)

**Comment by ukandrewc** [comment]
Not the same for all calls, "Network.getCookies", does work.

**Comment by ukandrewc** [comment]
It seems that ParametersAsJson may be the problem, I don't seem to be able to get a response when they are required.

This works:
`CoreWeb.CallDevToolsProtocolMethodAsync("Network.getCookies", "{}")`

Returns an empty array:
`CoreWeb.CallDevToolsProtocolMethodAsync("Network.getCookies", "{""urls"":[""google.co.uk"",""www.google.com""]}")`

**Comment by michael-russin** [comment]
For the cookies try adding the protocol.  That works for me.  For the **DOM.getOuterHTML** I haven't had any luck yet.

```C#
CoreWeb.CallDevToolsProtocolMethodAsync("Network.getCookies", "{""urls"":[""https://google.co.uk"",""https://www.google.com""]}")
```

**Comment by ukandrewc** [comment]
@michael-russin Cheers, didn't think of that. I was going on .Net where only domain is required.

**Comment by ukandrewc** [comment]
PS: I did try adding nodeId for getOuterHTML but nothing from that either.

**Comment by pagoe-msft** [comment]
@ukandrewc 

Thanks for bringing this up - we have been investigating this and trying to determine if this is a bug on our side or a bug in CDP

**Comment by pagoe-msft** [comment]
@ukandrewc 

This appears to be a bug on CDP side. I'll file a bug for them to look into and I've added a feature request on our end to provide better error messaging.

**Comment by ukandrewc** [comment]
@pagoe-msft Great, thanks. While we're on better error messaging, is there any way to log executeScriptAsync errors in devtools?

**Comment by pagoe-msft** [comment]
@ukandrewc 

We don't have support for that right now - but that's a really interesting feature request. Could you open a new issue for that, so we can track it separately in our backlog?

**Comment by ukandrewc** [comment]
@pagoe-msft  will do

**Comment by michael-russin** [comment]
You can get the getOuterHTML working by making 2 calls 

```C#
// Get the document information
CoreWebView2.CallDevToolsProtocolMethodAsync("DOM.getDocument", "{}");

// parse the result JSON and read the nodeId

// get the outer html for the nodeId
CoreWebView2.CallDevToolsProtocolMethodAsync("DOM.getOuterHTML", "{\"nodeId\" : " +  nodeId + "}");
```
This will give the source you would see by doing an Inspect not what you would see with a View Source.  

A basic sample can be found in the WebView2WindowsFormsBrowser project at https://github.com/michael-russin/WebView2Samples

**Comment by ukandrewc** [comment]
@michael-russin Thanks, that is what I wanted to find out. Is it just `document.documentElement.outerHTML`.
At the moment, I'm just making an XHR call to get the source, but was wondering if it is available locally.

**Comment by champnic** [comment]
@ukandrewc Apparently even though the docs for [getOuterHTML](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-getOuterHTML) list all parameters as optional, at least one needs to be specified.

**Comment by ukandrewc** [comment]
Great, thanks.

**Comment by WirelessMistress** [comment]
If you specify {"nodeId":1}
to the 
DOM.getOuterHTML 
command,
my impression is it gives you the entire HTML View Source Content

**Comment by WirelessMistress** [comment]
Sorry my bad
lemme correct my previous post

// Get the document information
var documentString = CoreWebView2.CallDevToolsProtocolMethodAsync("DOM.getDocument", @"{""depth"":-1,""pierce"":false}");

//var id =  parse using a System.Text.RegularExpressions.Regex 
// for @"(""backendNodeId"":)([0-9]+) on documentString 

// get the outer html for the nodeId
CoreWebView2.CallDevToolsProtocolMethodAsync("DOM.getOuterHTML", "{\"backendNodeId\" : " +  id + "}");

and you get all the view Source of the HTML document html-decoded
