### ISSUE TITLE
Extensions Sample

### ISSUE THREAD

**Issue by PassivePicasso** [MicrosoftEdge/WebViewFeedback#306]
If the new Edge component has support for Chromium extensions, some samples on it's usage would be wonderful.
If it does not, such support would be superb.

[AB#27173057](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27173057)

**Comment by champnic** [comment]
@PassivePicasso just moved it over. Turns out transferring the issue was easier than I thought it would be. Thanks!

**Comment by champnic** [comment]
This is tracked as part of #191 so closing this issue.
