### ISSUE TITLE
Enable clipboard paste access for webview2 in C

### ISSUE THREAD

**Issue by abeMedia** [MicrosoftEdge/WebViewFeedback#310]
I'm trying to enable JavaScript access to the clipboard from C but the docs aren't very clear to me.
I tried the following but get the error `error C2275: 'ICoreWebView2PermissionRequestedEventHandler': illegal use of this type as an expression`

```c
m_webview->add_PermissionRequested(
    Callback<ICoreWebView2PermissionRequestedEventHandler>(
        [this](
            ICoreWebView2* sender,
            ICoreWebView2PermissionRequestedEventArgs* args) -> HRESULT
{
    COREWEBVIEW2_PERMISSION_KIND kind;
    args->get_PermissionKind(&kind);
    if (kind == COREWEBVIEW2_PERMISSION_KIND_CLIPBOARD_READ) {
      args->put_State(COREWEBVIEW2_PERMISSION_STATE_ALLOW);
    }
    return S_OK;
}), nullptr);
```

**Comment by michael-russin** [comment]
add_PermissionRequested needs a pointer as the first parameter.   Try adding **Get()** for the Callback.

The **WebView2APISample** at https://github.com/MicrosoftEdge/WebView2Samples is a good reference.


```C
m_webview->add_PermissionRequested(
    Callback<ICoreWebView2PermissionRequestedEventHandler>(
        [this](
            ICoreWebView2* sender,
            ICoreWebView2PermissionRequestedEventArgs* args) -> HRESULT
{
    COREWEBVIEW2_PERMISSION_KIND kind;
    args->get_PermissionKind(&kind);
    if (kind == COREWEBVIEW2_PERMISSION_KIND_CLIPBOARD_READ) {
      args->put_State(COREWEBVIEW2_PERMISSION_STATE_ALLOW);
    }
    return S_OK;
}).Get(), nullptr);
```

**Comment by abeMedia** [comment]
I originally had that but then I got even more errors. Now I get the following:
```
C:\Users\adam\Desktop\webview\webview.h(875): error C2275: 'ICoreWebView2PermissionRequestedEventHandler': illegal use of this type as an expression
C:\Users\adam\Desktop\webview\script\..\script\microsoft.web.webview2.0.9.488\build\native\include\webview2.h(4802): note: see declaration of 'ICoreWebView2PermissionRequestedEventHandler'
C:\Users\adam\Desktop\webview\webview.h(886): error C2039: 'Get': is not a member of 'webview::edge_chromium::embed::<lambda_0c07c55c4d286edd819dcf1319730a8c>::()::<lambda_7eda210adf3cd3485771d98ce141fa56>'
C:\Users\adam\Desktop\webview\webview.h(886): note: see declaration of 'webview::edge_chromium::embed::<lambda_0c07c55c4d286edd819dcf1319730a8c>::()::<lambda_7eda210adf3cd3485771d98ce141fa56>'
```

**Comment by ysc3839** [comment]
The `Callback` is in `Microsoft::WRL` namespace. You have to use `Microsoft::WRL::Callback` or `using namespace Microsoft::WRL;`.

**Comment by abeMedia** [comment]
I tried adding the namespace and now I'm getting the following errors:

```
C:\Users\adam\Desktop\webview\webview.h(784): error C2653: 'Microsoft': is not a class or namespace name
C:\Users\adam\Desktop\webview\webview.h(784): error C2871: 'WRL': a namespace with this name does not exist
```

**Comment by abeMedia** [comment]
I'm using C by the way, not C++.

**Comment by michael-russin** [comment]
Looking at the project you are trying to work on I would suggest you just follow the pattern they have and change the _webview2_com_handler_ class to also implement the _ICoreWebView2PermissionRequestedEventHandler_ interface and not use WRL at all.

**Comment by abeMedia** [comment]
First off thanks for your help! I tried what you suggested, however I still get the permission request asking whether to allow access to the clipboard when trying to use `navigator.clipboard`. Also, `document.execCommand('paste')` is not supported.
Here's the updated `webview2_com_handler` class: https://github.com/abeMedia/webview/blob/edge-paste-permission/webview.h#L927-L981
Am I missing something?

Thanks again!

**Comment by michael-russin** [comment]
Looks like you are missing a call to [add_PermissionRequested](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-538/icorewebview2#add_permissionrequested) so the web view will call you handler.   Maybe around the same place you call _add_WebMessageReceived_

**Comment by abeMedia** [comment]
Ah yes of course. Thank you very much! Got it working now.
However `document.execCommand('paste')` still doesn't work... Do you know if it's supported in Edge Webview?
