### ISSUE TITLE
Minimize memory usage and/or opt-out browser features

### ISSUE THREAD

**Issue by jarrettv** [MicrosoftEdge/WebViewFeedback#315]
We build applications for resource constrained environments (citrix) and need to be very strict on memory usage. Is there a possibility of leaving out features to reduce memory usage? For example: no video, no audio, no bluetooth, no 3D, no canvas, etc?

Our target needs are the html, svg, and css layout features for rendering a javascript (vuejs) front-end.

[AB#27300973](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27300973)

**Comment by pagoe-msft** [comment]
@jarrettv 

Thanks so much for the feedback. I've added a feature request to create a mechanism to opt our of browser features.

**Comment by Birol2010** [comment]
You can use this code for now.
It reduces memory usage %30-%50.

        [DllImport("kernel32.dll")]
        [return: MarshalAs(UnmanagedType.Bool)]
        internal static extern bool SetProcessWorkingSetSize(
            IntPtr process,
            UIntPtr minimumWorkingSetSize,
            UIntPtr maximumWorkingSetSize);

        private void btnClearMemory_Click(object sender, EventArgs e)
        {
            string procName = "msedgewebview2";
            //Process[] processes = Process.GetProcessesByName(procName);
            Process[] processes = Process.GetProcesses();
            IntPtr handle = IntPtr.Zero;
            foreach (Process process in processes)
            {
                if (process.ProcessName.ToLower() == procName)
                {
                    try
                    {
                        handle = process.Handle;
                        SetProcessWorkingSetSize(handle, (UIntPtr)0xFFFFFFFF, (UIntPtr)0xFFFFFFFF);
                        //break;
                    }
                    catch (Win32Exception ex)
                    {
                        string mesaj = ex.Message;
                    }
                }
            }

        }

**Comment by liminzhu** [comment]
There isn't a low memory mode in WebView2 per-se, but you can turn off features by passing browser args (some of them documented [here](https://peter.sh/experiments/chromium-command-line-switches/)) when instantiating WebView environment.
