### ISSUE TITLE
Unable to use WebView2 on WPF Core

### ISSUE THREAD

**Issue by RaoHammas** [MicrosoftEdge/WebViewFeedback#319]
I've multiple times tried this and finally asking here. 

I have this `WPF .Net core 3.1` App. And according to instructions given here [https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf](url) , i install the `Microsoft.Web.WebView2` package version `0.9.538` but i am unable to use it in my program. Always get this.

![image](https://user-images.githubusercontent.com/16499626/86529978-53ff4480-bece-11ea-82a5-e458c897bb75.png)

Although the package is installed. I've tried on `Core 3.0` also still same issue. Can someone help me why ?

**Comment by mikemeinz** [comment]
You must use the **0.9.538-prerelease** NuGet package. 
Do not use the **0.9.538** NuGet package. The **0.9.538** NuGet package does not include .NET components.
See [Release Notes](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes)

**Comment by RaoHammas** [comment]
> You must use the **0.9.538-prerelease** NuGet package.
> Do not use the **0.9.538** NuGet package. The **0.9.538** NuGet package does not include .NET components.
> See [Release Notes](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes)

Oh yes ! Thank you sir for quick response. That was the reason, Solved now :)

**Comment by RaoHammas** [comment]
@mikemeinz  just a quick question sir. Can i use it with UWP ? cuz the package does get added to UWP project but same namespace problem shows there ? although i used pre-release pckg ??

**Comment by mikemeinz** [comment]
The documentation, at this point, does not say that you can use UWP.
See [WebView2 API Reference](https://docs.microsoft.com/en-us/microsoft-edge/webview2/webview2-api-reference)
See [Issue #713 ](https://github.com/MicrosoftDocs/edge-developer/issues/713)
See [Issue #282](https://github.com/MicrosoftEdge/WebViewFeedback/issues/282)
