### ISSUE TITLE
WebView2 changes the complete application's resolution at runtime

### ISSUE THREAD

**Issue by ajmalanwari** [MicrosoftEdge/WebViewFeedback#326]
Adding a WebView2 control changes the resolution of the MDI form and other opened forms resolution at runtime.

- I am using .Net Framework 4.7.2
- Installed MS WebView2 version 0.9.538 prerelease package
- Edge is the latest developer channel

I tried to find a way to stop this thing happening but couldn't, please let me know if any other information is required from my side.

[AB#27529862](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27529862)

**Comment by pagoe-msft** [comment]
@ajmalanwari 

Thanks for the feedback, I've filed a bug!

**Comment by champnic** [comment]
@ajmalanwari Could you add more detail about this issue? Are you talking about the DPI/scaling of the forms, or the layout/sizing? We are adding DPI support soon to our .Net controls, but I want to confirm that is the same issue your hitting here.

**Comment by oggy22** [comment]
Hi @ajmalanwari! You can probably solve the issue by setting DpiAwareness to be PerMonitorV2 in app.config the following way:

```
  <System.Windows.Forms.ApplicationConfigurationSection>
    <add key="DpiAwareness" value="PerMonitorV2"/>
  </System.Windows.Forms.ApplicationConfigurationSection>
```

Also you need to be at .NET framework >4.7.0, it doesn't work for 4.6.2, but you said you are using 4.7.2 so it should be fine. For more info check:
https://docs.microsoft.com/en-us/dotnet/framework/winforms/high-dpi-support-in-windows-forms

I am closing this issue, but feel free to reopen it if this fix doesn't work for you.
