### ISSUE TITLE
NuGet 2.0.9.538 doesn't contain the assembly

### ISSUE THREAD

**Issue by bgavrilMS** [MicrosoftEdge/WebViewFeedback#327]
See https://github.com/MicrosoftEdge/WebView2Browser/issues/18 for details

**Comment by pagoe-msft** [comment]
@bgavrilMS,

This has been addressed here: https://github.com/MicrosoftEdge/WebViewFeedback/issues/262

This is a fault on our end. There isn't a difference between 0.9.538 and 0.9.515 for the missing assemblies. We will correct this in our next SDK release

**Comment by bgavrilMS** [comment]
Not fixed, I left more details on #262
