### ISSUE TITLE
DOMException: Failed to construct 'Worker': '...' is not a valid URL.

### ISSUE THREAD

**Issue by ndreisg** [MicrosoftEdge/WebViewFeedback#332]
In my project I'm using [Forge](https://github.com/digitalbazaar/forge/) encryption library to generate an RSA keypair in javascript.

To generate the keypair Forge uses Web Workers if they are available.

    forge.rsa.generateKeyPair({ bits: 2048, workers: 1 }, function (err, keypair) {
      //do something with your keypair
    });

Apparently the window.Worker object is available but workers can't be constructed correctly. I get the following Exception:

    Uncaught (in promise) DOMException: Failed to construct 'Worker': 'forge/prime.worker.js' is not a valid URL.

It's working in the Edge HTML WebView.

I will provide a minimum sample soon. Please stay tuned.

**Comment by pagoe-msft** [comment]
@ndreisg,

Thanks for letting us know! Staying tuned for a sample and will follow up then.

**Comment by ndreisg** [comment]
I tried to make a sample but found out that Workers with a correct URL are working without any problem.
I created a new issue in the Forge repo. [digitalbazaar/forge/issues/796](https://github.com/digitalbazaar/forge/issues/796)
