### ISSUE TITLE
COMException when removing event handler from CoreWebView2

### ISSUE THREAD

**Issue by fvanheeswijk** [MicrosoftEdge/WebViewFeedback#338]
We are facing an issue in our application when we remove event handlers from the CoreWebView2, we need to explicitly remove them in our actual application because we need to update certain bookkeeping.

Upon removal of the event handler we get a COMException however:

> System.Runtime.InteropServices.COMException (0x8007139F): The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2.remove_NewWindowRequested(EventRegistrationToken token)
   at Microsoft.Web.WebView2.Core.CoreWebView2.remove_NewWindowRequested(EventHandler`1 value) Error code App:90001

We have managed to create the following reproducible example:

```
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;

using Microsoft.Web.WebView2.Core;
using Microsoft.Web.WebView2.WinForms;

namespace WebView2EventHandler
{
    static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(CreateNewForm());
        }

        private static Form CreateNewForm()
        {
            var form = new Form
            {
                Size = new Size(800, 600)
            };

            var button = new Button
            {
                Dock = DockStyle.Fill,
                Text = "Open form"
            };
            button.Click += (sender, e) =>
            {
                EventHandler<CoreWebView2NewWindowRequestedEventArgs> newWindowRequestedEvent = (sender2, e2) =>
                {
                    e2.Handled = false;
                };

                var webView2 = new WebView2
                {
                    Dock = DockStyle.Fill,
                    Source = new Uri(@"about:blank")
                };
                CoreWebView2 coreWebView2 = null;
                webView2.CoreWebView2Ready += (sender2, e2) =>
                {
                    coreWebView2 = webView2.CoreWebView2;
                    coreWebView2.NewWindowRequested += newWindowRequestedEvent;
                    coreWebView2.Navigate(@"https://www.google.com");

                };

                var modalForm = new Form
                {
                    Size = new Size(1280, 1024)
                };
                modalForm.Controls.Add(webView2);

                modalForm.ShowDialog(form);

                modalForm.Dispose();
                coreWebView2.NewWindowRequested -= newWindowRequestedEvent;
            };

            form.Controls.Add(button);

            return form;
        }
    }
}
```

We expect to be able to remove the event handlers explicitly. A difference we have encountered of your WebView2 versus other components is that other components actually have two parts: The WinForms control and the webview itself, in those components we have never encountered similar issues so maybe a split could be helpful.

[AB#27803586](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27803586)

**Comment by michael-russin** [comment]
Did you try disconnecting the event handler before you call Dispose() ?   Dispose is probably destroying the internal webview2

**Comment by fvanheeswijk** [comment]
In our application we always first dispose the Form, then dispose the event handlers and in the end do any additional cleanup of our custom controls on the form (things like background handlers, etc.).
This would be non-straightforward to change.

My main point for my mentioned expected behavior is that we have never encountered a similar issue before so we expected it to work.

**Comment by pagoe-msft** [comment]
Thanks for bringing this to our attention! I've filed a bug and we will investigate.

**Comment by oggy22** [comment]
Hi @fvanheeswijk! First of all thank you for submitting the issue. I did some investigation and basically your code is accessing `coreWebView2` when not in correct state, as the error message suggests. The "correct" state is having the form and control running, and therefore having the HWND. Since your call is after the form is closed, that is not correct state. We should probably update our docs to be more explicit about this requirement.

From the bright side I do have a verified solution for you and that is doing the un-subscription from the event handler, either `FormClosed` or `FormClosing`. They both seem to work fine. So right before the `ShowDialog` you should call:
`modalForm.FormClosing += (s, o) => { coreWebView2.NewWindowRequested -= newWindowRequestedEvent; };`

I am closing this issue as Won't fix. Please let me know if that's ok with you?

**Comment by fvanheeswijk** [comment]
Thank you for your response.

I still would say that the original situation shouldn't cause a COMException. Even though the native component under the coreWebView2 would be gone, the .NET based event handlers could still be removed. We haven't seen any other component that works in a similar way and we expect other users to potentially run into similar issues when they try to remove their event handlers explicitly.

The good news however is that removing the event handlers in the FormClosed event (because the FormClosing event can still potentially be canceled) works.

**Comment by oggy22** [comment]
Sorry for such late response. Yes, I agree this still needs to be addressed. So we do have an internal item to actually improve issuing COM exceptions to .NET devs. The idea is basically to wrap COM exceptions into more meaningful .NET exceptions with possible suggestions e.g. "not the right thread".

Thank you for your feedback!

**Comment by fvanheeswijk** [comment]
I still wonder if the dispose can be ignored on the WebView2 side when the control is gone already anyway, as in there is nothing to dispose anymore. It would greatly simplify things for us.
