### ISSUE TITLE
Version 0.9.538 NuGet package missed lib folder with required assemblies

### ISSUE THREAD

**Issue by alexandrevk** [MicrosoftEdge/WebViewFeedback#339]
After installing version 0.9.538 for WPF project, error during building:     name WebView2 does not exist in namespace Microsoft.Web.WebView2.Wpf

**Comment by mikemeinz** [comment]
You must use the NuGet 0.9.538-prelease package. The Nuget 0.9.538 package does not include .NET.

**Comment by pagoe-msft** [comment]
@mikemeinz is correct! .NET exists in the pre-release package.
