### ISSUE TITLE
Microsoft Edge can't read and write to its data directory

### ISSUE THREAD

**Issue by ndreisg** [MicrosoftEdge/WebViewFeedback#340]
When I try to run my Windows Forms application with WebView2 from program files dir I get the following error:

    ---------------------------
    We couldn't create the data directory
    ---------------------------
    Microsoft Edge can't read and write to its data directory:
        C:\Program Files (x86)\MyWebViewApplication\MyWebViewApplication.exe.WebView2\EBWebView

The application is not elevated so I guess it doesn't have access in program files.
How do I change the `data directory` to another location?

**Comment by cgeier** [comment]
See [#324 ](https://github.com/MicrosoftEdge/WebViewFeedback/issues/324) and [#297](https://github.com/MicrosoftEdge/WebViewFeedback/issues/297)

**Comment by ndreisg** [comment]
I now tried to change the userDataFolder like suggested here https://github.com/MicrosoftEdge/WebViewFeedback/issues/324#issuecomment-654980822 but it had no effect at all :/

    var env = await CoreWebView2Environment.CreateAsync(null, @"C:\Temp", null);
    await webView.EnsureCoreWebView2Async(env);

**Comment by ndreisg** [comment]
I created my WebView in Forms Designer. The `Source` property of the WebView is set to `about:blank` by default.
Apparently clearing the property value is not supported since I get an error when I try to.
But the documentation of `EnsureCoreWebView2Async` function states the following: 

> Calling this method after initialization has been implicitly triggered by setting the Microsoft.Web.WebView2.WinForms.WebView2.Source property will have no effect (any specified environment is ignored) and simply return a Task representing that initialization already in progress.

Can you suggest any best practice how to change it when the WebView was created in Forms Designer?

**Comment by cgeier** [comment]
There is an example [here](https://github.com/michael-russin/WebView2Samples/blob/master/WebView2WindowsFormsBrowser/BrowserForm.cs).

I think the different versions (canary/dev) of MS Edge that you've installed can be found in 
%ProgramFiles(x86)%\Microsoft\Edge\Application\<version folder>

The path to the  "Edge\Application" folder can be found in the registry:
HKLM\Software\Microsoft\Windows\CurrentVersion\App Path\msedge.exe . Look at "Path"

![MSEdgePathInRegistry](https://user-images.githubusercontent.com/34412039/87701779-7a42a100-c766-11ea-9600-a1a1d00447c8.JPG)

![MSEdgeApplicationFolder](https://user-images.githubusercontent.com/34412039/87701801-7f075500-c766-11ea-9d97-2e07be4a2671.JPG)

![MSEdgeOtherVersions](https://user-images.githubusercontent.com/34412039/87701808-83337280-c766-11ea-9d08-ecb418bffa0d.JPG)

**Comment by cgeier** [comment]
I guess I must have missed that. It seems to me that one should be able to set the "Source" property to null (or an empty string), since setting CoreWebView2Environment doesn't work after the "Source" property is set (as you stated). I tested the following workaround. If you go into the form designer (ex: Form1.Designer.cs), and comment out the line that sets the "Source" property. 

```
            // 
            // webView2Ctl
            // 
            this.webView2Ctl.Dock = System.Windows.Forms.DockStyle.Fill;
            this.webView2Ctl.Location = new System.Drawing.Point(0, 0);
            this.webView2Ctl.Name = "webView2Ctl";
            this.webView2Ctl.Size = new System.Drawing.Size(705, 360);
            //this.webView2Ctl.Source = new System.Uri("about:blank", System.UriKind.Absolute);
            this.webView2Ctl.TabIndex = 0;
            this.webView2Ctl.Text = "webView";
            this.webView2Ctl.ZoomFactor = 1D;
```


Then set the "Source" property after "EnsureCoreWebView2Async", it will work.

```
        ...
await webView2Ctl.EnsureCoreWebView2Async(webView2Environment);
webView2Ctl.Source = new Uri("about:blank", UriKind.Absolute);
        ...
```

Here's the code from above with the modification.

```
private void Form1_Load(object sender, EventArgs e)
{
    InitializeWebView2Async();
    //InitializeWebView2Async(@"C:\temp");
}


private async void InitializeWebView2Async(string tempDir = "")
{
    CoreWebView2Environment webView2Environment = null;

    //set value
    string tempDir2 = tempDir;

    if (String.IsNullOrEmpty(tempDir2))
    {
        //get fully-qualified path to user's temp folder
        tempDir2 = Path.GetTempPath();
    }//if

    //add event handler for CoreWebView2Ready - before webView2Ctl is initialized
    //it's important to not use webViewCtrl until CoreWebView2Ready event is thrown
    webView2Ctl.CoreWebView2Ready += WebView2Ctl_CoreWebView2Ready;

    CoreWebView2EnvironmentOptions options = null;
    //options = new CoreWebView2EnvironmentOptions("--disk-cache-size=200");
    //options = new CoreWebView2EnvironmentOptions("–incognito ");

    //set webView2 temp folder. The temp folder is used to store webView2
    //cached objects. If not specified, the folder where the executable
    //was started will be used. If the user doesn't have write permissions
    //on that folder, such as C:\Program Files\<your application folder>\,
    //then webView2 will fail. 

    //webView2Environment = await CoreWebView2Environment.CreateAsync(@"C:\Program Files (x86)\Microsoft\Edge Dev\Application\85.0.564.8", tempDir2, options);
    webView2Environment = await CoreWebView2Environment.CreateAsync(null, tempDir2, options);

    //webView2Ctl must be inialized before it can be used
    //wait for coreWebView2 initialization
    //when complete, CoreWebView2Ready event will be thrown
    await webView2Ctl.EnsureCoreWebView2Async(webView2Environment);

    webView2Ctl.Source = new Uri("about:blank", UriKind.Absolute);

    //add other event handlers - after webView2Ctrl is initialized
    //webView2Ctl.CoreWebView2.NavigationCompleted += CoreWebView2_NavigationCompleted;
    //webView2Ctl.CoreWebView2.WebMessageReceived += CoreWebView2_WebMessageReceived;
    //webView2Ctl.NavigationCompleted += WebView2Ctl_NavigationCompleted;
    //webView2Ctl.NavigationStarting += WebView2Ctl_NavigationStarting;

}

private void WebView2Ctl_CoreWebView2Ready(object sender, EventArgs e)
{
     System.Diagnostics.Debug.Print("Info: WebView2Ctl_CoreWebView2Ready"); 

}
```

When setting CoreWebView2Environment works, it creates a folder named "EBWebView" at the path that has been specified (ex: C:\Temp\EBWebView). 

![EBWebViewFolder](https://user-images.githubusercontent.com/34412039/87751843-f374df00-c7cc-11ea-93eb-64b63a2da41f.JPG)


![EBWebViewFolderContents](https://user-images.githubusercontent.com/34412039/87751844-f40d7580-c7cc-11ea-9d97-7ef48499741c.JPG)

**Comment by ndreisg** [comment]
Thanks @cgeier that seems to work.
Yes it seems it should be possible to clear the source property or maybe to have an additional property for the data directory.

**Comment by pagoe-msft** [comment]
Closing this issue - let me know if it should be re-opened.

**Comment by cgeier** [comment]
@pagoe-msft Setting "CoreWebView2Environment" when the WebView2 control was created with the Visual Studio Forms designer, doesn't appear to work. As described above, one needs to comment out (remove) the definition of the "Source" property because setting the "Source" property initializes the WebView2 control. Creating a new instance of WebView2 doesn't seem to have any effect. It seems, from my testing, that once the initialization has occurred, that initialization exists for all other WebView2 instances and can't be changed.

**Comment by cgeier** [comment]
@ndreisg It appears the code I posted above is flawed. InitializeWebView2Async should be "Task" not "void" and it should be called using "await". Without using "await" in the "Load" event handler, the code won't execute in the expected order.

Instead of:
```
private void Form1_Load(object sender, EventArgs e)
{
    ...
}
```

it should be:
```
private async void Form1_Load(object sender, EventArgs e)
{
    ...
}
```

Instead of:
```
private async void InitializeWebView2Async(string tempDir = "")
{
    ...
}
```

It should be:
```
private async Task InitializeWebView2Async(string tempDir = "")
{
    ...
}
```

Here's a corrected example:

```
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Microsoft.Web.WebView2.Core;
using Microsoft.Web.WebView2.WinForms;
using System.Diagnostics;

namespace TestWebView2
{
    public partial class Form1 : Form
    {
        //create new instance of WebView2
        Microsoft.Web.WebView2.WinForms.WebView2 webView21 = new Microsoft.Web.WebView2.WinForms.WebView2();
        public Form1()
        {
            InitializeComponent();

            //set WebView2 properties and add to form
            webView21.Location = new System.Drawing.Point(10, 10);
            webView21.Size = new System.Drawing.Size(800, 600);

            //don't set Source property here

            this.Controls.Add(webView21);
        }

        private async void Form1_Load(object sender, EventArgs e)
        {
            // add event handler
            webView21.CoreWebView2Ready += webView21_CoreWebView2Ready;

            Debug.Print("Info: initializing CoreWebView2");

            //initialize CoreWebView2
            await InitializeAsync();

            Debug.Print("Info: after initializing CoreWebView2");

            if (webView21 != null && webView21.CoreWebView2 != null)
            {
                //navigate to website - option 1
                webView21.Source = new Uri("https://www.microsoft.com", UriKind.Absolute);

                //navigate to website - option 2
                //webView21.CoreWebView2.Navigate("https://www.microsoft.com");
            }//if
        }

        private void webView21_CoreWebView2Ready(object sender, EventArgs e)
        {
            Debug.Print("Info: webView21_CoreWebView2Ready");

            //subscribe to events (add event handlers) - CoreWebView2
            webView21.CoreWebView2.NavigationCompleted += CoreWebView2_NavigationCompleted;

            //subscribe to events (add event handlers) - WebView2
            webView21.NavigationStarting += webView21_NavigationStarting;
            webView21.NavigationCompleted += webView21_NavigationCompleted;

            Debug.Print("Info: leaving webView21_CoreWebView2Ready");
        }

        private async Task InitializeAsync()
        {
            Debug.Print("Info: before EnsureCoreWebView2Async");

            // wait for coreWebView2 initialization
            await webView21.EnsureCoreWebView2Async();

            Debug.Print("Info: after EnsureCoreWebView2Async");
        }
        private void webView21_NavigationCompleted(object sender, CoreWebView2NavigationCompletedEventArgs e)
        {
            Debug.Print("Info: webView21_NavigationCompleted");
        }

        private void CoreWebView2_NavigationCompleted(object sender, CoreWebView2NavigationCompletedEventArgs e)
        {
            Debug.Print("Info: CoreWebView2_NavigationCompleted");
        }

        private void webView21_NavigationStarting(object sender, CoreWebView2NavigationStartingEventArgs e)
        {
            Debug.Print("Info: webView21_NavigationStarting - Navigating to '" + e.Uri.ToString() + "'");
        }
    }
}
```

**Comment by wangwei18** [comment]
getting error at Await WebView21.EnsureCoreWebView2Async(webView2Environment)

![image](https://user-images.githubusercontent.com/3354397/120941568-562ade00-c6f1-11eb-8441-dcfcb59ac6fd.png)
