### ISSUE TITLE
0.9.515-prerelease & Microsoft Edge version 84.0.522.0.

### ISSUE THREAD

**Issue by khalidalmannai** [MicrosoftEdge/WebViewFeedback#342]
Hello everybody

I was waiting for Microsoft Edge version 84 to be released to distribute my free applanation as it is using Webview2 0.9.515. According to documentation   0.9.515-prerelease NuGet package | minimum Microsoft Edge version 84.0.515.0.
https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes

Today I updated my Microsoft Edge to version 84.0.522.0. I think it was released yesterday..

Unfortunately Webview2 still not working with this latest Microsoft Edge update and requires Canary or WebView2 runtime package to be installed on the target machine?

Any advice?

Regards,

**Comment by champnic** [comment]
@khalidalmannai WebView2 only works with Canary/Dev/Beta channels of Edge, and the WebView2 Runtime (which is currently the same version as Dev, but will be Stable when we GA). WebView2 does not load or work with the Stable channel of Edge. Please also wait until we GA before distributing your app (unless you are doing a preview version).
