### ISSUE TITLE
Ability to set browser flags

### ISSUE THREAD

**Issue by AbeniMatteo** [MicrosoftEdge/WebViewFeedback#350]
Is there a way to set `edge://flags`?

Ex: `hardware-media-key-handling`

**Comment by liminzhu** [comment]
`edge://flags` are also exposed as browser args you can set through additionalBrowserArguments in [CreateCoreWebView2EnvironmentWithOptions](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-538/webview2-idl#createcorewebview2environmentwithoptions). Do note that these flags do not live forever and can be taken out some day.

**Comment by AbeniMatteo** [comment]
Thanks, the arg is `--disable-features=HardwareMediaKeyHandling`.
