### ISSUE TITLE
webView2 file version

### ISSUE THREAD

**Issue by cgeier** [MicrosoftEdge/WebViewFeedback#352]
Would it be possible to set the file version info to match the release numbers (ex: 0.9.579) for the following files:
 
Microsoft.Web.WebView2.Core.dll
Microsoft.Web.WebView2.WinForms.dll
Microsoft.WebView2.Wpf.dll

I'd like to be able to programmatically check that the proper MS Edge version is installed based on the version of webView2.

![WebView2 Properties](https://user-images.githubusercontent.com/34412039/88329953-b5aa1600-ccf8-11ea-8d75-585e72b6990f.JPG)

[AB#27912804](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27912804)

**Comment by pagoe-msft** [comment]
@cgeier ,

Do [these functions](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/dotnet/0-9-538/microsoft-web-webview2-core-corewebview2environment#browserversionstring) help?

Nevertheless, I've filed this as a feature request, and we'll look into it.

**Comment by oggy22** [comment]
The versioning for .NET assemblies will be shortly in, and be available in our next nuget package.

**Comment by champnic** [comment]
This is fixed and available in our latest prerelease package, 0.9.628-prerelease. Thanks!
