### ISSUE TITLE
WebView not visible in WPF window

### ISSUE THREAD

**Issue by alexandrevk** [MicrosoftEdge/WebViewFeedback#355]
If WPF window AllowsTransparency set to "True" WebView control is not visible:
<Window x:Class="WpfBrowser.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
       WindowStyle="None"        
        AllowsTransparency="True"
        Title="MainWindow" SizeToContent="WidthAndHeight" >
    <Grid>
        <wv2:WebView2 x:Name="PART_ContentBorder" Grid.Row="1" Source="http://localhost:5007/" MinWidth="250" MinHeight="250" />
    </Grid>
</Window>

**Comment by champnic** [comment]
WebView2 doesn't currently support transparency, but this is a feature request on our backlog tracked here: #328 
Thanks!

**Comment by survivalmani** [comment]
Please let us know when it will make be available this feature (Allow transparancy) in webview2 :)

**Comment by champnic** [comment]
It's not near the top of our backlog, so I wouldn't count on it in the next few months at least.
