### ISSUE TITLE
WebView2 not visible in Toolbox

### ISSUE THREAD

**Issue by andromeda54** [MicrosoftEdge/WebViewFeedback#357]
Hello,

I need to upgrade my main application to WebView2 because of .SVG support.

I installed VS2019 Community Version 16.6.5
with
Microsoft Visual Studio Community 2019
Version 16.6.5
Microsoft .NET Framework Version 4.8.03752
GitHub.VisualStudio   2.11.104.25275
Microsoft Visual C++-Assistenten   1.0
NuGet-Paket-Manager   5.6.0

then
Microsoft Edge Version 86.0.587.0 (Offizielles Build) canary (64-Bit)

then
Microsoft.Web.WebView2 0.9.579
to a WinForms TestProject (without anything but 1 button, nothing else)

compiled the Project, opened it, closed it

but WebView2 is not visible in Toolbox to drag it onto the Form...

**Comment by andromeda54** [comment]
OK, needed to install .579-prerelease...
sorry

**Comment by champnic** [comment]
Glad it's working for you now :)
