### ISSUE TITLE
WPF targetting .net core not able to identify webview2 v0.9.579

### ISSUE THREAD

**Issue by sumansaha15** [MicrosoftEdge/WebViewFeedback#358]
Hi team,

First of all, thank you for developing webview2 for enabling us to build cross-platform hybrid apps. It's a great product.

I am using Webview2 with my wpf application targetting .net core 3.1 for developing a thin client app. The pre-release version 0.9.579-prerelease worked fine. But when I upgraded to the latest stable version from nuget, the application broke. It could no longer be able identify Microsoft.Web.WebView2.Core. I have tried with another wpf app targetting standard .net framework and got same issue there as well.

I have both Edge (v83.x) and Edge Canary channel (v86.x) installed in my laptop. Please refer the following screenshots for the seeing the errors I am getting.

Please advise.

 
![image](https://user-images.githubusercontent.com/11616975/88832953-95b69e80-d19f-11ea-8cc0-22df2b25ab52.png)

![image](https://user-images.githubusercontent.com/11616975/88832992-a2d38d80-d19f-11ea-8561-bd50899353ee.png)

![image](https://user-images.githubusercontent.com/11616975/88833014-a830d800-d19f-11ea-99de-6619b83cfa6d.png)

![image](https://user-images.githubusercontent.com/11616975/88833055-b2eb6d00-d19f-11ea-8e73-663750cb528f.png)

Warm Regards,
Suman

**Comment by mikemeinz** [comment]
See [https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes)
It says:
`While WebView2 is a preview, the .NET APIs are in the pre-release package.`

**Comment by champnic** [comment]
Sorry about this versioning issue. Once we hit GA the version numbers between the release and prerelease packages will diverge and it will be much clearer that the prerelease package is the "newer" one, not the release package.

For now, it's easiest to think about prerelease as release package + .NET + experimental APIs.
