### ISSUE TITLE
WebResourceRequested event no longer fires if you register a second callback

### ISSUE THREAD

**Issue by wravery** [MicrosoftEdge/WebViewFeedback#36]
I'm adding Accept-Language headers to all outgoing requests, using code that looks like this:
```c++
webview->add_WebResourceRequested(nullptr, nullptr, 0, Microsoft::WRL::Callback<IWebView2WebResourceRequestedEventHandler>(
		[](IWebView2WebView* webview, IWebView2WebResourceRequestedEventArgs* args)
	{
		...
	}).Get(), &token);
```
It worked before, but now it's no longer calling the lambda function, and the header is not showing up in the Network dev tool. I'm on Canary with the following file versions/timestamps:

* WebView2Loader.dll, 0.08.230.0, 7/25/2019 8:51 PM
* embeddedbrowserwebview.dll, 78.00.246.0, 8/12/2019 9:44 PM

**Comment by wravery** [comment]
Just checked the Dev channel and it repros there too. Maybe related to the recent bump to Chromium 78?
* embeddedbrowserwebview.dll, 78.00.244.0, 8/8/2019 8:58 PM

**Comment by david-risney** [comment]
Thanks for the great details. I'll see if I can observe this behavior as well and investigate.

**Comment by wravery** [comment]
It turns out this was triggered by a change on my end. I was trying to use two different callbacks with different URI patterns for different purposes. Registering the second one for a specific URI pattern seems to have overridden the registration for this one.

I think this might still be a bug, since the matching `add_WebRequestReceived` and `remove_WebRequestReceived` methods use an `EventRegistrationToken` for correlation. That implies to me that you can have distinct registrations with different callbacks and all of them which match the URI pattern should be invoked. I haven't tested the other events with matching `add_`/`remove_` methods but I think the same reasoning applies if they behave the same way.

**Comment by pagoe-msft** [comment]
Happy to report that we just shipped updates to our WebResourceRequested Event in 0.8.355. Closing the issue for now and feel free to re-open the issue and let us know if you have additional feedback.
