### ISSUE TITLE
Canary Build breaks NavigationCompleted

### ISSUE THREAD

**Issue by TimWeidner** [MicrosoftEdge/WebViewFeedback#366]
When using the newest Canary Build (86.0.598.0) the WebView_NavigationCompleted() Method is never entered.

We are using the 0.9.579-prerelease version with Winforms and we basically had to switch to the weeky edge build because of this. Just putting this here, because we spent about 2 hours figuring out that Edge is responsible for this and not our code.

[AB#28208463](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/28208463)

**Comment by pagoe-msft** [comment]
@TimWeidner ,

With the new Canary build, Navigation Completed doesn't fire?

**Comment by TimWeidner** [comment]
@pagoe-msft thats precisely the problem.

**Comment by TimWeidner** [comment]
Small Update, doesn't work in 86.0.599.0 either.

**Comment by mikemeinz** [comment]
I was curious about this issue because I have a WinForms app that depends on the NavigationCompleted event. 
I tested this afternoon with Edge Canary build Version 86.0.600.0 (Official build) canary (64-bit) and 0.9.579-prerelease Winforms. I saw the expected NavigationCompleted events.

**Comment by yildirimcagri** [comment]
I do see the NavigationCompleted events with 86.0.615 in WinForms. Closing the issue for now, feel free to reopen with repro steps if you are still seeing this. Thanks!
