### ISSUE TITLE
Proposal: [.NET] Change WebResourceRequested from using exisiting .NET type to directly Expose

### ISSUE THREAD

**Issue by dianaqu** [MicrosoftEdge/WebViewFeedback#372]
In response to a high volume of user feedback and bug reports, the WebView2 team re-investigated the implementation of the Web Resource Requested event for WebView2 on .NET. 

Here is our API Change Proposal: [Proposed WebResourceRequested API Spec](https://github.com/MicrosoftEdge/WebViewFeedback/wiki/WebResourceRequested-API-Review-Spec). Please review and provide feedback here.

We appreciate your support.

**Comment by shawty** [comment]
Initial read of the proposed API doc, looks OK to me.

The interface is clean, intuitive, and makes sense to anyone used to the standard event model.

In my case, my chief use case is to return dynamically produced images from a back end method EG:


```
private void CoreWebView2_WebResourceRequested(object sender, CoreWebView2WebResourceRequestedEventArgs e)
{
  HttpResponseMessage response = new HttpResponseMessage(HttpStatusCode.OK);
  response.Content = new ByteArrayContent(File.ReadAllBytes(@"c:\\test.png"));
  response.Content.Headers.ContentType = new MediaTypeHeaderValue("image/png");
  response.StatusCode = HttpStatusCode.OK;

  e.Response = response;
}

```

I'm pulling a static image there, but in future, the byte array will be populated in code, from an external video stream on a TV tuner card fitted in the device in question.

I don't see off the top of my head how I can pass something like a byte array into this

```
CoreWebView2WebResourceResponse response = Environment.CreateWebResourceResponse(null, 403, "Blocked", "");
```

**Comment by Eilon** [comment]
@dianaqu thanks for sharing this. Do you have info on the exact signature of this method seen in the spec:

```c#
Environment.CreateWebResourceResponse(null, 403, "Blocked", "");
```

And can you share the exact types and members for these types seen in the spec?

* `CoreWebView2HttpRequest`
* `CoreWebView2HttpResponse`
* `CoreWebView2HttpRequestHeaders`
* `CoreWebView2HttpResponseHeaders`
* `CoreWebView2HttpHeadersCollectionIterator`

Without seeing what these types would look like it's hard to say whether these are a good fit for certain scenarios. I think that would help provide an answer to @shawty 's question too.

**Comment by michael-russin** [comment]
@dianaqu so it looks like you're staying much closer to what the original C++/COM interfaces exposed which is good for us.   I still think it's odd that you have to use the environment to create the WebResourceResponse.  It forces everyone to manually create the environment to fully user the WebResourceRequested event.

**Comment by shawty** [comment]
+1 to @michael-russin 's comment.  I was wondering too about the "Environment" thing, but I didn't want to mention that until I'd observed others reactions to it and gotten a better feel for thoughts surrounding that.

**Comment by champnic** [comment]
@michael-russin @shawty We do have plans to expose the Environment off of the CoreWebView2, so that even if the default environment is used you would still be able to access it to create the WebResourceResponse. That should be coming soon, and as you noted the workaround is to manually create the environment for the time being.

**Comment by dianaqu** [comment]
Hi @Eilon, the details of changed API is listed here: https://github.com/MicrosoftEdge/WebViewFeedback/wiki/WebResourceRequested-API-Review-Spec#api-notes. 
As for the details of these types. We have our COM documentation here that can help you understand it: [CreateWebResourceResponse](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/dotnet/0-9-538/microsoft-web-webview2-core-corewebview2environment#createwebresourceresponse) and [CoreWebView2WebResourceRequestedEventArgs ](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/dotnet/0-9-538/microsoft-web-webview2-core-corewebview2webresourcerequestedeventargs#response)

Let me know if this answer your questions.

**Comment by oggy22** [comment]
@Eilon our C# wrapper classes are generated automatically based on their COM counterparts, so reading our COM documentation you should be able to extrapolate what C# classes are.

**Comment by dianaqu** [comment]
@Eilon @shawty I updated the [ last section of the spec](https://github.com/MicrosoftEdge/WebViewFeedback/wiki/WebResourceRequested-API-Review-Spec) to include the part that our C# wrapper class that generated from COM. That should help get a overall looking at the whole API.

**Comment by shawty** [comment]
@dianaqu Tks, reviewing now.

**Comment by Eilon** [comment]
@dianaqu very helpful thank you!

For the .NET version, what does `CoreWebView2WebResourceResponse` look like? Will it use a COM `IStream` or a .NET System.Stream?

**Comment by dianaqu** [comment]
@Eilon  Here is what `CoreWebView2WebResourceResponse` looks like. It's the .NET System.Stream. I also updated the Spec
```c#
    public partial class CoreWebView2WebResourceResponse
    {
        public Stream Content { get; set; };
        public CoreWebView2HttpResponseHeaders Headers { get; };
        public int StatusCode { get; set; };
        public string ReasonPhrase { get; set; };
    }
```

**Comment by Eilon** [comment]
@dianaqu thank you again for the quick response. I think that API would work for what my project needs.

**Comment by dianaqu** [comment]
@Eilon that is great to hear!

**Comment by dianaqu** [comment]
Gonna close this issue as resolved.

**Comment by shawty** [comment]
@dianaqu I still have some testing to do, just not had chance as have moved onto a different bigger project for a while.

I'm sure I'll let you all know when I get back to it, if something doesn't work though.
