### ISSUE TITLE
请问如何在js里面调用WPF里面的方法，如何绑定对象

### ISSUE THREAD

**Issue by hw72869951** [MicrosoftEdge/WebViewFeedback#373]
js调用WPF原生组件，比如js调用WPF的弹窗的方法

**Comment by pagoe-msft** [comment]
We have more details here: https://docs.microsoft.com/microsoft-edge/webview2/reference/dotnet/0-9-538/microsoft-web-webview2-core-corewebview2#addhostobjecttoscript

**Comment by champnic** [comment]
Closing this issue. If you need more info or have a specific question please reopen or file a new issue. Thanks!
