### ISSUE TITLE
"Any CPU" without "Prefer 32 bit" results in BadImageFormatException

### ISSUE THREAD

**Issue by ajtowf** [MicrosoftEdge/WebViewFeedback#377]
Reproduced in this repo: https://github.com/ajtowf/WebView2WpfAppFullFx

Looking in Microsoft.Web.WebView2.targets, it's clear that the x86 binary will be loaded for the "Any CPU" configuration and with "Prefer 32 bit" unchecked this results in a runtime BadImageFormat exception when debugging.

![image](https://user-images.githubusercontent.com/3427270/89652492-d57b3580-d8c5-11ea-9245-6cd623278f61.png)

![image](https://user-images.githubusercontent.com/3427270/89684203-4b00f900-d8fa-11ea-96f6-478f1f463b6f.png)

Current workaround is to either re-package with modified target-file or check in the package with modified target-file into the repo.

**Comment by ajtowf** [comment]
Updated reproduce repo, changed to the prerelease package:

    <package id="Microsoft.Web.WebView2" version="0.9.579-prerelease" targetFramework="net472" />
    
at least compiles, but as I mentioned, how does this work with "Any CPU", without "Prefer 32 bit"?

![image](https://user-images.githubusercontent.com/3427270/89654435-f1340b00-d8c8-11ea-969a-d1c64b5f327e.png)

**Comment by dianaqu** [comment]
Hi @ajtowf , it's a known issue. It's due to wrong loader bit got copied to output path. These conditions you point out only applies to C++. We have a fix on the way that will fix how loader is being find. We are planning on including the fix with next SDK release. Thanks for the feedback!

**Comment by ajtowf** [comment]
Thanks @dianaqu I'll close this one as a duplicate of #182 then, cheers!
