### ISSUE TITLE
Disabling context menu in WebView2 control

### ISSUE THREAD

**Issue by saf-itpro** [MicrosoftEdge/WebViewFeedback#380]
**Environment**: `Windows 10 Pro - ver. 1903`, `VS2019 latest version`, `WPF Core`

When I have a manual control on an `HTML` page displayed inside [WebView2][1] control, I can disable the context menu by simply adding `oncontextmunu={return false;}` as an attribute to `<body>` tag. But in most cases the web page is displayed based on user interaction (what page user navigates to etc.).

**Question**: How can we disable to context menu of a webpage displayed in WebView2 control?

**Remarks**: 

 1. I have noticed that in some cases where a JavaScript is loaded along with a webpage, the `oncontextmunu={return false;}` does not disable the context menu even if I add this attribute programmatically to the `body` tag of loaded page. I see `AreDefaultContextMenusEnabled` property of [Microsoft.Web.WebView2.Core.CoreWebView2Settings][2] class but `VS2019` does not recognize any such property for `WebView2`.
 2. There was a similar issue on the old `WebBrowser` control of WPF as described [here][3] and [here][4], and I have the similar situation for WebView2.
 3. According to bullet 5 of this [Microsoft link][5] the issue was resolved. But the solution there seems to be related to `C++` while I'm using `C#`. Maybe, there is an alternative.

  [1]: https://docs.microsoft.com/en-us/microsoft-edge/webview2/
  [2]: https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/dotnet/0-9-515/microsoft-web-webview2-core-corewebview2settings
  [3]: https://stackoverflow.com/q/5507734/1232087
  [4]: https://stackoverflow.com/q/4412915/1232087
  [5]: https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes#08314

**Comment by ukandrewc** [comment]
Add the handler in JS, using addEventListener. That works for me.
