### ISSUE TITLE
Open/External Url Protocol, intercept and re-direct within application

### ISSUE THREAD

**Issue by vmeganathan81** [MicrosoftEdge/WebViewFeedback#384]
Using WebView2Control we would Like to intercept external URL such as mailto:// , and re-direct for appropriate application within the app, since everything is within application. Similar to issue https://github.com/MicrosoftEdge/WebViewFeedback/issues/137.

We want everything to be one single application. 

Could you please suggest workable solution for this issue with Webview2 control

**Comment by vmeganathan81** [comment]
Currently is working for us by listening to both events **FrameNavigationStarting** and **NavigationStarting**
![image](https://user-images.githubusercontent.com/19844029/89917631-02319480-dbc7-11ea-8428-def467fc0911.png)
Let us know is it okay to use for now, till API is available.

**Comment by vmeganathan81** [comment]
@champnic , any feedback on this?

**Comment by champnic** [comment]
I think that's fine to use until the API is available if it's working for you. As you noted, we are tracking adding the API for custom URI support in #137, so I'm going to close this issue. Please reopen if this solution isn't working for you.

@yildirimcagri Any reason you know that this workaround might not work?
