### ISSUE TITLE
WebView2Control using in VB6 issue

### ISSUE THREAD

**Issue by praburamb** [MicrosoftEdge/WebViewFeedback#385]
We have legacy VB6 application using internet control and third part Wow Control, but unable to call new AngularJS application from internet control. After Microsoft developed WebView2 control, I have developed Interop control in C# using VS2009 and that dll using in VB6 application.
So now I can load AngularJS application in to my VB6 application. but  Edge Canary should be installed in developer computer.

Now Product is ready to release, but since Edge canary is not a release version. How do I use ViewView2 control and how do I publish without Canary.

Please help me.
- Ram

**Comment by champnic** [comment]
For release/production you should use the WebView Runtime Installer, please see this documentation:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

The WebView2 control itself is still in prerelease/preview, so I wouldn't recommend releasing to production now anyways. The Runtime Installer will be released later this year at the same time as the Win32 control (Oct/Nov), and then the .NET controls will be after that (probably Nov/Dec).

**Comment by praburamb** [comment]
you mentioned about Win32 control (Oct/Nov), what is that one, it is not a .net control ?

**Comment by champnic** [comment]
Correct - it's this control: https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-538-reference-webview2

The .NET controls are built on top of that control, and will be shipping to production a bit later.
