### ISSUE TITLE
WebView2 WPF doesn't work when published with ClickOnce

### ISSUE THREAD

**Issue by BastienEscaich** [MicrosoftEdge/WebViewFeedback#386]
Hello,

During my testing of 0.9.579-prerelease, I noticed that while WebView2 works fine when debugging, deploying our app ends up just showing a gray background when deployed. My guess is that it is missing some DLLs but since it doesn't happen when debugging, I can't seem to figure out which one(s). I'm thinking that the NuGet package should deploy all necessary files without the need for us to "manually" do so. If this is not the case, would you mind sharing some sample code that would allow me to deploy the missing DLLs?

I'm attaching a small sample app that reproduces the problem. It deploys locally to "C:", just open setup.exe once published and notice the gray background (supposed to load www.google.com). 

Thank you for your great work!

[DemoExagoBrowserIssue.zip](https://github.com/MicrosoftEdge/WebViewFeedback/files/5063316/DemoExagoBrowserIssue.zip)

**Comment by mikemeinz** [comment]
@BastienEscaich

I had a similar problem. I found a workaround. See #228

**Comment by mikemeinz** [comment]
@BastienEscaich 

You are missing some WebView2 initialization code. Awaiting **EnsureCoreWebView2Async** and not using the control until the **CoreWebView2Ready** is thrown ensure that the WebView2 control is ready for use.  See [https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf) - Step #7 - paragraph 1.

Here is an example:
```
      public WebView()
        {
            this.Load += WebView2Test_Load;
            InitializeComponent();
            webView2.CoreWebView2Ready += webView_CoreWebView2Ready;
            webView2.NavigationCompleted += browser_NavigationCompleted;
        }

        private void WebView2Test_Load(object sender, EventArgs e)
        {
            InitializeAsync();
        }

        async private void InitializeAsync()
        {
            await webView2.EnsureCoreWebView2Async(); // Wait for coreWebView2 initialization
           
        }
        private void browser_NavigationCompleted(object sender, CoreWebView2NavigationCompletedEventArgs e)
        {
            Debug.Print("Navigation Completed");
        }

        private void webView_CoreWebView2Ready(object sender, EventArgs e)
        {
            try
            {
                webView2.Source = new System.Uri("https://microsoft.com/", UriKind.Absolute);
            }
            catch (Exception ex)
            {
                Debug.Print(ex.ToString());
            }
        }
```

**Comment by BastienEscaich** [comment]
@mikemeinz Thank you for your help. I did find this thread and implemented that solution in one of the file. I didn't realised there was a second Microsoft.Web.WebView2.targets file however, just tried modifying that one as well and it still doesn't work.

Regarding the extra loading code, I don't think this should be necessary as it works while debugging. I'll try implementing it, but I'm not convinced it will change much.

**Comment by BastienEscaich** [comment]
@mikemeinz Adding this code does work (I had to hardcode a fix to deploy the right WebView2Loader.dll since my default config is "Any Cpu"). Thanks again for your help.

**Comment by champnic** [comment]
@BastienEscaich as @mikemeinz mentioned we are fixing the .targets issue in #228, and we are fixing the AnyCPU + WebView2Loader.dll issue in #182. I'm going to close this issue out, but please reopen or file a new issue if you are running into something else. Thanks!

**Comment by cgeier** [comment]
@BastienEscaich I believe that InitializeAsync should be "Task" not "void" or your code may not execute in the expected order. Here are the changes:

Instead of:
```
private void WebView2Test_Load(object sender, EventArgs e)
{
    InitializeAsync();
}
```

I believe it should be: 
```
private async void WebView2Test_Load(object sender, EventArgs e)
{
    await InitializeAsync();
}
```

***Note:** "async" was added. "await" was also added.

Instead of: 
```
async private void InitializeAsync()
{
    await webView2.EnsureCoreWebView2Async(); // Wait for coreWebView2 initialization       
}
```
I believe it should be: 
```
async private Task InitializeAsync()
{
    await webView2.EnsureCoreWebView2Async(); // Wait for coreWebView2 initialization       
}
```

***Note:**  Changed from "void" to "Task".
