### ISSUE TITLE
Expose `ICoreWebView2` in WinUI3

### ISSUE THREAD

**Issue by bsld** [MicrosoftEdge/WebViewFeedback#387]
## Summary
Allow something like `QueryInterface` from `Microsoft::UI::Xaml::Controls::IWebView2` to `ICoreWebView2`.

## Rationale
Features like `PostWebMessage` doesn't seem to be available under `Microsoft::UI::Xaml::Controls::IWebView2`, there only seem to be an option to add a handler for `WebMessageReceived`. I'm sure there are other features missing from it but those are of the top of my head and also what I need to implement my WebGPU application with UWP shell.

[Here is the request in WinUI3 project as well](https://github.com/microsoft/microsoft-ui-xaml/issues/3112)

[AB#28413406](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/28413406)

**Comment by pagoe-msft** [comment]
@bsld 

This work is underway! I'll circle back here when the work is complete.

**Comment by champnic** [comment]
This work is being tracked and will be completed by the WinUI3 team, so closing this issue. Thanks!
