### ISSUE TITLE
Not working on Windows Server 2012R2?

### ISSUE THREAD

**Issue by MojoDK** [MicrosoftEdge/WebViewFeedback#388]
From the documentation (https://docs.microsoft.com/en-us/microsoft-edge/webview2/) Windows Server 2012R2 is on the supported list.

But when I run my test app on Windows Server 2012R2, I get this error...

**ThrowIfBeforeWindows10April2018**

Program: WebView2Test.2.exe
Framework-version: v4.0.30319
Beskrivelse: Denne proces blev afsluttet pga. en ubehandlet undtagelse.
Undtagelsesoplysninger: System.NotSupportedException
   ved Microsoft.Toolkit.Win32.UI.Controls.Interop.OSVersionHelper.ThrowIfBeforeWindows10April2018()
   ved Microsoft.Toolkit.Forms.UI.Controls.WebView.System.ComponentModel.ISupportInitialize.EndInit()
   ved WebView2Test._2.Form1.InitializeComponent()
   ved WebView2Test._2.Form1..ctor()

Undtagelsesoplysninger: System.InvalidOperationException
   ved WebView2Test._2.My.MyProject+MyForms.Create__Instance__[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.__Canon)
   ved WebView2Test._2.My.MyProject+MyForms.get_Form1()
   ved WebView2Test._2.My.MyApplication.OnCreateMainForm()
   ved Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   ved Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   ved Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(System.String[])
   ved WebView2Test._2.My.MyApplication.Main(System.String[])

I have following Nuget packages:

- Microsoft.Toolkit.Forms.UI.Controls.WebView (v6.1.2)
- Microsoft.Windows.SDK.Contracts (v.10.0.19041.1)
- System.Runtime.WindowsRuntime.UI.Xaml (v.5.0.0preview.5.20278.1)

Is it because it has not been develloped for pre 2018 opretingsystems yet?

**Comment by pagoe-msft** [comment]
@MojoDK,

It appears the NuGet package you are using for WebView: Microsoft.Toolkit.Forms.UI.Controls.WebView (v6.1.2) is the outdated one based on the old Edge browser (WebView1). The WebView2 control is in Microsoft.Web.WebView2 and .NET is in the pre-release package.

**Comment by MojoDK** [comment]
@pagoe-msft 

Thanks.

I don't see any prereelase packages?? And if I chose the v0.9.579 version and build the project, no "WebView2" control is showing in the toolbox (as stated here https://docs.microsoft.com/da-dk/microsoft-edge/webview2/gettingstarted/winforms)

Any idea why?

**Comment by champnic** [comment]
For .NET support (WPF and Winforms) you need to use the prerelease package: 0.9.579-prerelease.
If you aren't seeing the prerelease package, please make sure the "Include Prerelease" checkbox is checked in the Nuget Manager:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms#step-2---install-webview2-sdk

**Comment by champnic** [comment]
Closing this issue. If you need more help with this please reopen, or if you run into new issues please open a new issue. Thanks!
