### ISSUE TITLE
InPrivate mode to support isolated multi-user scenarios

### ISSUE THREAD

**Issue by verelpode** [MicrosoftEdge/WebViewFeedback#39]
We would find it very useful if WebView2 would support a mode equivalent to the InPrivate mode in the full MS Edge app. This is especially useful to protect/isolate one person's browsing session from the next person's browsing session, so that the next person/user doesn't gain access to the previous person's cookies, IndexedDB, saved passwords, form data.  When a kiosk computer or other web-enabled computing device is used by multiple different customers or staff members, and one person logs into their web-based email or whatever, this session/cookie data needs to be deleted before the next customer or staff member uses the computing device. This is a major issue for us.

The idea is that you'd create an "InPrivateSession" object and use the same InPrivateSession instance with multiple WebView2 instances (multiple because need to support tabs/popups/windows).  When you dispose/end the InPrivateSession instance, it should delete all cookies/passwords/IndexedDB/etc that were created during/inside that InPrivateSession instance.  Thus an InPrivateSession would be like a container that stores or records all cookies/etc created in or during that InPrivateSession and deletes them when the InPrivateSession is disposed/ended.  In other words, when a WebView2 is linked with an InPrivateSession instance, then the lifetime of new cookies should be limited to the lifetime of the InPrivateSession instance.

Regarding deletion of cached webpages, image files, etc, ideally this would be optional.  I'd love to have a setting that controls whether cache and cookies is deleted versus only cookies deleted.  The problem with deleting all cached files is that it causes a lot of extra network traffic to repeatedly re-download the same files.

Re IndexedDB:  Ideally in theory, a new temporary IndexedDB storage area would be created for each InPrivateSession, thus when an app terminates an InPrivateSession, it would ideally have no effect on IndexedDB data in other InPrivate sessions in other apps/processes.  If that's too difficult, we'd still be happy if the InPrivate session simply deletes the entire IndexedDB data or does exactly the same as the MS Edge app currently does.  In our case, the most important requirement is to prevent the next user seeing the previous user's data.

When designing an InPrivate feature, care needs to be taken to ensure that it is compatible with a separate-process mode such as `Windows.UI.Xaml.Controls.WebViewExecutionMode.SeparateProcess` and `Windows.Web.UI.Interop.WebViewControlProcess`.  In WinINet.dll, it's easy to forget that not all cookies are stored to disk.  Some cookies are only stored in the RAM of the process (cookies with NO expiration date or with the "HTTP Only" flag).

For comparison, see the WebView 1 method [WebView.ClearTemporaryWebDataAsync](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.cleartemporarywebdataasync).  This is very useful but unfortunately it's not fine-grained enough because of the inability to exclude the clearing of cached files.  This method is a _static_ method in WebView 1 but for WebView2 it'd be worthwhile considering whether it should be static or per-instance and how that affects the separate-process mode (a per-instance method can access `WebView.Process` whereas a static method cannot).

See also (partially relevant) [INTERNET_SUPPRESS_COOKIE_PERSIST](https://docs.microsoft.com/en-us/windows/win32/wininet/option-flags) and [INTERNET_OPTION_END_BROWSER_SESSION](https://docs.microsoft.com/en-us/windows/win32/wininet/option-flags).

**Comment by verelpode** [comment]
@liminzhu
> This is a really interesting idea and it occurred to me when I was reading your initial comment too! What holds me back is with InPrivate, you still have to write up logic to tear things down when a user session end and create new WebView for another upcoming user. It isn't much different from creating another webview from a new user data folder and deleting the old one, which you can do today.

Can you give me (and also add to the documentation) a list of what the [user data folder](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/webview2.idl#createwebview2environmentwithdetails) contains?  Which of the following does the folder include and exclude?

* Temporary cookies (those marked "HTTP Only" or those that have no expiration date).  Only in RAM or stored in user data folder?
* Persistent cookies (those that have an expiration date).
* Navigation history for the `WebView.GoBack` and `WebView.GoForward` commands.
* IndexedDB.
* Cached files (HTML webpages, image files, etc).
* Form auto-fill data.
* Saved passwords.
* What else?

Is [WinINet.dll documentation](https://docs.microsoft.com/en-us/windows/win32/wininet/about-wininet) relevant to WebView2 or will it no longer use WinINet.dll?

Does the following rule of WinINet.dll also apply to WebView2?
_"Session cookies are stored in memory [RAM] and can be accessed only by the process that created them."_

> Priority 1 - WebView API needs to support a workflow for isolated user session. When a previous user is finished, WebView cannot leak any data from previous user to the next.

Correct.  (If this requires the creation of a new instance of WebView2 when switching to the next user, and closing/disposing the previous instance, then that's not a problem.)

> Priority 2 - While user data should be isolated, it'd be great if non-sensitive cached resources such as images can persist.

Yes.  The network department requested our group to avoid generating unnecessary traffic if possible.  We noticed that unnecessary cache deletion occurs many times per day in some locations where each computer is briefly used by multiple different staff members within the same day.  Over the course of a week, we have thousands of unnecessary cache deletions.

**Comment by david-risney** [comment]
Any state that the Chromium based Edge browser stores (or WebView2 in this case) is stored in the user data folder. Everything you listed plus user settings, crash dumps, really anything you can think of that needs to be persisted.

The Chromium based Edge (and WebView2 in this case)

**Comment by verelpode** [comment]
Thanks for the details. OK, as @liminzhu indicated, it seems like the only missing functionality re InPrivate is the option to delete everything except for non-sensitive cached resources such as images.

**Comment by champnic** [comment]
We aren't currently planning any extra work in this space - deleting the UserDataFolder is the recommended approach here. InPrivate-type mode would typically want to delete cached images anyways, as images can very often contain sensitive information.
