### ISSUE TITLE
WeakRef is missing from the web view

### ISSUE THREAD

**Issue by R2D221** [MicrosoftEdge/WebViewFeedback#390]
I'm testing some stuff with WeakRef (which as I understand is fairly new)... but I'm surprised to see it's not available in the web view. What's weird is that in both the Stable and Canary builds which I have installed I can find it just fine. It's just when using WebView2 where the reference can't be found.

Do I need to explicitly enable it somehow? Or is there a reason why it's disabled for WebView2?

[AB#28434023](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/28434023)

**Comment by oggy22** [comment]
Thank you for submitting this issue. Can you please clarify few things:
- do you use c++ or .NET control?
- What do you mean by WeakRef?

**Comment by R2D221** [comment]
1) I'm using the .NET control
2) By WeakRef I mean this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef

**Comment by liminzhu** [comment]
It's a bug on our end that we'd definitely fix.

**Comment by R2D221** [comment]
Thanks!

**Comment by liminzhu** [comment]
No problem, thanks for reporting it!

**Comment by champnic** [comment]
This should be fixed and available in Edge 86.0.621.0+. Thanks!
