### ISSUE TITLE
Can we go live with Microsoft Edge Stable Channel + WebView2Loader (Win32)?

### ISSUE THREAD

**Issue by vmeganathan81** [MicrosoftEdge/WebViewFeedback#391]
This more a question rather than issue, 
We have application already working and ready.

Using WebView2Loader, we are able to change browserexecutable folder to Stable Edge production channel.

Both WebView2Loader and Edge are production version.

WebView2Loader
![image](https://user-images.githubusercontent.com/19844029/90276467-f4337c00-de31-11ea-953f-a88b85b8729c.png)

Please let us know your feedback

**Comment by champnic** [comment]
We're actually going to be removing this workaround (loading Stable Edge from browserExecutableFolder) in the next release, so I wouldn't recommend this approach. Instead you should use the WebView Runtime Installer.

We also haven't fully released the control for GA yet, so if you went live now it would be with a preview control. You should wait until we release, which is probably sometime in October (.NET should be released sometime in Nov/Dec).

**Comment by champnic** [comment]
Here are some potentially helpful links:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/versioning
https://developer.microsoft.com/en-us/microsoft-edge/webview2/

We're putting together more docs/samples on exactly how to incorporate the runtime into your apps installation/deployment.
