### ISSUE TITLE
[DMC] CoreWebView2 is null when accessing it from another XAML Window in the same project #822

### ISSUE THREAD

**Issue by Reezaali** [MicrosoftEdge/WebViewFeedback#393]
Hi, please review the customer issue located at: https://github.com/MicrosoftDocs/edge-developer/issues/822

Thanks.

**Comment by pagoe-msft** [comment]
Hi,

The creation of the Core WebView2 object is asynchronous. Before calling functions off of Core WebView2 await [EnsureCoreWebView2Async](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/wpf/0-9-515/microsoft-web-webview2-wpf-webview2#ensurecorewebview2async).

Here is an example from the getting started guide:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf#step-7---communication-between-host-and-web-content

**Comment by saf-itpro** [comment]
@Reezaali  Issue resolved.  Thank you.

**Comment by Reezaali** [comment]
I'll go ahead and close this issue now. Thanks.
