### ISSUE TITLE
WebView2 message handler doesn't seems to be triggered.

### ISSUE THREAD

**Issue by bsld** [MicrosoftEdge/WebViewFeedback#394]
So I'm posting a message from my `ICoreWebView2` interface - but my registered `window.chrome.webview.addEventListener('message', ` handler doesn't seems to be called (I've put `alert` and `console.log` in there). 

Initially I was embedding my script in the `NavigateToString` method but then I saw in the examples they used `AddScriptToExecuteOnDocumentCreated` instead - I tried that as well but it doesn't seem to be working.

Maybe the issue is that I'm asynchronously loading my files in my message received handler and then posting a web-message from a different thread. Currently however I'm requesting only one file for test purposes.

On request I can commit/push my progress so far and link my dev repo.

And also no the same note - I think it'll be useful if you can directly post message to a specific worker.

**Comment by bsld** [comment]
It turned out I was just using the wrong interface. Closing now.

**Comment by champnic** [comment]
Glad you got it figured out! Let us know if there was anything confusing about our documentation or more info that would have helped here. Thanks!
