### ISSUE TITLE
Unity3d compatibility?

### ISSUE THREAD

**Issue by Nanocentury** [MicrosoftEdge/WebViewFeedback#401]
I've been interested in web view solutions for Unity3d apps for Windows.
Is a plugin or compatibility on the roadmap?

**Comment by champnic** [comment]
It's on our backlog. In particular it would be very helpful for building Hololens apps which we hope to support in the future. However, it's not a very high priority right now, so potentially sometime in 2021 is the best I could say. This work will be tracked in #20. Thanks!

**Comment by BinaryNate** [comment]
@Nanocentury , just a heads-up in case it is helpful: I develop a library for Unity called [3D WebView](https://developer.vuplex.com/webview/overview) that supports UWP apps, including Hololens 1 & 2. It currently uses the original UWP WebView component, but I plan to upgrade it to WebView2 [when it is available](https://github.com/MicrosoftEdge/WebView2Feedback/issues/1021).
