### ISSUE TITLE
Webview2 with Excel-Dna / COM addin gives System.NullReferenceException

### ISSUE THREAD

**Issue by cirrusone** [MicrosoftEdge/WebViewFeedback#405]
Attempting to use Webview2 with an Excel-Dna addin (and also a COM addin) gives the following error

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

StackTrace:
```
   at Microsoft.Web.WebView2.WinForms.WebView2.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.AssignParent(Control value)
   at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at System.Windows.Forms.Form.ControlCollection.Add(Control value)
   at ClassLibrary1.Form1.InitializeComponent()
```

It fails on line `this.Controls.Add(this.webView2);` in `Form1.Designer.cs`

Attached is sample project where bug occurs [Sample repo](https://www.dropbox.com/s/jca3zz4ir8iwy1v/ClassLibrary1.7z?dl=0)

There is no error if Webview2 is removed entirely. Also Webview2 appears to work okay in a 'pure' winform app without Excel-Dna.

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Excel-DNA" version="1.1.1" targetFramework="net472" />
  <package id="ExcelDna.AddIn" version="1.1.1" targetFramework="net472" developmentDependency="true" />
  <package id="ExcelDna.Integration" version="1.1.0" targetFramework="net472" />
  <package id="Microsoft.Web.WebView2" version="0.9.579-prerelease" targetFramework="net472" />
</packages>
```

[AB#28748698](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/28748698)

**Comment by yanshuiting** [comment]
I face this issue too,pure winformApp works fine,webview2 excel dna project can only work okay on my developing machine（win10 + vs2017），but the  excel dna project throw nullreferenceException on onther machine（win10 or win7）

**Comment by pagoe-msft** [comment]
@cirrusone,

Thanks for bringing this to our attention! I've filed a bug for us to look into this.

**Comment by champnic** [comment]
@cirrusone I'm unfamiliar with ExcelDNA. This is trying to embed a WebView2 add-in to the Excel ribbon? (That sounds pretty cool :D )
Is it the WebView2 object that's null when adding the control to the Form?

**Comment by cirrusone** [comment]
Excel-DNA is good for adding .NET ribbon functionality without requiring registration or installation.

Hovering over the Webview2 object in debug doesn't appear to indicate it's null but it does crash and is not able to be inspected.

![Untitled](https://user-images.githubusercontent.com/10389314/91431339-25f80a00-e858-11ea-90f8-e44f61c4770b.png)

Object `this` and `Controls` are fine so it's definitely an issue with webview2.

**Comment by champnic** [comment]
I debugged through this a bit. I think the underlying issue is that the default UserDataFolder that's being created is inaccessible for the browser to write to because it's under the C:\program files\... folder. To fix this, you can manually set the UserDataFolder to something else. The changes below made the code you posted work for me:
In **Form1.Designer.cs - InitilializeComponent()**, comment out the Source property.
```
this.webView2.Size = new System.Drawing.Size(776, 426);
//this.webView2.Source = new System.Uri("about:blank", System.UriKind.Absolute);
this.webView2.TabIndex = 0;
```

In **Form1.cs**, use explicit initialization with a different UserDataFolder.
```
        public Form1()
        {
            InitializeComponent();
            InitializeAsync();
        }
        async void InitializeAsync()
        {
            // Set the UserDataFolder to something that the runtime can write to.
            var env = await CoreWebView2Environment.CreateAsync(null, "C:\\temp");
            await webView2.EnsureCoreWebView2Async(env);
        }
```

**Comment by cirrusone** [comment]
Thanks for the update.

I cannot get that working this end, it gives another error. (I have created a temp folder on the C: drive).

![Untitled](https://user-images.githubusercontent.com/10389314/91465551-d16b8380-e885-11ea-87b6-63eda70abfb3.png)

```
System.BadImageFormatException
  HResult=0x8007000B
  Message=An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
  Source=Microsoft.Web.WebView2.Core
  StackTrace:
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ClassLibrary1.Form1.<InitializeAsync>d__1.MoveNext() in C:\Users\os\Desktop\New folder\ClassLibrary1\ClassLibrary1\Form1.cs:line 25
```

**Comment by jozefizso** [comment]
@cirrusone most probably use are using different bitness of MS Office application and the WebView2 libraries.

**Comment by cirrusone** [comment]
I'm using 64bit Excel, does webview2 have different bitness versions?

**Comment by champnic** [comment]
Yes, the webview2loader.dll (which finds, launches, and connects to the browser/runtime) is 32 or 64 bit. What version of the SDK are you using? We recently made some fixes to the loader bitness + deployment.

**Comment by cirrusone** [comment]
Apologies, it is working. I switched to an image that didn't have Edge installed at all. This is working okay now, thanks for your help.

**Comment by champnic** [comment]
Glad it's working! I'm going to close this issue. If you run into the same problem please reopen this issue, or open a new issue. Thanks!
