### ISSUE TITLE
Can't reset User Agent  ( NET)

### ISSUE THREAD

**Issue by PvlD** [MicrosoftEdge/WebViewFeedback#408]
Version: 0.9.579-prerelease.
Target : Net  4.6.2
_Application: WinForms_

 private void CoreWebView2_WebResourceRequested(object sender, **CoreWebView2WebResourceRequestedEventArgs** e)
        {
            // _**next line doesn't change  UserAgent**_
            e.Request.Headers.UserAgent.Add(new System.Net.Http.Headers.ProductInfoHeaderValue("ZZZ","0.0.0.0"));

_in CPP Sample works OK:_

requestHeaders->SetHeader(L"User-Agent", m_overridingUserAgent.c_str());

_Also setUserAgentOverride  not work in NET._

this._webView2Control.CoreWebView2.CallDevToolsProtocolMethodAsync("Network.setUserAgentOverride", arg)

**Comment by champnic** [comment]
This will be fixed by the changes coming as part of #372, which should be available in the next SDK release. Thanks!
