### ISSUE TITLE
WebView2 Release timeline

### ISSUE THREAD

**Issue by vbjain** [MicrosoftEdge/WebViewFeedback#412]
Hi,

We are building WPF Desktop App with Microsoft.WebView.Webview2 Nuget package. But it looks like the package works only with EDGE CANARY build. Also, there are some implementation in package which are not fully functional.

Can you please let me know when can we expect the Webview2 for WPF to be in production (not in pre-release)? We plan to release our product soon and we cannot release with EDGE Canary build.

Thank you,
Viral.

**Comment by mikemeinz** [comment]
[https://docs.microsoft.com/en-us/microsoft-edge/webview2/roadmap](https://docs.microsoft.com/en-us/microsoft-edge/webview2/roadmap)

[https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution)
See **Evergreen WebView2 Runtime Installer**

**Comment by champnic** [comment]
Thanks @mikemeinz! 

From those pages: "The .NET SDK wraps the Win32 C/C++ SDK. The .NET SDK is expected to GA shortly after the Win32 C/C++ GA in Q4 2020."

Canary vs Runtime: "There are multiple channels WebView2 that applications may use as the web platform. By default, WebView2 targets the most stable channel available on the device that meets the minimum version requirement of the WebView2 SDK. The following channels are listed in order from most to least stable channel.

WebView2 Runtime (Preview)
Microsoft Edge Beta Channel
Microsoft Edge Dev Channel
Microsoft Edge Canary Channel"

If you have specific implementations that you think are missing, please open separate issues for each one. Thanks!
