### ISSUE TITLE
Unable to try out the WebView2 WPF Browser example with v0.9.579/0.9.579-prerelease

### ISSUE THREAD

**Issue by noseratio** [MicrosoftEdge/WebViewFeedback#415]
Please help me to try `WebView2` with a simple .NET Core WPF app.

## Unable to try out the WebView2 WPF Browser example

Please help me to try `WebView2` with a simple .NET Core WPF app.

[This repro](https://github.com/noseratio/WebView2WpfBrowser) is just a clone of Microsoft's [WebView2 WPF Browser](https://github.com/MicrosoftEdge/WebView2Samples/tree/master/SampleApps/WebView2WpfBrowser), shaped as a .NET Core 3.1 app and using the [`Microsoft.Web.WebView2` 0.9.579-prerelease](https://www.nuget.org/packages/Microsoft.Web.WebView2/0.9.579-prerelease), with added error handling:

```C#
public partial class App : Application
{
    public App()
    {
        this.DispatcherUnhandledException += App_DispatcherUnhandledException;
        InitializeComponent();
    }

    private void App_DispatcherUnhandledException(object sender, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs e)
    {
        MessageBox.Show(e.Exception.Message);
        e.Handled = false;
    }
}
```

To try it out (Visual Studio is **not** required):

- Download and install [Download .NET Core 3.1 SDK](https://download.visualstudio.microsoft.com/download/pr/547f9f81-599a-4b58-9322-d1d158385df6/ebe3e02fd54c29487ac32409cb20d352/dotnet-sdk-3.1.401-win-x64.exe), v3.1.401 at the time of writing this.

- Run it from the project folder:
  ```
  dotnet run
  ```

## I'm get this runtime error:
  ```
  Couldn't find a compatible Edge application to host WebViews.
  ```

My Edge version:
  ```
  Microsoft Edge is up to date.
  Version 85.0.564.41 (Official build) (64-bit)
  ```

If I change the `Microsoft.Web.WebView2` package reference to the most recent [0.9.579](https://www.nuget.org/packages/Microsoft.Web.WebView2/0.9.579) (at the time of writing), I can't even compile it. In `WebView2WpfBrowser.csproj`:

```XML
<ItemGroup>
  <PackageReference Include="Microsoft.Web.WebView2" Version="0.9.579" />
</ItemGroup>
```

I'm getting these compile time errors:

```
App.xaml(18,10): error MC3074: The tag 'CoreWebView2CreationProperties' does not exist in XML namespace 'clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf'. 

MainWindow.xaml(57,10): error MC3074: The tag 'WebView2' does not exist in XML namespace 'clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf'. 
```

Apparently, [the NuGet package for WebView2 v0.9.579](https://www.nuget.org/packages/Microsoft.Web.WebView2/0.9.579) is missing a bunch of DLLs and the whole `lib\netcoreapp3.0` folder:

```
Microsoft.Web.WebView2.Core.dll
Microsoft.Web.WebView2.Core.xml
Microsoft.Web.WebView2.WinForms.dll
Microsoft.Web.WebView2.WinForms.xml
Microsoft.Web.WebView2.Wpf.dll
Microsoft.Web.WebView2.Wpf.xml
```

**Comment by champnic** [comment]
For WPF/.NET, you need to -prerelease SDK package.

Per [versioning docs](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/versioning), your browser build version must be higher than the SDK build version. So for SDK 0.9.579, you need a browser *.*.579.*+. Your current browser version is only 85.0.**564**.41, and so is incompatible with the SDK 0.9.**579**. Try the latest [Dev or Canary build](https://www.microsoftedgeinsider.com/en-us/download/). Thanks!

**Comment by noseratio** [comment]
Thank you. With Edge Dev v86.0.615.3 and WebView 2 *v0.9.579-prerelease*, I'm able to run this sample code.
I used Chocolatey to install it, in case someone wants to try it:

```
choco install microsoft-edge-insider-dev
```

However, with *v0.9.579* I still can't compile it, with the same errors. I believe this version of the package is missing the key assemblies.

**Comment by pagoe-msft** [comment]
@noseratio, Since our .NET version is still in preview we have placed it in the pre-release package. We will move the DLLs over to the release package once we GA.

**Comment by noseratio** [comment]
> @noseratio, Since our .NET version is still in preview we have placed it in the pre-release package. We will move the DLLs over to the release package once we GA.

@pagoe-msft, in this light, could the *non* .NET version (i.e., Win32 C/C++) be considered of production quality already? I thought it's still [in Preview with GA in Q4 2020](https://docs.microsoft.com/en-us/microsoft-edge/webview2/roadmap).

**Comment by champnic** [comment]
It's a little bit confusing, but no, the non-.NET version (in the "release" package) is not production quality yet. It's super close, but is still in preview. It will be releasing first, which is why it's in the "release" package currently.

**Comment by noseratio** [comment]
@champnic, understood, tks. FWIF, I've now put together a memory footprint comparison of some different flavours of WebView-based desktop apps:

[Electron vs Chromely vs Edge/WebView2 vs Legacy IE11/WebBrowser](https://dev.to/noseratio/comparing-process-working-sets-of-webview-based-windows-desktop-apps-5dkk).

**Comment by champnic** [comment]
Thanks @noseratio! We were just discussing your investigation today on the team :) We've got a bug to make sure that all the child processes correctly show up under the app in Task Manager - currently it only shows a few of them. We've also noticed a discrepancy between Task Manager reporting and ProcExp, where Task Manager reports a lower number. In particular one of our engineers pointed out that a lot of the ProcExp Working Set memory was in shared files mapped into multiple processes, so the Task Manager number is probably more accurate. That said, it's good to see that all of the chromium-based web controls were similar, as there isn't a _ton_ of code divergence. On bing.com, I also noticed that the size of the page (and resizing the page) can result in drastically different values.

**Comment by noseratio** [comment]
Thanks, I feel heard, so here's more ranting :-)

I agree, there might be better metrics in Process Explorer (see the pic below), I'm gonna experiment more with it, time permitting. Also, something more simple like [example.com](https://example.com) night be a more sensible test case. 

One other thing I noticed is that if I use Chromely with Xilium.CefGlue (vs CefSharp), the memory footprint is a few hundred megs lower, going to look deeper into that, too. On a side note, [Chromely](https://github.com/chromelyapps/Chromely) is an amazing (thank you @mattkol) but underrated project. If it had some corporate backing, it could bring a huge boost to .NET/Blazor/WASM adoption for Desktop, as a much needed .NET alternative to Electron.

IMO, the memory footprint is very important as more people will be moving from IE11 `WebBrower` to `WebView2`. For example, I still use `WebBrowser` just [for `textarea` as plain text editor](https://github.com/postprintum/devcomrade/blob/main/AppLogic/Presenter/Notepad.cs), and it's hard for me to justify adopting `WebView2` for that.

<img src="https://user-images.githubusercontent.com/4774875/91784136-7e0e8200-ec45-11ea-91f7-0d228e0c9cbf.png" width="300">

**Comment by champnic** [comment]
In ProcExp, the setting the matches the data TaskMgr gives is the "WS Private Bytes" column. (WS Private Bytes + WS Shared Bytes = Working Set Size). 

I agree that something like example.com would be better, or even your own test page that you make, to keep the different tests as close as possible. Also should control for the size of the web controls, though on static pages I don't think that should have too much of an effect.

Chromely is new to us, so thanks for sharing! Curious that using CefGlue saves a few hundred megs. If it's still using CEF/Chromium under-the-hood I would expect it to be similar to the other chromium-based controls, so my first inclination would be to check if it's something to do with the process/memory reporting (like maybe it has a process that doesn't show up directly in the tree, but parented somewhere else, etc.)

For Edge as a whole we care a lot about the fundamentals, of which memory footprint is a piece. On the WebView2 side there's probably limits to what we can/will do, as it is mostly work done by other teams on Edge. When looking at other web controls (like WebBrowser) we believe we are competing on other aspects as well, like having access to a modern and secure web platform. However, that doesn't mean that WebView2 will always be the right choice, and I think your example of just needing a textarea in an app is a great example where maybe WebView2 isn't the best option, especially if there are any constraints around memory (low-spec hardware, etc.)

**Comment by noseratio** [comment]
> Chromely is new to us, so thanks for sharing!

I believe Chromely is very important because currently it's is the only framework to build self-contained, *cross-platform* desktop HTML apps with C# and .NET Core. I picked Electron for my own SaaS project over Chromely only because I feel Chromely doesn't have enough backing from some big players yet. 

> When looking at other web controls (like WebBrowser) we believe we are competing on other aspects as well

IMO, Embedding `WebBrowser` (or MSHTML part of it) is still a viable tool and has many advantages:

- Trident is still a decent HTML5 renderer
- it has relatively low memory footprint 
- its feature set is frozen which means more stability, predictability and fewer bugs
- nothing needs to be installed or bundled
- it still receives security updates as part of Windows updates
- we can easily interact with DOM from C# via COM interfaces, without for any proxying code relying on JavaScript

The problem is,  Microsoft is somewhat unclear about when (if ever) IE11 is going to be removed from Windows. The information on this is very scarce. To my best understanding, [it's expected to still be around at least until 2019](https://www.reddit.com/r/webdev/comments/i9bvps/does_any_part_of_your_lineofbusiness_web/g1e9it6?utm_source=share&utm_medium=web2x&context=3).  Happy to be corrected about that assumption.

**Comment by RickStrahl** [comment]
@noseratio Totally agree on the WebBrowser versus WebView debate. In Markdown Monster I've been using the WebBrowser control for a heavy interfacing with ACE Editor as an editor control plus a preview and one thing that really stood out is that overall memory usage of the application was pretty low (around 100-150mb typically even with a number of editors open). 

I recently added a WebView2 as an optional add in and the memory usage (externally via the WebView instances) goes up drastically typically running around 400-500mb just for the WebView instances.

As much as I hate that - it seems ridiculous for a text editor to have this usage, the memory footprint is similar to other Chromium applications including Electron apps, or apps like Brave or even Edge. The only exception that seems to control memory much better seems to be VS Code, which seems to have reasonable mem usage but they also use Chromium via Electron. What is VS Code doing differently running Chromium and not incurring that huge memory hit? Mucking with the memory reporting or freeing memory when switching away from the app perhaps?

**Comment by noseratio** [comment]
> The only exception that seems to control memory much better seems to be VS Code, which seems to have reasonable mem usage but they also use Chromium via Electron.

@RickStrahl  I could only speculate, but maybe what makes VS Code different from other Electron apps is their very lightweight front-end UI framework. It's pretty much vanilla JS + Monaco editor. OTOH, MS Teams (also Electron) uses Angular and I've seen Teams cruising at ~6GB on my desktop. To an extent, it's possible to do micro-memory-management in Chromium with things like [`WeakRef` and finalizers](https://v8.dev/features/weak-references), but I doubt VS Code uses that. A good thing is, their source code is open, I haven't dug deep yet myself but I plan to.

But overall yeah, this memory footprint is the new reality for modern Windows desktop apps, as most of them need a WebView (i.e., some form of Chromium).

**Comment by noseratio** [comment]
For those who may end up here after the `WebView2` GA release, be sure to [check this update](https://dev.to/noseratio/comparing-process-working-sets-of-webview-based-windows-desktop-apps-5dkk/#ga-update).
Kudos to the MSEdge team for such an improvement!

**Comment by champnic** [comment]
Thanks for the investigation and writeup @noseratio! :)
