### ISSUE TITLE
Need support for WebView in dialogs like CDHtmlDialog

### ISSUE THREAD

**Issue by dd8** [MicrosoftEdge/WebViewFeedback#417]
The MFC class CDHtmlDialog uses MsHtml.dll
https://docs.microsoft.com/en-us/cpp/mfc/reference/cdhtmldialog-class?view=vs-2019

Need support for building similar HTML dialog UIs using WebView2. It doesn't have to be MFC - just need some supported way of doing this in Win32. The documentation implies webview2 can only be attached to top level windows:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-538/icorewebview2controller#put_parentwindow

I tried adding an HTML dialog as a scenario to WebView2ApiSample but couldn't get it to work - no webview appeared in the dialog. The code I used was

```
// Message handler for HTML dialog.
INT_PTR CALLBACK AppWindow::HtmlDialog( HWND hDlg, UINT message, WPARAM wParam, LPARAM lParam )
{
    switch (message)
    {
    case WM_INITDIALOG:
        // Step 3 - Create a single WebView within the parent window
        // Locate the browser and set up the environment for WebView
        CreateCoreWebView2EnvironmentWithOptions( nullptr, nullptr, nullptr,
            Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(
                [hDlg]( HRESULT result, ICoreWebView2Environment* env ) -> HRESULT {

                    // Create a CoreWebView2Controller and get the associated CoreWebView2 whose parent is the main window hWnd
                    env->CreateCoreWebView2Controller( hDlg, Callback<ICoreWebView2CreateCoreWebView2ControllerCompletedHandler>(
                        [hDlg]( HRESULT result, ICoreWebView2Controller* controller ) -> HRESULT {

                            // Resize WebView to fit the bounds of the parent window
                            RECT bounds;
                            GetClientRect( hDlg, &bounds );
                            controller->put_Bounds( bounds );
                            controller->put_IsVisible( TRUE );

                            // Schedule an async task to navigate to example.com
                            ICoreWebView2* webview;
                            controller->get_CoreWebView2( &webview );
                            webview->Navigate( L"https://www.example.com/" );

                            // Step 4 - Navigation events

                            // Step 5 - Scripting

                            // Step 6 - Communication between host and web content

                            return S_OK;
                        } ).Get() );
                    return S_OK;
                } ).Get() );

        return (INT_PTR)TRUE;

    case WM_COMMAND:
        if (LOWORD( wParam ) == IDOK || LOWORD( wParam ) == IDCANCEL)
        {
            EndDialog( hDlg, LOWORD( wParam ) );
            return (INT_PTR)TRUE;
        }
        break;
    }
    return (INT_PTR)FALSE;
}
```

**Comment by champnic** [comment]
Thanks for trying this out @dd8! The "topLevelWindow" mentioned in the documentation is a bug - we'll fix the naming there. The reason the webview isn't showing up is that you need to keep a reference to the controller. Otherwise, as soon as the lambda completes the controller will lose its ref and clean itself up, including the webview. Can you try that?

**Comment by dd8** [comment]
Great, stashing the controller reference in a static scoped to the dialog WndProc worked, then freed on WM_DESTROY

Might be worth adding an HTML dialog as a scenario to WebView2ApiSample - not much required:

1) dialog resource
2) dialog wnd proc (I just copied the About wndproc and pasted in the WebView2 getting started Step 3 code)
3) menu command to display dialog

**Comment by champnic** [comment]
Happy you got it working! We've fixed the documentation to just be "parentWindow" instead of "topLevelWindow" to make it more clear, and we may add that sample code in the future. Thanks!
