### ISSUE TITLE
WebresourceRequests returning large files crashes WebView2 

### ISSUE THREAD

**Issue by swilhelmi** [MicrosoftEdge/WebViewFeedback#418]
**Description**
Loading a large stream (120MB) into a WebresourceRequestedEventArgs->Response crashes the webView2.

**Version**
SDK: WebView2 0.9.579-prerelease
Runtime: Edge WebView2 Runtime 86.0.615.3
Framework: WPF
OS: Win10

**Repro Steps**

1. Handle  WebContent.CoreWebView2.WebResourceRequested event.
2. Write big chunk of data (120MB) to CoreWebView2WebResourceRequestedEventArgs.Response
   (using workaround from https://github.com/MicrosoftEdge/WebViewFeedback/issues/219)
=> WebView2 crashes.

**Screenshots**

**Additional context**

[AB#28985510](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/28985510)

**Comment by champnic** [comment]
If you run with a debugger do you get a crash stack? I'm opening a bug on our side to track this and we'll take a look. Thanks!

**Comment by swilhelmi** [comment]
Hello, thanks for the quick reaction.
I tried to reproduce the Problem to get you further informations.
In the mean time Edge upgraded to 86.0.622.3 and the problem seems to have vanished.

With the original setup the view went blank and a few seconds after the rest of the application crashed too. The debugger did not hold any where.

**Comment by swilhelmi** [comment]
Edge WebView2 Runtime 86.0.622.3 quite definitely solved the problem. Even older builds of our application did fine with the new Edge Version. Also tested with a 300 MB chunk of date.

**Comment by champnic** [comment]
That's great to hear, thanks for the follow-up! I'll close this for now, but please reopen if you see this again. Thanks!
