### ISSUE TITLE
The name "WebView2" does not exist in the namespace "clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"

### ISSUE THREAD

**Issue by mphacker** [MicrosoftEdge/WebViewFeedback#426]
**Description**
I have been using an older version (0.9.579-prerelease) of the WebView2 with WPF (.net core) without issue.  I upgrade to anything higher, including 0.9.622.11 and I get the error The name "WebView2" does not exist in the namespace "clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"

**Version**
SDK: 0.9.622.11
Framework: WPF .Net Core
OS: Win10, Windows Server 

**Repro Steps**
1. update nuget package and error occurs.

**Comment by mphacker** [comment]
It appears that WPF is only in the -preview packages.  This is very confusing and should be noted in the documentation instead of having to search through old issues here.

**Comment by cgeier** [comment]
@mphacker See the [Release notes for WebView2 SDK](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes)

![Release Note - Use Preview](https://user-images.githubusercontent.com/34412039/92841335-2c39ca80-f3b0-11ea-8385-4d07d428979d.JPG)

**Comment by Symbai** [comment]
I ran into the same issue although I read the readme. In readme it says it requires the prerelease version and in VS I have enabled "include previews" and installed the latest (preview) version. However the prerelease version which is required is NOT listed at the top, this means VS will download another version instead. This is confusing.

**Comment by pagoe-msft** [comment]
@Symbai,

We are aware that is is confusing. I do believe this was corrected with yesterday's release. When pre-release is checkmarked the pre-release package is at the top and default by VS. Is this not what you're experiencing? Can you send a screenshot?

**Comment by mphacker** [comment]
I did grab the pre-release package yesterday. It did show up on top and worked.  Thank you.  That along with the notice on the WPF getting started page does clear things up a lot.  Appreciate it!

**Comment by Symbai** [comment]
> @Symbai,
> 
> We are aware that is is confusing. I do believe this was corrected with yesterday's release. When pre-release is checkmarked the pre-release package is at the top and default by VS. Is this not what you're experiencing? Can you send a screenshot?

I've installed it yesterday but perhaps before you corrected it? It had installed 0.9.622.11 for me instead of 0.9.579-prerelease. But today I see there is a new version at the top 0.9.628-prerelease so yeah, its fixed at least now.

**Comment by pagoe-msft** [comment]
@Symbai perfect! Yes we fixed it yesterday! Thanks for the feedback.
