### ISSUE TITLE
WebView2 not using newest MS Edge version installed

### ISSUE THREAD

**Issue by cgeier** [MicrosoftEdge/WebViewFeedback#429]
**Description**
I have all of the following MS Edge (development) versions installed:

- **MS Edge Beta**: 86.0.622.11 (%ProgramFilesx86%\Microsoft\Edge Beta\Application\msedge.exe)
- **MS Edge Dev**: 87.0.634.0  (%ProgramFilesx86%\Microsoft\Edge Dev\Application\msedge.exe)
- **MS Edge Canary**: 87.0.637.0 (%UserProfile%\AppData\Local\Microsoft\Edge SxS\Application\msedge.exe)

I installed Beta first, then Dev, then Canary. When I run my WinForms program with a WebView2 control on it, and call **Microsoft.Web.WebView2.Core.CoreWebView2Environment.GetAvailableBrowserVersionString()**, it's showing **86.0.622.11 beta**. I expect it to use/show the highest version installed, not the lowest (development) version.

**Version**
**SDK**: 0.9.628.0-prerelease
**Runtime**: Beta: 86.0.622.11; Dev: 87.0.634.0; Canary: 87.0.637.0
**Framework**: WinForms
**OS**: Win10 ReleaseId: 2004 CurrentBuild: 19041 (64-bit)

**Repro Steps**

- Create a new WinForms project
- Add WebView2 NuGet package to project
- Add WebView2 control to Form1
- Subscribe to "Load" event for Form1
- In "Load" event handler, get the version using **GetAvailableBrowserVersionString()**

**Form1_Load:**
```
private void Form1_Load(object sender, EventArgs e)
{
    System.Diagnostics.Debug.WriteLine("WebView2 version: " + Microsoft.Web.WebView2.Core.CoreWebView2Environment.GetAvailableBrowserVersionString());
}
```

Output shows:
**WebView2 version: 86.0.622.11 beta**

**Comment by champnic** [comment]
The default behavior is to use the most stable browser/runtime: WV2 Runtime > Beta > Dev > Canary.

However, you can change this behavior. If you want a specific folder, you can set the [browserExecutableFolder ](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/dotnet/0-9-538/microsoft-web-webview2-core-corewebview2environment#createasync) to the location of the specific channel you'd like to use (for example, "C:\Program Files (x86)\Microsoft\Edge Dev\Application" for the Dev channel).  I recommend you do this for development only, not release.

You can also reverse the behavior to use the most unstable: Canary > Dev > Beta > WV2 Runtime.
To reverse the order, you can set the WEBVIEW2_RELEASE_CHANNEL_PREFERENCE environment variable to 1, using [Environment.SetEnvironmentVariable](https://docs.microsoft.com/en-us/dotnet/api/system.environment.setenvironmentvariable?view=netcore-3.1).

The loader will choose a supported version of the browser/runtime from those available, and will crash if it can't find one. However, if you want to test the latest fixes in Canary, the above techniques should work. Let me know if they don't and I can reopen this issue. Thanks!!
