### ISSUE TITLE
When I open a child window in my app's window using NewWindowRequested, document.write cannot write the content to the child window

### ISSUE THREAD

**Issue by ms-yuhara** [MicrosoftEdge/WebViewFeedback#439]
**Description**
When I open a child window in my app's window using NewWindowRequested, document.write cannot write the content to the child window. That occurs only if I handled a NewWindowRequested event and created a new instance of WebView2 to open the page in my app's own window instead of the Edge's window.

The page opens a new window as shown below and writes a string to the contents of the child window with document.write.

```
my_window = window.open("", "mywindow", "status=1,width=350,height=150");
my_window.document.write('<H1>The Popup Window</H1>');
```

**Version**
SDK: 0.9.579-prerelease
Runtime: Confirmed with Beta 86.0.622.15
Framework: WPF, WinForms
OS: Windows 10 2004

**Repro Steps**
1. Extract the attached repro, [SimpleWebView2.zip](https://github.com/MicrosoftEdge/WebViewFeedback/files/5222055/SimpleWebView2.zip)
2. Launch SimpleWebView2.exe and wait for the page to appear
3. Click the [Open Popup Window] link and see whether a child page will be opened properly

Expected result: "The Popup Window" is displayed in the child window (as same result in Edge)
Actual result: The child window is blank and nothing is displayed

- WebView2

![WebView2](https://user-images.githubusercontent.com/38028987/93156921-188dbb80-f744-11ea-9bd9-18627a22dee7.png)

- Edge

![Edge](https://user-images.githubusercontent.com/38028987/93156896-0ca1f980-f744-11ea-92a2-5ed8f39e45ce.png)

**Note:** Any page that simply opens a child window with a URL will work fine with this sample code (e.g. http://files.javascript-coder.com/window-popup/javascript-window-open-example1.html)

**Comment by champnic** [comment]
This is a known issue, and we're tracking the fix in #409. Thanks!
