### ISSUE TITLE
Need support for progress ring (or improved frame events)

### ISSUE THREAD

**Issue by verelpode** [MicrosoftEdge/WebViewFeedback#44]
It's great to see the exciting progress being made with WebView2!  Speaking of progress, am I mistaken in thinking that the current version of WebView2 is missing a way to let apps display a [ProgressRing](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.progressring)?   Apps using WebView2 need the ability to display an indeterminate progress animation in the same manner as how the full Edge app displays a small progress ring animation while a webpage is loading.

I believe the following procedure is the recommended way to do this but it contains a bug:
1. When the [NavigationStarting](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview#add_navigationstarting) event is triggered, the app starts the progress animation.  In the case of UWP, the app can set `Windows.UI.Xaml.Controls.ProgressRing.IsActive` to true.
2. When the [NavigationCompleted](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview#add_navigationcompleted) event is triggered, the app sets `ProgressRing.IsActive` to false.

The bug is that it malfunctions when the webpage contains one or more [inline frames](https://www.w3schools.com/tags/tag_iframe.asp).  The progress ring animation is started but never stopped, thus the animation is left running forever.  The reason why this can happen is because of the following statement in the documentation:

> "For subframes inside WebView, the * **only** * navigation event fired is the NavigationStarting event which gives host the ability to block subframe navigations."
> -- [Navigation events](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview#navigation-events)

Thus when an inline frame is loaded, the NavigationStarting event is triggered and the app starts its progress animation, but the animation remains running infinitely because the NavigationCompleted event is not triggered for inline frames.

I think the aforementioned documentation is out-of-date and needs to be updated because it says frames trigger NavigationStarting but I see there now exists also a [FrameNavigationStarting](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview#add_framenavigationstarting) event.  Thus I'm confused and I would appreciate an improvement in the documentation.

Regardless of whether frames trigger NavigationStarting or FrameNavigationStarting **or both**, in any case there still appears to be no event triggered when the frame is completed, thus no way of stopping the progress animation.  I suggest this solution:

1. If `NavigationStarting` should be invoked for frames, then I suggest adding an **"IsInlineFrame"** property  to [NavigationStartingEventArgs](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2navigationstartingeventargs).
2. Regardless of whether `NavigationStarting` will be invoked for frames, in any case, it would still be advantageous to have an **"IsInlineFrame"** property because it would allow apps to conveniently use the same event handler for both `NavigationStarting` and `FrameNavigationStarting` (both of these events use the same arguments type, that is `IWebView2NavigationStartingEventArgs).`
3. Re choice of naming:  I made it consistent with the description of [<iframe> at w3schools](https://www.w3schools.com/tags/tag_iframe.asp), where it says "inline frame".
4. WebView2 needs an event triggered when frame loading is completed.  This could operate the same as WebView 1:  [Windows.UI.Xaml.Controls.WebView.FrameNavigationCompleted](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.framenavigationcompleted)
5. Alternatively, `NavigationCompleted` could also be invoked when frame loading is completed, but if WebView2 does this, then **"IsInlineFrame"** properties need to be added to both of `NavigationCompleted` and `NavigationStarting`.
6. Make **"FrameId"** properties in `FrameNavigationStarting` and `FrameNavigationCompleted`, in order to permit the app to match up a "Completed" event with the correct corresponding "Starting" event.  Alternatively an integer property that specifies the **count** of frames that are in-progress.  

If no "FrameId" (or count) property exists, the progress animation again malfunctions when the following sequence of events occurs, when WebView2 loads 2 or more frames in parallel:

1. `FrameNavigationStarting` is triggered for frame **F1**.  The app sets `ProgressRing.IsActive` to true.
2. `FrameNavigationStarting` is triggered for frame **F2**.  The app sets `ProgressRing.IsActive` to true.
3. `FrameNavigationCompleted` is triggered for frame **F1**.  The app sets `ProgressRing.IsActive` to false, but this is a bug because frame **F2** is still in-progress.
4. `FrameNavigationCompleted` is triggered for frame **F2**.  The app sets `ProgressRing.IsActive` to false, but this is a bug because `IsActive` was already (prematurely) set to false.

The app can fix the above bug if a "FrameId" property exists.  Alternatively, if you prefer, the `FrameNavigationStarting` and `FrameNavigationCompleted` events could include an integer property that specifies the **count** of frames that are in-progress.   Thus when the count drops to zero, the app knows that it should set `ProgressRing.IsActive` to false.

At first glance, the progress ring issue seems like it should be very simple, but actually it's not so simple when a webpage contains JavaScript and multiple inline frames and the JavaScript may potentially also modify those frames or navigate them to different pages.  That's why I suggest the "FrameId" or count property.

Thanks very much for creating WebView2 as a **component** for developers, not only as the Edge app for end-users.   It is tremendously useful to be able to use such an embedded web component in various apps.

**Comment by verelpode** [comment]
@david-risney
> Tracking loading of frames is a good scenario for adding a frame navigation completed.

Yes please.  For the purpose of tracking activity/progress, it would be helpful to give WebView2 a `FrameNavigationCompleted` event, like how EdgeHTML-based WebView has this event.

> I imagine the app could keep track of the count of outstanding frame navigations if we didn't have a count or frameId property?

True, good point; _theoretically_ the app can increment and decrement its own frame counter field.  However, in my experience, there is often a difference between what works in theory and what works reliably in practice, therefore I favor the extra reliability/robustness of a FrameId property and/or a robust count provided by WebView2.

In my experience, people increment and decrement a counter and _theoretically_ the counter can never become negative, and can never be permanently stuck at 1+, but it happens anyway, despite the theory.  For example, something like the following scenario could break the counter:

1. The `FrameNavigationStarting` event occurs.  The app increments its frame counter from 0 to 1.
2. The [ProcessFailed](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview#add_processfailed) event occurs.  The app recovers by recreating its instance of WebView2.
3. The corresponding `FrameNavigationCompleted` event is never delivered because the process failed.  The frame counter is incorrectly stuck at 1+.

You could reply by saying that the app can fix the bug by simply resetting its frame counter to zero when the `ProcessFailed` event occurs.  OK, let's try it and see what happens:

1. The `FrameNavigationStarting` event occurs.  The app increments its frame counter from 0 to 1.
2. The [ProcessFailed](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview#add_processfailed) event occurs.  The app recovers by recreating its instance of WebView2.
3. The app resets its frame counter to zero in response to `ProcessFailed`.
4. The corresponding `FrameNavigationCompleted` event is delivered even despite the fact that the process failed, because this `FrameNavigationCompleted` event might have been already enqueued or posted before the process failed, and because the `ProcessFailed` event is detected and triggered within the local app process whereas the `FrameNavigationCompleted` event originates in the separate web process.
5. The app responds to `FrameNavigationCompleted` by decrementing its frame counter.  The counter is already 0 thus it becomes -1 thus it is broken.

Thus it's easy to say _"Just reset the counter to zero when ProcessFailed occurs"_, but it's much easier said than done in a real program.  To make matters worse, the above headache-inducing scenario is only a fictional simplified scenario, whereas the real scenario is more complicated because the delivery of `FrameNavigationCompleted` and/or the management of the frame counter may be affected by:
* The app's event handlers for `WebResourceRequested`, `NewWindowRequested`, `PermissionRequested`, `ProcessFailed`, etc.
* The precise timing of when the app sets [IWebView2NavigationStartingEventArgs.Cancel](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2navigationstartingeventargs#put_cancel) to true.
* Whether it's possible for any events to be delivered in an unexpected order.
* Interleaved events:  What happens when other events occur in-between `FrameNavigationStarting` and `FrameNavigationCompleted`.
* Race conditions and other unexpected multitasking quirks.
* And other things.

People tend to say or think, _"Just increment/decrement a counter; it's easy"_, but it ends up being buggy anyway because it's difficult to think of all the corner cases.

I don't know the internal details of WebView2.  Maybe your reply will be that you're already absolutely certain that it's impossible for WebView2 to cause unexpected or out-of-order events, and you're sure that no race conditions exist.  But how can you be certain about this considering that the app and WebView2 are indeed running in parallel in separate processes?  This means race conditions are a very real risk.   Even the most experienced and advanced software engineers still make mistakes with race conditions and headache-inducing parallel-execution bugs.  That's why I favor a more robust solution.

**Comment by champnic** [comment]
@verelpode Both the FrameNavigationStarting and FrameNavigationCompleted event handler args have a [NavigationId](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-538/icorewebview2navigationstartingeventargs#get_navigationid) you should be able to use for this. If this does not work for you, please reopen.
