### ISSUE TITLE
OnCreateEnvironmentCompleted receives 0x80010106 if COM was initilized in multi-thread

### ISSUE THREAD

**Issue by ysc3839** [MicrosoftEdge/WebViewFeedback#447]
**Description**

If COM was initilized in multi-thread mode (using `CoInitializeEx(NULL, COINIT_MULTITHREADED)`), calling `CreateCoreWebView2EnvironmentWithOptions` will receive `0x80010106: Cannot change thread mode after it is set.` in EnvironmentCompletedHandler.
Previous SDK version 0.9.579 does not have such issue.

**Version**
SDK: 0.9.628-prerelease
Runtime: Canary 87.0.641.0
Framework: Win32
OS: Win10 19041.450

**Repro Steps**

Clone [WebView2Samples](https://github.com/MicrosoftEdge/WebView2Samples), change `COINIT_APARTMENTTHREADED` to `COINIT_MULTITHREADED` in https://github.com/MicrosoftEdge/WebView2Samples/blob/0e6587d15e0c50762639146868d7d637d96ae936/SampleApps/WebView2APISample/AppWindow.cpp#L55
And run.

**Screenshots**

**Additional context**

**Comment by champnic** [comment]
WebView2 has never supported multithreaded access, and this new error is a result of us checking for that and communicating it better. You can read more details here:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/threading-model

Thanks!

**Comment by ysc3839** [comment]
Thanks for pointing out my fault.
Can you tell me how to use WebView2 with C++/WinRT in the same Win32 app? Because the WinRT API requires multi-thread apartment.

**Comment by champnic** [comment]
I believe the workaround is to have the WebView2 and WinRT calls on separate threads - following up with the team to confirm and maybe add details.

**Comment by champnic** [comment]
@ysc3839 It sounds like WinRT needs to be COM initialized, but can use an ASTA (which will work with WebView2) instead of an MTA. Can you give that a try?

**Comment by ysc3839** [comment]
I found it's because I'm doing a blocking `wait_for` for a `IAsyncAction`, which checks STA apartment.
https://github.com/microsoft/cppwinrt/blob/c20a75b98e13b247a4ad43536347cd17f883a541/strings/base_coroutine_foundation.h#L70-L72

The WinRT itself works fine with STA apartment.

Thank you again for helping me resolve the issue!

**Comment by champnic** [comment]
Glad you've got it working! Thanks!
