### ISSUE TITLE
Webview2 is not working - windows app

### ISSUE THREAD

**Issue by sbg123** [MicrosoftEdge/WebViewFeedback#450]
I am using WebView2 0.9.628-prerelease in my windows application. 
Microsoft Edge Version 87.0.641.0 (Official build) canary (64-b it) installed in my Windows 10.
Trying to use it with Visual Studio 2019. .Net framework 4.6.2

Debug mode is mixed platform.

I am getting Object Reference error 
this.Controls.Add(this.webView21); in the designer.

One more question. How does this work once used in a production environment where Microsoft Edge canary (64-b it) is NOT installed

**Comment by uwalace** [comment]
For use the webview2 without the Microsoft Edge Canary, you can install the Webview2 Runtime ( https://developer.microsoft.com/pt-br/microsoft-edge/webview2/)

**Comment by cgeier** [comment]
@sbg123 This looks like issue #431. Either use 64-bit (Any CPU with  Prefer 32-bit unchecked or x64) or try the workaround that I posted.

**Comment by champnic** [comment]
Thanks @uwalace and @cgeier for the answers here.
@sbg123 you can also checkout https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution.

We're working on putting together documentation and samples on how to include WebView2 Runtime deployment as part of app install.

If this doesn't answer your question or you are continuing to run into problems after trying the fixes in #431, please let me know. Thanks!
