### ISSUE TITLE
Webview 2 .Net (Windows Form) NullReferenceException

### ISSUE THREAD

**Issue by sbg123** [MicrosoftEdge/WebViewFeedback#464]
I am using Webview 2. Version=0.9.628.0. Visual studio 2019 and .Net framework version is 4.8
I have Microsoft Edge Version 87.0.646.0 (Official build) canary (64-bit) installed in my Windows 10.
I am still getting NullReferenceException

**Comment by IRRDC** [comment]
I can confirm this. this.Controls.Add(this.webViewX); throws the exception. webViewX is not null. I had to go back to 0.9.579 to run the application.

**Comment by cgeier** [comment]
@sbg123, @IRRDC this is most likely issue #431. If using "Any CPU", uncheck "Prefer 32 bit", or use x64 when compiling.

**Comment by IRRDC** [comment]
That works for me.
