### ISSUE TITLE
Access WebView downloads

### ISSUE THREAD

**Issue by maltejur** [MicrosoftEdge/WebViewFeedback#467]
Is there any way to access chrome apis like [ `chrome.downloads`](https://developers.chrome.com/extensions/downloads)? WebView2 does have downloads within the webview, so I was wondering if there was a way to control it.

**Comment by JoshuaWeber** [comment]
Sounds like you are looking for interaction directly with downloads? Could you provide a few more details about your scenario and what you are looking to accomplish?

**Comment by ukandrewc** [comment]
You can get notifications with DevTools Protocol, but you don't have any control.

**Comment by maltejur** [comment]
> Could you provide a few more details about your scenario and what you are looking to accomplish?

I need the user to be able to download a file in the webview, display all the current downloads in another part of the program and execute some code when a download is finished. I already tried using [`WebClient.DownloadFileAsync`](https://docs.microsoft.com/en-us/dotnet/api/system.net.webclient.downloadfileasync) as an alternative, but that is noticeably slower than chrome/edge.

> You can get notifications with DevTools Protocol, but you don't have any control.

That sounds promising. How exactly does that work? I tried this, but it doesn't seem to work
```csharp
private void WebView_CoreWebView2Ready(object sender, EventArgs e)
{
    var evr = webView.CoreWebView2.GetDevToolsProtocolEventReceiver("Page.downloadProgress");
    evr.DevToolsProtocolEventReceived += (object sender, CoreWebView2DevToolsProtocolEventReceivedEventArgs e) =>
    {
        Debug.WriteLine(e.ParameterObjectAsJson);
    };
}
```

**Comment by ukandrewc** [comment]
> but it doesn't seem to work

You have to enable the events for each domain:

`CoreWebView2.CallDevToolsProtocolMethodAsync("Page.enable", "{}"))`

**Comment by maltejur** [comment]
> You have to enable the events for each domain:
> 
> `CoreWebView2.CallDevToolsProtocolMethodAsync("Page.enable", "{}"))`

That does the trick. Thank you for the nice tip with the devtools!
