### ISSUE TITLE
Launch WebView2 separate process in same desktop (HDESK) as the app using WebView2

### ISSUE THREAD

**Issue by verelpode** [MicrosoftEdge/WebViewFeedback#48]
Hello, I would like to request that when Chromium-based WebView2 launches its separate web process, it should launch the separate web process in the **same** desktop ([HDESK](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createdesktopw)) as the app using WebView2, not always in the default desktop.

I suggest that before WebView2 launches the separate web process, it should (if necessary/applicable):
1. Invoke the Win32 [GetThreadDesktop](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getthreaddesktop) function in order to determine which desktop the current app is running inside.  
2. Launch the separate web process in the same desktop as what `GetThreadDesktop` returns, by invoking the [CreateProcessWithTokenW](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createprocesswithtokenw) or [CreateProcessAsUserW](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessasuserw) function.  Set the [STARTUPINFOW.lpDesktop](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/ns-processthreadsapi-startupinfow) field of the struct passed to the `lpStartupInfo` parameter of [CreateProcessWithTokenW](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createprocesswithtokenw) or [CreateProcessAsUserW](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessasuserw).
3. Consider also invoking [GetCurrentProcessToken](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getcurrentprocesstoken) at the same time as [GetThreadDesktop](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getthreaddesktop), in order to help prevent another bug where WebView2 would fail when the app is run as a different user, such as when the app is run as administrator.  i.e. WebView2 should launch the separate web process with the same user/access token and same desktop as the app using WebView2.  

Ideally, WebView2 should also not care (not fail) when Windows Explorer ("explorer.exe") is NOT running in the desktop where the app is running.  For example, if the app using WebView2 runs in a desktop named "TestDesktop1", then the separate web process should be launched in the same desktop "TestDesktop1", and ideally WebView2 shouldn't malfunction if NO instance of explorer.exe is running in "TestDesktop1".

I don't know whether WebView2 will launch the separate web process directly or indirectly via a broker process such as explorer.exe.  The EdgeHTML-based WebView communicates with explorer.exe.   If WebView2 will also communicate with explorer.exe, then the desktop and user/access problems exist.  On the other hand, if WebView2 will simply and directly the launch the separate web process by itself (without going through explorer.exe or other broker process), then I believe the desktop and user/access problems would be correctly handled automatically without any extra work required to make it function correctly.  Whereas if a broker process is used, then I think care needs to be taken to ensure that the separate web process is launched with the same user/access token and same desktop as the app using WebView2.  

In comparison, the EdgeHTML-based WebView has a problem with multiple desktops:  It fails when the app is running in any non-default desktop because EdgeHTML WebView always launches the separate web process in the default desktop.  I have written more details in the bug report [#1384 "WebView launches separate process in wrong desktop (HDESK)"](https://github.com/microsoft/microsoft-ui-xaml/issues/1384)

**Comment by david-risney** [comment]
[WebView2 uses the same process model as Chromium](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview#process-model) so we rely on that existing code in the browser process to create render processes.

I'm trying to use Sysinternals Desktop as suggested in the bug you opened but at least on Win10 I get a new desktop but explorer doesn't start in it. I can get Task Manager to open in it, but everything I run from Task Manager doesn't display (presumably running in the other desktop).

I can say that it works correctly with Win10's notion of virtual desktops although I don't know if that's the same as what you're asking for.

**Comment by verelpode** [comment]
@david-risney
> I'm trying to use Sysinternals Desktop as suggested in the bug you opened but at least on Win10 I get a new desktop but explorer doesn't start in it.

Try this procedure:
1. Double-click "Desktops.exe" to run Sysinternals Desktop.  It appears as a tray icon in the lower right of the screen.
2. Click the Desktops tray icon in the lower right.  It shows a grid of 4 desktops.
3. Click "Press to create desktop 2".  You'll see a new desktop with background image/wallpaper and taskbar at the bottom of the screen.
4. Don't click the Explorer icon in the taskbar because it only partially functions with multiple desktops.  Instead right-click the desktop background image/wallpaper, and click "New" then "Folder".  A new folder icon appears on the desktop.
5. Enter any folder name and press the Enter key to commit the name.
6. Double-click the new folder icon.  A new Explorer window appears.
7. Use the new Explorer window to launch the program that contains WebView2.
8. Also launch WebView2 instances in other desktops, in order to test multiple simultaneous instances of WebView2 in multiple different desktops.

Although Sysinternals Desktop is a little buggy (or not 100% compatible with Win10), nevertheless it serves as a convenient way of testing compatibility with the [CreateDesktop](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createdesktopw) and [SwitchDesktop](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-switchdesktop) functions.

> I can say that it works correctly with Win10's notion of virtual desktops although I don't know if that's the same as what you're asking for.

That's different.  The bug re `HDESK` cannot be reproduced by using the so-called "desktops" feature that is available by clicking the "Task View" icon located immediately right of the Start menu icon in Windows 10 (Pro and Enterprise).  That feature does not create the same kind of "desktop" as what the Win32 [CreateDesktop](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createdesktopw) function creates.  I think the "desktops" in "Task View" operate by hiding and showing windows, not by creating `HDESK` instances.  Thus WebView experiences no problems with multiple "desktops" created via "Task View" because those are not real desktops in the sense of `HDESK`.

> WebView2 uses the same process model as Chromium so we rely on that existing code in the browser process to create render processes.

Is that part of WebView2 finished, meaning: Will that part of WebView2 remain the same as it is currently, or should it be tested again later?  I don't know whether WebView2 is, for example, roughly 50% finished or 90% finished etc, so I don't know whether the result of today's testing remains valid until WebView2 is released.

**Comment by david-risney** [comment]
Yes the process model part of the webview is done. I'll see if I can reproduce the issue on Monday. Thanks.

**Comment by david-risney** [comment]
It looks like this is all working correctly for WebView2. Thanks for the detailed repro instructions! Seems like the issue I was hitting before was something going wrong in explorer.exe separate from any WebView2 related code. Let us know if you find this isn't working well in the future. Thanks

**Comment by verelpode** [comment]
> Seems like the issue I was hitting before was something going wrong in explorer.exe separate from any WebView2 related code.

I guess you experienced this problem:  If an Explorer window is open (left open) in desktop 1, then you switch to desktop 2 and click the Explorer icon in the Windows taskbar at the bottom of the screen, then it tries to show the Explorer window in desktop 1 but this fails because the current desktop is desktop 2 thus any windows in desktop 1 cannot be shown.  Thus the Win10 taskbar isn't fully compatible with multiple `HDESK` desktops but this doesn't matter because `HDESK` desktops aren't intended to be used for that purpose anyway.

> It looks like this is all working correctly for WebView2.

That's great news.  In addition to improving compatibility with kiosk modes, the compatibility with `SwitchDesktop` also means that WebView2 could be displayed in the "Lock Screen" desktop, etc.

But what if **no** explorer.exe process is running in a desktop?  Explorer.exe does not run in the "Lock Screen" desktop, and likewise explorer.exe is unwanted in kiosk mode desktops.  Does WebView2 still work without explorer.exe now and in future?  The [WebView2 Process model documentation](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview#process-model) currently says:
> "WebView2 uses the same process model as the Edge web browser."

The EdgeHTML process model includes some communication with explorer.exe and thus unfortunately EdgeHTML-WebView malfunctions when explorer.exe is not running.  Is this aspect of the WebView2 process model the same or different than the EdgeHTML process model?

To perform testing, you can use this command to terminate explorer.exe before testing WebView2:
```
taskkill /IM explorer.exe /F
```

In order to kill multiple instances of explorer.exe, execute the taskkill command multiple times until it says the process is not found.

IMPORTANT:  An instance of explorer.exe is still running if you can see the Windows taskbar at the bottom of the screen, even if no other Explorer windows are visible.  i.e. the taskbar is produced by explorer.exe.  The taskbar disappears when all explorer.exe instances are terminated.  However, even if the taskbar appears to be gone, a taskbar/Explorer can still exist in another desktop if another instance of explorer.exe is running in that other desktop, thus I suggest running taskkill repeatedly until it says process not found.

Hopefully WebView2 doesn't require explorer.exe now and also never in future, unlike EdgeHTML-WebView.
