### ISSUE TITLE
put_IsFullScreenAllowed(FALSE) doesn't block full-screen mode for F11 key

### ISSUE THREAD

**Issue by wravery** [MicrosoftEdge/WebViewFeedback#56]
I'm setting `IsFullScreenAllowed` to false in the `IWebView2CreateWebViewCompletedHandler` callback, along with a few other settings. It looks something like this:
```c++
bool UpdateSettings(IWebView2WebView* webview)
{
	Microsoft::WRL::ComPtr<IWebView2Settings> settings;

	return SUCCEEDED(webview->get_Settings(&settings))
		&& nullptr != settings
		&& SUCCEEDED(settings->put_AreDefaultScriptDialogsEnabled(FALSE))
		&& SUCCEEDED(settings->put_IsFullscreenAllowed(FALSE))
		&& SUCCEEDED(settings->put_IsStatusBarEnabled(FALSE))
		&& SUCCEEDED(settings->put_AreDevToolsEnabled(FALSE));
}
```
Most of those take effect, but the `F11` shortcut is still enabled and it enters full-screen mode on 1 entire screen, well beyond the bounds of the WebView2 control which is what this setting says it will do if the page tries to enter full-screen mode.

**Comment by david-risney** [comment]
Thanks! We'll look into this.

**Comment by verelpode** [comment]
After looking at the documentation, I don't see any equivalent in WebView2 for the fullscreen event and property in EdgeHTML-WebView:
* Event [Windows.UI.Xaml.Controls.WebView.ContainsFullScreenElementChanged](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.containsfullscreenelementchanged) 
* Property [Windows.UI.Xaml.Controls.WebView.ContainsFullScreenElement](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.containsfullscreenelement)

Can you support the same thing in WebView2?

AFAIK, if my understanding is correct, WebView2 should never implement the fullscreen mode by itself, rather it should notify the app that fullscreen mode is requested, and the app should decide for itself whether to grant or reject to the request, and if the app decides to grant the request, then the app should implement the fullscreen mode by itself.  For example, a UWP app invokes [Windows.UI.ViewManagement.ApplicationView.TryEnterFullScreenMode](https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.applicationview.tryenterfullscreenmode).

Therefore, shouldn't `IWebView2Settings.IsFullscreenAllowed` be removed from WebView2 and replaced with an event and property like how EdgeHTML-WebView works?

Importantly, if WebView2 tries to implement the fullscreen mode by itself (such as by resizing its own Win32 window to fill the entire screen), then it would break compatibility with UWP apps.  

There exists a whole bunch of things that WebView2 should NOT do by itself, rather it should just simply notify the app and let the app handle it.  Fullscreen mode is one of those things that WebView2 shouldn't implement by itself.

**Comment by david-risney** [comment]
@wravery, your original issue should be fixed now. F11 fullscreen is sort of a different feature than the DOM making a particular DOM element fullscreen. We've disabled the F11-style fullscreen feature since it doesn't really make sense for a WebView.

Wrt ContainsFullScreenElement, we'll likely switch to something more aligned with that from the EdgeHtml WebView fullscreen API in a future breaking change.
