### ISSUE TITLE
No display of any modal dialog boxes of any kind (including permission dialog boxes etc)

### ISSUE THREAD

**Issue by verelpode** [MicrosoftEdge/WebViewFeedback#59]
Hello, 
I'd like to request that WebView2 never display any modal dialog boxes of any kind.  Or even better would be if it never displays any extra windows including both modal and non-modal windows.  The reason why I'm bringing this issue to your attention is because various dialog boxes (or other windows) have been a long-running problem for us in previous versions of the web component (EdgeHTML-WebView and especially the older `System.Windows.Controls.WebBrowser`).

Instead of displaying a dialog box, please notify the app (consumer of WebView2) via events and let the app decide what to do in response to the event.  The app can decide for itself whether to display its own dialog box or message in response to events triggered by WebView2.

## Permission dialog boxes

One of the kinds of dialog boxes is dialogs that ask for permission.  I see that WebView2 already has a [PermissionRequested](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview#add_permissionrequested) event.  That's excellent, but for your reference, in EdgeHTML, the corresponding event `Windows.UI.Xaml.Controls.WebView.PermissionRequested` didn't stop WebView from displaying this dialog box when I wanted it to deny access:

![image](https://user-images.githubusercontent.com/32857007/67037931-c0f36400-f11e-11e9-90a3-45627ea230cf.png)

## Users view permission dialog box as a problem or a malfunction

Although it might seem like the permission dialog box is harmless and easily understood, it actually causes a real problem in our environment.  Although the dialog box seems simple to you and I, nevertheless it causes too many users to call or email tech support.  Users don't know whether to click the "Yes" or "No" button, or they don't understand why the dialog box is appearing at all, or they believe that the existence of the dialog box indicates that the software is malfunctioning.  

This doesn't mean they're stupid.  It's not only the end-users who don't understand the dialog box -- I also cannot explain why it appears, despite my technical experience and knowledge.  I simply viewed the same website as the end-users (a website unrelated to audio recording) and EdgeHTML-WebView displayed the microphone permission dialog box but I don't know why.  

I hope that WebView2 won't ever display any dialog boxes, rather it will make any dialog boxes the responsibility of the app to display if necessary.

## WebView shouldn't cause permanent changes to OS settings

Another reason why the permission dialog box causes real problems:  When users click either the "Yes" or "No" button, it permanently changes an OS setting in the computer, meaning that different computers end up with different settings:
* On some computers, users click "Yes", 
* and on some other computers, users click "No",
* and on some other computers, users don't click anything and instead walk away and either abandon the computer or contact tech support for assistance. 

It's very bad when WebView causes different computers to have different settings in the OS, permanently, because this leads to significant debugging/diagnostic and tech support difficulties.  How can we successfully troubleshoot/maintain a thousand different computers when they all end up with different combinations of settings in the OS?

Someone tests something on one computer and then someone else tries to reproduce the same problem on other computer but the computers behave differently because WebView permanently changed the settings in each computer to differing values.  This is a real problem in terms of delivering reliable tech support and maintenance for a large quantity of computers.  Major headaches and troubleshooting delays occur when each computer behaves differently because of different OS settings.

The fact that a XAML Control (in this case WebView) causes permanent changes to OS settings is actually strange, unexpected, problematic behavior.  Thus the permission dialog box isn't as harmless and simple as it may seem at first glance.

## Mandatory permission dialog box to GRANT permission

I realize that for security reasons in UWP/sandboxed apps, when an app sets [IWebView2PermissionRequestedEventArgs.State](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2permissionrequestedeventargs#put_state) to `WEBVIEW2_PERMISSION_STATE_ALLOW`, then the OS may need to display a mandatory permission dialog box, but even in this case, I still think that WebView2 should NOT cause any dialog box to be displayed, rather WebView2 should make it the responsibility of the app to gain the necessary permission from the OS.

Thus apps would be required to perform 2 steps to grant permission:
* Gain the necessary permission from the OS via the app manifest or by invoking a UWP method that displays a permission dialog box.
* Set `IWebView2PermissionRequestedEventArgs.State` to `WEBVIEW2_PERMISSION_STATE_ALLOW`.  This should only take effect if the other/aforementioned step is also performed (either before or after setting `IWebView2PermissionRequestedEventArgs.State`).

## JavaScript dialog boxes

WebView2 has the event [ScriptDialogOpening](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview#add_scriptdialogopening).  After reading the documentation, it's unclear to me whether this event is intended to allow apps to **replace** the dialog box displayed by WebView2 with a dialog box displayed by the app.

Could you please consider allowing apps (consumers of WebView2) to display their own dialog box (or replacement GUI) and suppress the dialog box displayed by WebView2?   Or if this is already possible, could you add a few sentences to the documentation to explain how to do that?

## The print dialog/window

The print dialog is another example of the fact that **every** kind of dialog and window displayed by WebView/2 causes significant problems in our environment.  It's a substantial problem if we're unable to control whether WebView allows or denies users or scripts to display the print dialog/window.  Sometimes it causes a security breach if users are able to display the print dialog, especially because virtual printers may print to a file and therefore show a "Save As" dialog that lets users see the file system.  See also https://github.com/MicrosoftEdge/WebViewFeedback/issues/42

## Non-modal windows

I also think that WebView2 should never create any additional windows in the app, including modal and non-modal windows.  For example, consider the event [NewWindowRequested](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview3#add_newwindowrequested).  Currently, by default, WebView2 creates a new window by itself unless the app suppresses it by setting `IWebView2NewWindowRequestedEventArgs.Handled`.   Admittedly I can't complain because it already provides the ability that we need, but personally if it was my decision, I'd change the default behavior to never create any windows.

I think it's problematic when WebView2 creates windows because it creates them at the Win32 layer which would be OK in a Win32 app, but WebView2 will be used in UWP apps.  When WebView2 creates windows at the Win32 layer, these windows are missing a corresponding UWP wrapper/layer (`Windows.UI.Core.CoreWindow`), which is a strange situation in a UWP app, therefore personally I'd favor a rule of never creating windows or dialog boxes in WebView2.
  
## Multitasking problems when WebView dialogs are displayed

Especially in networked software such as ours, or other multitasking software, things can happen at any time.  For example, a message can arrive via the internet at a time when WebView is displaying a modal dialog box.  Likewise a C# async task can complete its job at a time when WebView is displaying a modal dialog box.   This multitasking can cause a displayed modal dialog to become out-of-date or incorrect _before_ the user clicks any button to dismiss the modal dialog.    

Thus the app needs the ability to close/cancel any modal dialogs at any time, without requiring the user to click a button in the dialog.  However if the modal dialog is displayed by WebView2, then WebView2 might not provide any support for checking whether a dialog is displayed nor closing it programmatically.  One possible solution is to make a "CloseDialogs" method in WebView2 but I dislike this idea and I believe the better solution is to make WebView2 never display any dialogs.

Also consider the case where the WebView instance/control is disposed (or when the app needs to exit) at a time when WebView has a modal dialog onscreen -- this scenario needs to be tested to check whether it malfunctions, but again the better solution is to make WebView never display any modal dialogs.

In my experience with WebView and the older WebBrowser, any dialogs and extra windows displayed by WebView end up causing trouble.  Not only do they cause trouble, they're also unnecessary because any necessary dialogs can be displayed by the app instead of WebView.

## Expected/requested behavior

1. WebView2 should never display any modal dialog boxes of any kind.  Instead of displaying a dialog, notify the app via an event and let the app decide for itself what to do in response to the event.
2. Setting `IWebView2PermissionRequestedEventArgs.State` to `WEBVIEW2_PERMISSION_STATE_ALLOW` shouldn't cause a permission dialog box to be displayed.  Instead WebView2 should make it the responsibility of the app to gain the necessary permission from the OS as a separate step before or after setting `IWebView2PermissionRequestedEventArgs.State` to `WEBVIEW2_PERMISSION_STATE_ALLOW`.
3. The event [ScriptDialogOpening](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview#add_scriptdialogopening) should allow apps to to display their own dialog box (or replacement GUI) and suppress the dialog box displayed by WebView2.
4. Ideally also don't create any non-modal windows (re `NewWindowRequested`).
5. WebView2 should not directly or indirectly cause any permanent changes to OS settings such as permissions.
6. Apps should be able to enable or disable the print dialog in WebView2.  Or even better would be if WebView2 gives apps enough functionality to replace the print dialog with the app's own print dialog.

## Relevant OS settings

![image](https://user-images.githubusercontent.com/32857007/67038012-e54f4080-f11e-11e9-8d0c-f2e95b00799a.png)

![image](https://user-images.githubusercontent.com/32857007/67038037-f304c600-f11e-11e9-9bcb-0d606a9b42d4.png)

## See also

Re permission dialog appearing with EdgeHTML-WebView-for-WPF:  
https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/191

**Comment by verelpode** [comment]
Continuing this windowing topic, here are 2 more Win32 windows (`HWND`) that WebView2 should never create:

# Fullscreen mode
Fullscreen mode should be implemented by the app that uses WebView2, not by WebView2 itself.  I believe that the Win32 WebView2 layer should _never_ create a fullscreen window and should _never_ try to resize its preexisting `HWND` to fill the entire screen, because this behavior breaks compatibility with UWP apps.  The Win32 WebView2 instance should _never_ exceed the bounding rectangle/box of the WinUI/XAML WebView2 Control, even when fullscreen mode is requested.  

Not even the WinUI/XAML WebView2 Control should implement the fullscreen mode by itself, rather it should notify the app and let the app do it.  This sequence of actions should occur:

1. The HTML webpage or JavaScript requests fullscreen mode.
2. The Win32 WebView2 triggers an event in order to notify the next layer (the WinUI/XAML WebView2 Control).
3. The WinUI/XAML WebView2 Control triggers an event in order to notify the app that fullscreen mode is requested.
4. The app decides to either grant or reject the fullscreen request.
5. If the app decides to grant the fullscreen request, then it invokes [Windows.UI.ViewManagement.ApplicationView.TryEnterFullScreenMode](https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.applicationview.tryenterfullscreenmode).
6. Importantly, in addition to invoking `ApplicationView.TryEnterFullScreenMode`, the app would typically also change some of its own GUI elements, such as hiding a toolbar that controls the WebView2 element, or otherwise presenting a suitable fullscreen appearance for the end-user.  The app may also resize the WebView2 Control at this time.  Note this way allows the app to customize the appearance and behavior of the fullscreen mode in whatever manner it needs to.
7. Later, when the Win32 WebView2 layer triggers an event to notify the next layer that fullscreen mode should end, the WinUI/XAML layer passes it on to the app, and the app invokes [Windows.UI.ViewManagement.ApplicationView.ExitFullScreenMode](https://docs.microsoft.com/en-us/uwp/api/windows.ui.viewmanagement.applicationview.exitfullscreenmode), and adjusts the app's GUI to restore a toolbar etc to the normal non-fullscreen mode state.

Currently, after looking at the documentation, I don't see any equivalent in WebView2 for the fullscreen event and property in EdgeHTML-WebView:
* Event [Windows.UI.Xaml.Controls.WebView.ContainsFullScreenElementChanged](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.containsfullscreenelementchanged) 
* Property [Windows.UI.Xaml.Controls.WebView.ContainsFullScreenElement](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.containsfullscreenelement)

Thus I suggest that WebView2 handle the fullscreen mode in much the same manner as the preexisting EdgeHTML-WebView does, with an event that notifies the app to handle the fullscreen request.  This means [IWebView2Settings.IsFullscreenAllowed](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2settings#get_isfullscreenallowed) would be removed and replaced.

See also:  Issue https://github.com/MicrosoftEdge/WebViewFeedback/issues/56


# Context menus (right-click)
Context menus (right-click) are also a windowing issue because context menus are typically implemented with the help of an underlying Win32 window (`HWND`).  Thus context menus are also windows, even though end-users don't think of them as windows.

I believe that the Win32 WebView2 component/layer should never create a context menu when the user right-clicks, because this would be poorly compatible with WinUI/XAML/UWP apps.  For example, the appearance/theme/colors of a context menu created in the Win32 layer don't match the appearance of context menus created in the WinUI/XAML layer, therefore the Win32 WebView2 layer shouldn't create any context menus.

In my opinion, the WinUI/XAML WebView2 Control also shouldn't create the context menu, rather it should notify the app via an event and let the app decide what to do.

This sequence of actions should occur:
1. The end-user right-clicks in the webpage.
2. Win32 WebView2 doesn't display any context menu. Instead it triggers an event in order to notify the next layer (the WinUI/XAML WebView Control).
3. The WinUI/XAML WebView Control doesn't display any context menu.  It just passes the event along to the app.
4. The app can optionally decide to ignore the event, meaning disable the context menu ability.  If necessary, WebView2 may require the app to set a `Handled` property (in the event args) to true.
5. The app can optionally decide to display its own customized context menu by using [Windows.UI.Xaml.Controls.MenuFlyout](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.menuflyout).

Similarly, apps need control over the keyboard accelerators/hotkeys.  In our environment, it's a major problem if users are able to use either a context menu or hotkey to display a "Save As" or "Print" dialog.  Our clients impress upon us the importance of the need to lockdown/secure the web component and prevent users from escaping this sandbox via context menus or hotkeys in WebView2 that show extra dialogs or windows such as "Save As" or "Print" or fullscreen mode.

See also:  Issue https://github.com/MicrosoftEdge/WebViewFeedback/issues/57

# Remove all extra windows, dialogs, context menus, toolbars 
**ANY** extra windows, dialogs, context menus, or toolbars displayed by WebView2 usually cause big trouble for us.   I wish that WebView2 would do _less_ by itself and instead hand-over various actions to the app via events, in order to give apps more control and customization ability.

Furthermore, any extra Win32 windows or pseudo-windows displayed by WebView2 typically break compatibility with UWP apps, or at least they produce poor compatibility with UWP, such as: 

* Mismatching appearance/theme of GUI elements created by Win32 versus by UWP/WinUI.
* Inconsistent behavior when the same thing behaves somewhat differently in Win32 versus UWP/WinUI when WebView2 implements it at the Win32 layer instead of passing it along to the next layer.
* Incompatibility with automation/accessibility (screen readers etc).
* Lack of correct or consistent behavior when a mobile/tablet/touchscreen device is used instead of a mouse.
* Violation of UWP security rules (the UWP sandbox) such as when WebView2 displays a Win32-based "Save As" or "Print" dialog in a UWP app instead of using the UWP/WinUI implementations of these dialogs.

**Comment by david-risney** [comment]
Hi! A lot of your feedback is disagreement with our defaults for WebView2. Generally we're starting with the code and behavior of the new Edge browser and adding WebView2 features to allow the WebView2 end developer to interact, customize or replace browser or web platform features as our customers require. By default as a baseline WebView2 acts similar to the browser so the end developer doesn't have to understand and use every feature of WebView2 in order to have a working WebView2. Without reading about every feature the end developer can assume that WebView2 will act consistent with the web.

 * **Permission dialogs**: By default WebView2 shows a dialog asking the end user for permission and the end developer can override with the PermissionRequested event. The EdgeHtml WebView always ran in the context of a UWP app and the OS would show permission prompts (like the one you have a screenshot of) separate from what EdgeHtml could control for accessing things like the camera or mic.
 * **OS settings**: AFAIK the new Edge browser does not change OS settings like you describe. If we need to run in the context of a UWP app and the OS prompts the end user for permission for mic etc, there's not much we can do about that. Otherwise, some end user responses to prompts (like permissions) are cached per user data folder in the new Edge browser / WebView2. Generally any state the new Edge browser / WebView2 needs is stored in the user data folder.
 * **Mandatory permission dialog box**: IIRC the OS prompts the end user to allow the app to use the camera (for example) when we attempt to use the API to access the camera. I don't think we can separate permission prompts from API use.
 * **JavaScript dialogs**: Yes you can use ScriptDialogOpening to replace JavaScript dialogs. The documentation is not clear. I'll open a separate GH issue for that.
 * **Print dialogs**: Yes looks like we already have a feature request for this that you link #42. As mentioned earlier we're starting with the browser's existing behavior and modifying that. So any issue with replacing particular dialogs is each its own feature request.
 * **Non-modal windows**: Yes you can use NewWindowRequest as you mention. Our defaults for WebView2 don't match the behavior you want but hopefully we can via feature requests be able to support your scenario with customization of the WebView2 via properties / event handlers etc. Yes how we create new windows will need to work differently in UWP.
 * **Multitasking when WebView dialogs are displayed**: I'll open a separate GH issue for this. We should ensure that the WebView can behave appropriately when its methods are used while its showing a dialog. This likely depends on how the different dialogs are implemented and will vary based on the dialog.
 * **Fullscreen**: The implementation of fullscreen will be updated to work correctly in UWP apps. I expect we'll need the event etc like we had with the EdgeHtml WebView to support that. Issue #56 is for the fullscreen mode browser feature which is separate from the fullscreen DOM API.
 * **Context-menus**: In the short term you'll be able to disable context menus. In the long term we'll have a more complicated API to support customizing context menus and / or drawing them yourself.
 * **Remove all extra windows, dialogs, context menus, toolbars** & **Web View not Web Browser**: As mentioned previously the default for WebView2 is the existing new Edge browser's default code. By default the WebView2 acts like the browser and we add features to allow you to customize that as required.

**Comment by verelpode** [comment]
@david-risney 
> Generally we're starting with the code and behavior of the new Edge browser  ..... By default as a baseline WebView2 acts similar to the browser 

That's a major problem for most developers who will want to use WebView2.  That concept was the concept/principle/idea for WPF's Control named "WebBrowser" (`System.Windows.Controls.WebBrowser`).  My understanding is that Microsoft cancelled this concept of browser-in-a-GUI-control when Microsoft released `Windows.UI.Xaml.Controls.WebView` as the successor of `System.Windows.Controls.WebBrowser`, hence the name change.  The change of name from "WebBrowser" to "WebView" nicely reflected the change of concept.

The browser-like behavior of WPF `WebBrowser` made life difficult for many developers trying to use `WebBrowser`, who were forced to use messy undocumented low-level hacks to switch off or override the browser-like behavior of `WebBrowser`.  Thus when `WebView` was released, it was a big relief to see that the browser-like behavior was mostly eliminated by default.  I think many developers would view it as a step backwards if WebView2 reverts to the concept of WPF `WebBrowser`.

In my opinion, Microsoft made the right decision to cancel the concept of browser-in-a-GUI-control and this concept should remain cancelled, not be resurrected in WebView2.  According to Microsoft's decisions, EdgeHTML-WebView isn't a web browser and shouldn't be a web browser, and likewise WebView2 shouldn't be a web browser either.

**Comment by verelpode** [comment]
@david-risney -- I don't mean to make it look like I'm ignoring or disregarding the rest of your message and points.  It's good stuff, good reply, thanks!  I just can't work further on web stuff today, but I'll return to web work tomorrow or next week.

**Comment by david-risney** [comment]
No problem =). I appreciate you feel strongly about WebBrowser vs WebView. But hopefully in the long run it shouldn't make a large difference.

We have default settings for the WebView but provide the end developer with the ability to customize the WebView features as required. None of our customers agree on what subset of browser and web platform features are appropriate for a WebView which is why we provide defaults with customization. Some customers want all of the browser behavior and all customers want some of the browser behavior. Everyone knows how the browser acts and assumes that our control behaves in the same way as the browser for the features they don't know or care about. Accordingly we start with mostly browser behavior and allow end developers to customize on top of that.

What you describe of EdgeHtml WebView was more of a practical issue stemming from the architecture of the previous Edge browser than a conscious choice on our part. We had many customers who wanted more browser features than what the WebView supported but because of the browser and WebView architecture we had to re-implement those features making it difficult and slow going.

**Comment by verelpode** [comment]
@david-risney
If possible, I'm trying to help make your jobs easier, faster, more successful.  Win-win for everyone.  Hopefully I can help achieve a win-win result.

I understand your point:  If WebView2 allows me to configure its settings in the manner that I need (actually the manner that our customers need), then I'm not negatively impacted by the default settings/behavior and can't complain.  

Yes that's a good point, but I am still negatively impacted if a default behavior is practically impossible or excessively difficult or time-consuming for the WebView2 team to implement reliably without ongoing bugs and dysfunctions and maintainence, and causes new versions of WebView2 to be delayed, and/or causes WebView2 to be buggy even when the settings are changed to non-default values (complexity+bugs in a problematic default behavior sometimes spread and creep into other behaviors even when the settings are changed to non-default values).

A specific example:  Re the event [NewWindowRequested](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview3#add_newwindowrequested), my understanding is that the default behavior is that the Win32 WebView2 component creates a new Win32 window by itself at the Win32 layer.  This default behavior seems like it could be one of these cases of being practically impossible or excessively difficult or time-consuming for the WebView2 team to implement reliably.  

Not only is it too difficult, it's also unnecessary, unwanted by nearly everyone (AFAIK), and a waste of the WebView2 team's time and energy to support it.  In the past, the behavior of creating additional windows (AKA popups) severely bothered literally _millions_ of end-users around the world, with every web browser in every OS in every country.  Popups were so notorious that they have even been depicted in various movies.  Negatively depicted, of course.

Therefore, perhaps it'd be good to reconsider whether the default behavior of WebView2 should be such a notorious behavior that was already cancelled by every web browser manufacturer years ago.

The default behavior of the full Edge browser app is:
![image](https://user-images.githubusercontent.com/32857007/67581496-66728d00-f748-11e9-95df-c0953cb787ef.png)

The fact that it says "Security" is important.  Popups are a security issue.  It is recommended practice to make default settings be the secure settings, but if WebView2 creates new windows by default, then it would be **defaulting to the insecure setting**, against the recommended practice.

When not blocked, Edge opens popups in new tabs, not new windows.

Internet Explorer's settings were:
![image](https://user-images.githubusercontent.com/32857007/67581534-75593f80-f748-11e9-9242-ef34f5c11af2.png)

Nobody wants popups opening in new windows, therefore why should the default behavior of WebView2 be new windows?  Why expend resources to implement and maintain something that severely bothered millions of users in the past?

If WebView2 will create new windows anyway, despite nearly everyone hating this behavior, and despite the recommended practice being to default to secure settings, then I believe that most likely it would only function correctly if the WinUI/XAML WebView2 layer creates an instance of [Windows.UI.WindowManagement.AppWindow](https://docs.microsoft.com/en-us/uwp/api/windows.ui.windowmanagement.appwindow) _instead of_ the Win32 WebView2 component trying to create the new window by itself at the Win32 layer.  However this proposed solution still involves technical difficulties, thus personally I believe the best solution is to block/ignore popups by default and leave it to app developers to handle the `NewWindowRequested` event in the manner that is correct for their particular app (a manner that is different for each different app).

**Comment by verelpode** [comment]
By the way, I do realize that a possible answer is:
_"Although opening popups in tabs may be the most common requirement, not every customer makes [a tab GUI](https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/tabview) in their app when they use WebView, therefore not every customer wants popups to open in tabs."_

That's us!  We also support customers who don't want any tabs, as an exception to the usual preference for tabs.   However, even in this case where no tab GUI is created, our customers still don't want popups to open in new windows.  They expressed very clearly that it's essential for the content of popup webpages to be displayed (some enterprise websites use popups), but the popups shouldn't be opened in new windows nor tabs.  Thus we developed a GUI design that displays popup content without new windows nor tabs.  Practically nobody wants popups opening in new windows.

The popups situation is actually good news for the WebView2 team because skipping new window creation means less work and fewer hassles for the WebView2 team, and faster release of WebView2 / fewer delays.

**Comment by verelpode** [comment]
I remembered another example:
If the Win32 WebView2 layer displays its own Win32 modal dialog-windows, these Win32 dialogs will fail to work with the "Back" button / CloseButton API when WebView2 is used in UWP apps.  The ["Dialog controls" article](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs-and-flyouts/dialogs) says:

> CloseButton - Required - Represents the safe, nondestructive action that enables the user to exit the dialog. Appears as the rightmost button.
> ...
> Every dialog should contain a safe, nondestructive action button that enables the user to confidently exit the dialog.
> Use the ContentDialog.CloseButton API to create this button. This allows you to create the right user experience for all inputs including mouse, keyboard, touch, and gamepad. This experience will happen when:
> 1. The user clicks or taps on the CloseButton 
> 2. The user presses the system back button 
> 3. The user presses the ESC button on the keyboard 
> 4. The user presses Gamepad B 

See also:
* `Windows.UI.Core.CoreWindowDialog.BackButtonCommand`
* `Windows.UI.Core.CoreWindowDialog.CancelCommandIndex`
* `Windows.UI.Xaml.Controls.ContentDialog.CloseButtonCommand`

This CloseButton API issue is one of an endless rabbit hole of problems caused by the Win32 WebView2 layer displaying its own Win32 dialogs, windows, pseudo-windows, menus.

Reaching the end of this rabbit hole (fixing all those problems) is an **impossibly difficult task**, even for the smartest and most experienced engineers in Microsoft.  The only reliable way to fix it is to stop doing it.

**Comment by david-risney** [comment]
We don't have a general mechanism to prevent all dialogs available to us. We have the browser's behavior and are adding APIs on top of that. We will work to ensure we can address the issues you describe.

>  if a default behavior is practically impossible or excessively difficult or time-consuming for the WebView2 team to implement

WebView2 is built on top of the new Edge browser and so we are starting with the browser's behavior. It is more work for us to add a NewWindowRequested event to supress new DOM windows and more after that to allow end developers to connect the new DOM window up to a particular WebView2.

> it's also unnecessary, unwanted by nearly everyone (AFAIK), and a waste of the WebView2 team's time and energy to support it

We have customers for the 3 behaviors (WebView2 owned new window, supress new windows, app owned new window)

> notorious behavior that was already cancelled by every web browser manufacturer years ago

We get the browser's behavior wrt preventing popups. The browser employs a heuristic to determine if user interaction was used to spawn new DOM windows that also applies to WebView2. The only difference from the browser and WebView2's default new DOM windows behavior is that WebView2's open in a new OS window instead of a browser tab. This is the same behavior as PWAs running in the browser.

> nevertheless delivering an improved design is still a win

It was a big problem for us delivering features to our customers.

**Comment by verelpode** [comment]
I heard some excellent news!  I heard that the new or current plan is that WebView2 won't display Win32 dialogs/windows/menus/etc in WinUI or UWP apps.  For context menus, the plan is that the underlying Win32 WebView2 component will send a description of the menu items to the WinUI side of WebView2, and then the WinUI side will show a WinUI context menu with those menu items.  Thus the problematic old Win32 context menus are eliminated and replaced by modern WinUI context menus.

This sounds like great news, in my opinion.  I think this is an excellent and smart plan and I'm relieved to hear about it.  This plan eliminates the problem of Microsoft not possessing sufficient resources to fix all problems caused by the Win32 side of WebView2 displaying Win32 GUI in WinUI/UWP apps.  

Microsoft is a big company but some things are still too difficult for Microsoft to achieve.  The idea of WebView2 displaying Win32 GUI was an example of an impossibly difficult task that Microsoft could not achieve (even with the best engineers in the world), but this problem is now GONE thanks to the excellent plan of displaying the GUI in the WinUI side of WebView2 instead of displaying it in the Win32 side of WebView2.  Wonderful!  I'm looking forward to the next version of WebView2.
