### ISSUE TITLE
Add type in-param for postMessage APIs

### ISSUE THREAD

**Issue by enricogior** [MicrosoftEdge/WebViewFeedback#60]
Hi!
PowerToys is migrating from the Win32WebView control to the new (and awesome!) WebView2 control. In our scenario, the host is communicating with the WW2 control sending and receiving two types of messages:
 - messages that the host receives from the PowerToys modules, they are already in JSON format and contain the description of the module settings that will be rendered by the WW2  control.
 - control messages between the host and the WW2 control to handles different scenarios, like informing the WW2 control that the user has clicked on the Settings window close button so that the control can check if there are unsaved changes and prompt the user for confirmation to close/save/cancel.

We can achieve all we need using `IWebView2WebView::PostWebMessageAsJSON` and `window.chrome.webview.postMessage` with one caveat: each message the host sends/receives needs two fields, one to describe the message type and one to contain the message data.
When the host receives the JSON from a PowerToys module, it has to allocate memory to encapsulate that JSON in a new JSON as the message data.

It would be better for us to avoid that extra processing/memory allocation if we could call `PostWebMessageAsJSON` and `postMessage` passing two arguments, one would be the message type and the other the message data.

In our case the`PostWebMessageAsJSON` message type can be just a string, but it would also be OK if it's a JSON as well.

Looking forward to fully integrate the new control into PowerToys!
Thank you.

**Comment by liminzhu** [comment]
Hey @enricogior we're excited to work with ya and PowerToys! 

To make sure I understand this, you want something like `PostWebMessageAsJson(LPCWSTR messageType, LPCWSTR webMessageAsJson)`? I might be misunderstanding things, but is it possible to just capture the type info in the JSON object itself? Since there still has to be some memory allocation for the type info and type handling logic somewhere, I'm not sure I see much difference the additional type param would make.

**Comment by enricogior** [comment]
Hi @liminzhu
yes, `PostWebMessageAsJson(LPCWSTR messageType, LPCWSTR webMessageAsJson)` is what I would like to use.

In our scenario we send two types of messages from/to the host to/from the WebView2 control:
 - one type is a JSON that the host process receives from an external component. In this case the host process doesn't parse the JSON, it simply forwards it to the WebView2 control.
 - the other type is a control message that in turn has multiple sub-types. These messages are generated directly by the host process.

I need a way to distinguish those two high level message types in some way.
As you said, it is possible to capture the info in the JSON object itself, that is simple to do when sending the control messages generated by the host process itself, but when the host processe receives a JSON created by a component that doesn't know/care about the message type, it would have to allocated a new JSON and add the original JSON as data of the new JSON.

Asking to add a second argument to `PostWebMessageAsJson` is for the same reason why APIs have multiple arguments instead of grouping all arguments into one structure, so the caller doesn't have to allocate the structure every times it calls the API and it can pass the same data it receives from other components.

I would like to have the the same change for `window.chrome.webview.postMessage`, since it also receives the JSON from our React component and it behaves as a broker to the host but it also needs to add the message type.

This is also valid for `PostWebMessageAsString` since it would be weird to have to allocate a string that contains both the message type and the message data.

In fact, if the proposed change to `PostWebMessageAsJson` is not acceptable my plan would be to use `PostWebMessageAsJson` only for one type of message and use `PostWebMessageAsString` for the control messages and in this case the need of a second argument for the message type is a must.
Also in this case I would need to be able to specify two different message handlers in the HTML code, one for the messages from `PostWebMessageAsJson` and one for the messages from `PostWebMessageAsString` or is it already possible?

I hope I have explained better our scenario and the need of a dedicated second argument.
Thank you.

**Comment by liminzhu** [comment]
Ah I see where you're coming from. While I understand your argument, the concern on my side is that our postMessage API (both on the host side and web side) is modeled after the corresponding [Web API](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) behavior, which doesn't have type in-param, and the JSON type is supposed to be a catch-all that encapsulate the entire message including type, timestamp, content, etc. Adding a specific type in-param to the postMessage API therefore seems a little arbitrary for a general-purpose API.

I take it that you control the JSON message generated by host process but not the external one. What about adding a `_powertoysControlType` field (or something your external messages shouldn't contain assuming you have some knowledge of how those look like) to your host process message? And one the web side you can distinguish them easily by checking

```js
if (message._powertoysControlType) {
  //host message
}
else {
  //control message
}
```

**Comment by liminzhu** [comment]
Also changing the title to make the ask more explicit

**Comment by enricogior** [comment]
Hi @liminzhu 
thank you for the detailed explanation and the suggestion. I understand the reasoning behind the current design and I agree with it. We will make the necessary changes on our side to encapsulate the message type in the JSON.
Thanks!

**Comment by liminzhu** [comment]
Thanks for understanding. Feel free to open other issues as you make progress prototyping/developing :).
