### ISSUE TITLE
Multitasking problems when WebView dialogs are displayed

### ISSUE THREAD

**Issue by david-risney** [MicrosoftEdge/WebViewFeedback#61]
(from #59 )

Especially in networked software such as ours, or other multitasking software, things can happen at any time. For example, a message can arrive via the internet at a time when WebView is displaying a modal dialog box. Likewise a C# async task can complete its job at a time when WebView is displaying a modal dialog box. This multitasking can cause a displayed modal dialog to become out-of-date or incorrect before the user clicks any button to dismiss the modal dialog.

Thus the app needs the ability to close/cancel any modal dialogs at any time, without requiring the user to click a button in the dialog. However if the modal dialog is displayed by WebView2, then WebView2 might not provide any support for checking whether a dialog is displayed nor closing it programmatically. One possible solution is to make a "CloseDialogs" method in WebView2 but I dislike this idea and I believe the better solution is to make WebView2 never display any dialogs.

Also consider the case where the WebView instance/control is disposed (or when the app needs to exit) at a time when WebView has a modal dialog onscreen -- this scenario needs to be tested to check whether it malfunctions, but again the better solution is to make WebView never display any modal dialogs.

In my experience with WebView and the older WebBrowser, any dialogs and extra windows displayed by WebView end up causing trouble. Not only do they cause trouble, they're also unnecessary because any necessary dialogs can be displayed by the app instead of WebView

**Comment by champnic** [comment]
@verelpode I believe we've mostly removed modal dialog boxes for most things. If you find this is still an issue for one of your user scenarios please reopen this issue with details and we'll see what we can do to fix it. Thanks!
