### ISSUE TITLE
JavaScript dialog boxes documentation unclear

### ISSUE THREAD

**Issue by david-risney** [MicrosoftEdge/WebViewFeedback#62]
(from #59 )
WebView2 has the event ScriptDialogOpening. After reading the documentation, it's unclear to me whether this event is intended to allow apps to replace the dialog box displayed by WebView2 with a dialog box displayed by the app.

Could you please consider allowing apps (consumers of WebView2) to display their own dialog box (or replacement GUI) and suppress the dialog box displayed by WebView2? Or if this is already possible, could you add a few sentences to the documentation to explain how to do that?

**Comment by champnic** [comment]
Docs have been updated: https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-538/icorewebview2#add_scriptdialogopening
