### ISSUE TITLE
IE Mode (Question)

### ISSUE THREAD

**Issue by christianbain** [MicrosoftEdge/WebViewFeedback#67]
Is IE mode supported?  Can the GPO settings be implemented with a site list? If not, are there any plans to support this?

Thanks.

**Comment by david-risney** [comment]
Great questions! We should document these.
 * IE mode is not yet supported. We can work on this in the future although it is a lot of work so it will be good to understand how it impacts you. Do you need to use IE mode?
 * Policy set for the browser is also applied to all WebView2 instances. Will this work for you?

Thanks!

**Comment by christianbain** [comment]
David - Thanks for the response.

- IE Mode - unfortunately, yes.  We still have quite a few legacy applications that target IE 9-11.  They are slowly being modernized, but since Microsoft announced GA for Edge Chromium we would like to build off of that.

I work for a large retailer, and we like to control things like the address bar for certain workstations in the stores.  This code sample shows how simple it is to do that, but IE mode is a requirement.

Thanks!

**Comment by champnic** [comment]
@christianbain It's unlikely we'll get to IE mode for a while, if at all. I'm not sure what your whole scenario is, but have you considered using building an Extension for Edge? Or it may be possible to switch between the WebView2 control for normal content, and the older [WebBrowser ](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.webbrowser?view=netcore-3.1)control for IE content?

**Comment by champnic** [comment]
I've confirmed with the team that IE mode in WebView2 is not in plan to be supported. We do hope to make a sample in the future that demonstrates an app switching between WebBrowser (IE/Trident) and WebView2 (Edge) for legacy support. Thanks!
