### ISSUE TITLE
Support for printing content of a webview.

### ISSUE THREAD

**Issue by mobiletonster** [MicrosoftEdge/WebViewFeedback#7]
Unlike WebView(EDGEhtml), please, please support printing of contents of a webview. All the crazy gyrations needed to print webview content in a UWP application today doesn't work well.

Thanks for your consideration.

**Comment by lingamy** [comment]
Thanks for your feedback. You can use [CapturePreview](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview#capturepreview) to capture an image of what WebView is displaying. Will that work for your scenario?

**Comment by mobiletonster** [comment]
Thanks for the suggestion, but no it doesn’t work well, especially if it is a multipage document, the CapturePreview becomes cumbersome and often doesn’t look very good.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by lingamy** [comment]
Thanks for providing additional details. We'll look into how to meet the requirement for your scenario.

**Comment by dianaqu** [comment]
Hey @mobiletonster ,

I'm the developer looking into this feature request. Just trying to get more information from you. Can you tell me more about what you need this feature for? You mentioned Spartan WebView printing support which was complicated to hook up to UWP/WinRT printing support, do you mean a similar functionality to hook up to UWP printing APIs?

Thank you!

**Comment by mobiletonster** [comment]
Yes, thank you very much for looking in to this feature. We build an application (UWP) which displays content formatted in HTML. As part of this app, we allow users to annotate and highlight, add notes, tags, etc. to the content for study purposes. The users often want to print the content along with their annotations. We use the webview control to display this content and would love to be able to print the content directly from the webview control as it is displayed on the screen. Today, we export the html, css, etc. to a local file on disk and invoke the default web browser then invoke a print command via injected Javascript...problem is, it only works part of the time and isn't always as precise as what we display within the application. Printing directly from UWP is currently very cumbersome and rarely works well.

If you would like to try the app, download Gospel Library from the Microsoft Store and try it out. 

Thanks.

**Comment by liminzhu** [comment]
Thanks for the context @mobiletonster ! 

> Today, we export the html, css, etc. to a local file on disk and invoke the default web browser then invoke a print command via injected Javascript...

If you don't mind me asking, why are you going through this? Would injecting a script to WebView directly to invoke `window.print` work for you?

**Comment by mobiletonster** [comment]
> Thanks for the context @mobiletonster !
> 
> > Today, we export the html, css, etc. to a local file on disk and invoke the default web browser then invoke a print command via injected Javascript...
> 
> If you don't mind me asking, why are you going through this? Would injecting a script to WebView directly to invoke `window.print` work for you?

Currently, the UWP or EdgeHTML WebView provides no printing support. invoking window.print doesn't actually do anything in the WebView control. Worse yet, in later version of Edge, you can no longer export your HTML/CSS to the file system and invoke a window.print due to security updates. Chrome, Firefox do still support it, so if your default browser is not Edge, it will still work. The print capabilities of the browsers are already very good (and support @media print CSS directives). To reproduce all of that capability ourselves in our app is not practical. We would prefer to access the native print capabilities of the new (or even existing) Edge browser and invoke it directly from our app/WebView control...in otherwords, be able to print what is currently loaded in the WebView control....just as the browser would do.

Thanks.

**Comment by mobiletonster** [comment]
Here are links to other people searching for the ability to print from the webview control to provide more context to the issue.

https://stackoverflow.com/questions/39012591/uwp-print-webview

https://stackoverflow.com/questions/17049677/how-do-i-print-webview-content-in-a-windows-store-app?noredirect=1&lq=1

https://stackoverflow.com/questions/46451357/how-do-i-print-webview-content-c-sharp-uwp-win-10?noredirect=1

https://social.msdn.microsoft.com/Forums/en-US/2d8ed6c7-d4e9-4d23-b657-01d91df12476/uwpcproblem-with-printing-webview-in-uwp-phone

https://www.suchan.cz/2016/04/make-webview-great-again/  
Item #13

**Comment by liminzhu** [comment]
Thanks for all the link and bring this up. I wasn't aware `window.print` isn't working in EdgeHTML WebView. 

For the WebView2 we're building tho, you can use `window.print`. WebView opens the same printing prompt and prints that the browser does. I was messing with this,

```
webviewWindow->Navigate(L"https://www.twitter.com/");
EventRegistrationToken token;
webviewWindow->add_NavigationCompleted(Callback<IWebView2NavigationCompletedEventHandler>(
    [](IWebView2WebView* wv, IWebView2NavigationCompletedEventArgs* args) -> HRESULT {
        webviewWindow->ExecuteScript(L"window.print();", nullptr);
        return S_OK;
    }).Get(), &token);
```

![print](https://user-images.githubusercontent.com/1158954/60201410-11a42180-97fd-11e9-859c-3bd703d9c3a9.PNG)

**Comment by mobiletonster** [comment]
That looks promising! As long as we can connect into the webview's print api's, then that would be perfect!

**Comment by liminzhu** [comment]
Great! I think the issue is resolved at this point, but feel free to reopen if you have additional comments on this topic.

**Comment by asklar** [comment]
the platform has requests around converting html or other web content into pdf, which would benefit from this feature being implemented. See https://github.com/microsoft/react-native-windows/issues/7723
