### ISSUE TITLE
Expose windowFeatures passed into window.open in IWebView2NewWindowRequestedEventArgs

### ISSUE THREAD

**Issue by michael-russin** [MicrosoftEdge/WebViewFeedback#70]
Please expose the following parameters in _IWebView2NewWindowRequestedEventArgs_ so the application hosting the new window can honor the settings passed from JavaScript into the window.open() call
* height
* width
* x
* y 
* fullscreen
* location bar (address bar) visible
* menu bar visible
* scrollbars visible
* status bar visible
* toolbar visible 

It would be similar to how CEF exposes CefPopupFeatures in [CefLifeSpanHandler::OnBeforePopup](https://magpcss.org/ceforum/apidocs/projects/%28default%29/CefLifeSpanHandler.html#OnBeforePopup(CefRefPtr%3CCefBrowser%3E,constCefPopupFeatures&,CefWindowInfo&,constCefString&,CefRefPtr%3CCefClient%3E&,CefBrowserSettings&))

Thanks.

**Comment by david-risney** [comment]
Thanks for the feedback! Do you need all of the windowfeatures values? What are you planning to do with them? Thanks!

**Comment by michael-russin** [comment]
We just need x, y, height and width.   We have a application that shows multiple web views hosting different web pages.  One of them is scrolling news headlines and when a user clicks on a story link the web page passes size and location information for the story popup.   We currently handle the new window event to provide a parent window that matches our application style and we use the position and size information to place the window.

**Comment by ukandrewc** [comment]
As a workaround, you can patch window.open():
`//Patch window.open to get dimensions
(function (nativeOpen) {
	window.open = function (u, t, p) {
		//Parse parameters here
		return nativeOpen(u, t, p)
	}
})(open)
`

**Comment by yildirimcagri** [comment]
The window features is now exposed to the NewWindowRequested event. Please see https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-538/icorewebview2experimentalnewwindowrequestedeventargs for reference. Please note that this API addition is currently experimental.

**Comment by ukandrewc** [comment]
This doesn't seem to have been exposed for Winforms?

**Comment by yildirimcagri** [comment]
We don't support exposing the experimental APIs to WinForms and WPF yet, however it's in our internal backlog. Feel free to create a separate GitHub issue if you'd like to track this. Thanks!

**Comment by ukandrewc** [comment]
Thanks, I'll wait, we don't have anything dependant on it.
