### ISSUE TITLE
WebResourceRequested goes into an infinite loop if you give it an IStream

### ISSUE THREAD

**Issue by wravery** [MicrosoftEdge/WebViewFeedback#74]
I haven't tested any prior versions, but in version 0.8.314 returning a content `IStream` through the `IWebView2WebResourceResponse` interface sends webview2 into an infinite loop. I think the `IStream::Read` loop has a bug in its termination condition:
```c++
embeddedbrowserwebview.dll!embedded_browser_webview_current::internal::ReadContentStreamIntoStringStream(IStream * content_stream, std::__1::basic_stringstream<char,std::__1::char_traits<char>,std::__1::allocator<char>> & string_stream) Line 82
```

Here's a simplified sample showing what I'm trying to do in the `IWebView2WebResourceRequestedEventHandler` callback:
```c++
constexpr auto c_fakeBody = R"htm(<html>
	<head>
		<title>Fake Body</title>
	</head>
	<body>
		<pre>Lorem ipsum...</pre>
	</body>
</html>)htm"sv;

constexpr auto c_fakeBodySize = static_cast<ULONG>(c_fakeBody.size() * sizeof(*c_fakeBody.data()));

// I get the URL of the request and compare it to the expected value before proceeding...

Microsoft::WRL::ComPtr<IWebView2WebResourceResponse> response;
Microsoft::WRL::ComPtr<IWebView2HttpResponseHeaders> headers;
Microsoft::WRL::ComPtr<IStream> content;
ULONG cbWritten = 0;
ULARGE_INTEGER uliSize{};

uliSize.QuadPart = static_cast<ULONGLONG>(c_fakeBodySize);

if (SUCCEEDED(CreateStreamOnHGlobal(NULL, true, &content))
	&& SUCCEEDED(content->Write(c_fakeBody.data(), c_fakeBodySize, &cbWritten))
	&& cbWritten == c_fakeBodySize
	&& SUCCEEDED(content->SetSize(uliSize))
	&& SUCCEEDED(content->Seek(LARGE_INTEGER{}, STREAM_SEEK_SET, nullptr))
	&& SUCCEEDED(environment->CreateWebResourceResponse(content.Get(), 200, L"OK", L"", &response))
	&& SUCCEEDED(response->get_Headers(&headers))
	&& SUCCEEDED(headers->AppendHeader(L"Content-Type", L"text/html")))
{
	args->put_Response(response.Get());
}
```

**Comment by david-risney** [comment]
Great bug report, thanks! Let me look into this and get back to you.

**Comment by david-risney** [comment]
Yes just like you said an issue in the Read loop termination condition. We'll look into this. Thanks!

**Comment by yildirimcagri** [comment]
Thanks for reporting this! We have the fix in the works. In the meantime if you need a workaround I recommend using SHCreateMemStream, which should not run into this issue because it's IStream::Read returns S_FALSE when reached end of stream.

**Comment by pagoe-msft** [comment]
Happy to report that we just shipped updates to our WebResourceRequested Event in 0.8.355. Closing the issue for now and feel free to re-open the issue and let us know if you have additional feedback.

**Comment by wravery** [comment]
Just verified the fix, thanks!
