### ISSUE TITLE
Enable support for browser extensions  #featurerequest 

### ISSUE THREAD

**Issue by paj777** [MicrosoftEdge/WebViewFeedback#81]
We have the need for using different zoom levels in different browser instances pointing at the same domain.  Will there be browser extension support so that it would be possible to implement this?

**Comment by david-risney** [comment]
Hi @paj777, thanks for your feedback! This sounds like two different feature requests:
1. Control the zoom of a WebView independent of the origin
2. Host may provide browser extensions

For (2) host provided browser extensions, do you have other use cases for browser extensions or if we implemented a mechanism to control the zoom of a webview and didn't implement host browser extensions would that solve your problem?

Host provided browser extensions would certainly open up a lot of possibilities although it may end up being a lot more work than enabling origin independent zoom.

**Comment by paj777** [comment]
Hi @david-risney thank you for your response.

Yes, breaking this up into two separate feature requests makes sense.  The reason my suggestion included extensions is because this is the only solution that Chrome provides for this zoom issue.  If the independent zoom can be tackled without the need for browser extensions  then that would be great.

As you said, providing browser extensions would open up possibilities but may not be necessary for this issue.

**Comment by douglas-jordan** [comment]
+1 for extensions

**Comment by douglas-jordan** [comment]
I just ran into this problem today, zoom is not independent of origin.  I have more than one WebView2 showing different pages on the same domain and any zoom change sets all the views to the same.

**Comment by douglas-jordan** [comment]
I have test Canary 82.0.435.0 and zoom is independent of origin. Does not appear to be in the release notes for the updated SDK.

**Comment by priprii** [comment]
I would also like to see support for extensions for element blocking with uBlock Origin which makes use of webRequest.

The WebResourceRequested event in Webview2 does not seem to fire for resources being loaded in iframes so I'm unable to block those specific resources from loading by sending 403 response.

In other browsers like Chrome & Firefox, resources in iframes can be blocked with uBlock Origin extension.

So I'm either looking for support for extensions to make use of webRequest, or to have WebResourceRequested support resources in iframes.

**Comment by Adjective-Object** [comment]
I'm working on a react app hosted in webview2 and not having access to React Devtools is pretty painful. I unfortunately can't develop in a full-fledged browser, since we're passing messages to the host process for some required native integrations.

**Comment by champnic** [comment]
Closing this as it's an amalgamation of issues tracked elsewhere or fixed.
* Zoom issue: Fixed
* Browser Extensions: #98 (end users) and #191 (devs)
* React Devtools + remote debugging: #190

**Comment by CoastalData** [comment]
I have another use-case scenario for extension in webview2... I'm making some Line of Business desktop applications that use webview embedded to show a couple of websites that require login, and so I'd like to have access to 1Password in the app to store and fill passwords by the user.

Like others, this is something that would be baked into the app, we're not looking to let users add extensions.

**Comment by EnigmaV8** [comment]
> I have another use-case scenario for extension in webview2... I'm making some Line of Business desktop applications that use webview embedded to show a couple of websites that require login, and so I'd like to have access to 1Password in the app to store and fill passwords by the user.
> 
> Like others, this is something that would be baked into the app, we're not looking to let users add extensions.

We have the exact same enterprise scenario except LastPass is our password filler.  We have some older internal web apps running on WebView2 that still use Basic Auth.  Sure would be nice if our LastPass extension could be utilized instead of requiring wasted time of additional authentication.  (use to work when run under Internet Explorer because they could simply same the credential natively)

**Comment by champnic** [comment]
Please see here for how to install and use an extension in your WebView2:
https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2profile.addbrowserextensionasync?view=webview2-dotnet-1.0.2895-prerelease
