### ISSUE TITLE
Disable Context menu using put_AreDefaultContextMenusEnabled makes Control to disappear.

### ISSUE THREAD

**Issue by kumaranoop228** [MicrosoftEdge/WebViewFeedback#82]
I am trying to disable default context menu using the put_AreDefaultContextMenusEnabled of IWebView2Settings2. After calling put_AreDefaultContextMenusEnabled (False) makes web view control to disappear on right click.

Even if we call put_AreDefaultContextMenusEnabled(True) afterwards webview disappears on right click.

**Comment by david-risney** [comment]
Wow thanks for the bug report! We'll look into the issue and get back to you. Can you say which version of the sdk you have and which version of the browser you have?

**Comment by kumaranoop228** [comment]
I updated the browser to Version 80.0.345.0 (Official build) canary (64-bit) and it seems the issue is no more present.
So I am able to enable and disable the default context menu now.

Is there any way apart from JS using which I can configure my own context menu?

**Comment by david-risney** [comment]
Glad it's working for you now! We don't currently have a mechanism to customize the context menu. We do have that feature in our backlog though.

**Comment by kumaranoop228** [comment]
Do you have any right click event on browse? I do not see any mouse events.

**Comment by david-risney** [comment]
You should see the normal mouse events in the DOM in JavaScript. Otherwise, from the native side you should be able to see all input events before they go to the WebView2 control.
