### ISSUE TITLE
Setting preferences

### ISSUE THREAD

**Issue by ukandrewc** [MicrosoftEdge/WebViewFeedback#83]
Is it possible to change the chrome preferences?
I've tried changing **\EBWebView\Default\preferences** but that doesn't seem to work.
In particular I'd like to change some in **profile>default_content_setting_values**

**Comment by david-risney** [comment]
We only expose a few settings currently on the Settings object. Which preferences are you trying to modify?

**Comment by ukandrewc** [comment]
Images for a start, but not sure what else, just seeing what control there is.
Any chance entries in the preferences file could be used as defaults?

**Comment by david-risney** [comment]
Do you mean to prevent images from loading? If you have specific requests we can look into supporting them.

**Comment by ukandrewc** [comment]
Yes, that was the main one.
Ideally, we need options to block: images, media, CSS and JS.
Although, I appreciate we can probably do that with WebResourceRequested

**Comment by pagoe-msft** [comment]
Yes, you can accomplish this with WebResourceRequested.
