### ISSUE TITLE
Provide interface for alert() callback

### ISSUE THREAD

**Issue by agonzalezjr** [MicrosoftEdge/WebViewFeedback#85]
The WebView2 should expose a WebView_AlertRaised type of callback that classes can register with just like NavigationCompleted, ScriptNotify, etc... that gets executed whenever the `alert()` method is called in JavaScript.

This is available in most other platforms WebView frameworks (Android and [iOS](https://developer.apple.com/documentation/webkit/wkuidelegate/1537406-webview) for sure)

It would be very helpful in displaying alerts in a native dialog message.

**Comment by michael-russin** [comment]
You can use the `add_ScriptDialogOpening`  (https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview#add_scriptdialogopening) to hook into the `alert()` method.  You'll need to set the AreDefaultScriptDialogsEnabled setting to false also.

**Comment by agonzalezjr** [comment]
Thanks! @michael-russin
