### ISSUE TITLE
WebView privacy and security

### ISSUE THREAD

**Issue by Dmitiry-hub** [MicrosoftEdge/WebViewFeedback#86]
How safe is WebView?
Does WebView send visit data to Microsoft?

**Comment by liminzhu** [comment]
Thanks for your question @Dmitiry-hub! Some answers

> How safe is WebView?

This is a very broad question :), but with WebView2 we inherit the Chromium sandboxing/process model, so the security metrics from that aspect is the same as Chromium. 

> Does WebView send visit data to Microsoft?
We only do when the user has given consent to send telemetry data about Microsoft Edge. User is able to retrieve consent any time they wish.
