### ISSUE TITLE
WebView VPN C# WPF

### ISSUE THREAD

**Issue by Dmitiry-hub** [MicrosoftEdge/WebViewFeedback#87]
How do I implement a VPN in WebView(EdgeHTML) on C# WPF?

**Comment by david-risney** [comment]
Can you please elaborate on what you mean? I would imagine the VPN connection is a networking change in your OS and doesn't require WebView changes.

**Comment by champnic** [comment]
No response, closing. Also, WebView (EdgeHTML) is out of scope for this repo. Thanks!
