### ISSUE TITLE
WPF WebView1 stub processes turn zombie if hosted process silently terminated when attach debugger

### ISSUE THREAD

**Issue by kekyo** [MicrosoftEdge/WebViewFeedback#88]
I implement some applications with WPF WebView1 component. I known it'll start stub process named both "WWAHost.exe" and "Win32WebViewHost.exe".
These process become turn to zombies when terminate debugging (will stop debug button or menu in VS) hosted WPF process.

I wanna these processes terminate implicitly if hosted process died, or can we configure it already released WevView1 versions?

FYI: I tired killing it manually, so wrote a utility for one-click solution (I use it every day :)
https://github.com/kekyo/WebView1Terminator

**Comment by pagoe-msft** [comment]
Hi @kekyo,

Our engineering priority has shifted from supporting WebView1 to working on releasing WebView2 which is powered by Microsoft's new Chromium browser. Currently WebView2 is in beta, but will launch Q1 2020, and we plan to have .NET support by Q3 2020.

You can learn more about WebView 2 here: https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2 

Thanks for letting us know of this issue with WebView1 - we will ensure that this issue does not arise in WebView2.

**Comment by kekyo** [comment]
@pagoe-msft I understood and agreed. I hope your team focus into WebView2. I think this issue maybe causes on WebView2 same as WebView1 if WebView2 backend architecture has separated process. So, I sent attention :)
