### ISSUE TITLE
Modernization of WebView2

### ISSUE THREAD

**Issue by verelpode** [MicrosoftEdge/WebViewFeedback#99]
I have been debating for weeks with a colleague of mine because I say we should use WebView2 and he says that we should use Chromium directly and forget Microsoft's web components.  I have more faith in Microsoft than he does.  Naturally I want to win this debate and reach agreement to use WebView2, but currently I'm struggling to refute this argument of his:  
> Microsoft needs to win the trust of developers, but Microsoft does NOT inspire trust when in the year 2020 Microsoft publishes a new API that looks like the old API's from the 1990's.  In the year 2020, developers trust modern software designs, not designs from 27 years ago.

Relucantly I'm forced to admit that decades ago, back when I started my career, I wrote code using the techniques that were current at the time, such as `HRESULT`.  I kept my skills up-to-date over the years, thus I switched from `HRESULT` to [exception handling](https://en.wikipedia.org/wiki/Exception_handling) when it became the best and recommended practice.  What can I say when he points out that WebView2 is being published in the year 2020 yet still uses `HRESULT` instead of exception handling, as if WebView2 is part of Windows 95?  I don't know how to answer this question.  He's making a good point.  

I fear that I will lose the debate.  I'm an honorable debater, so if I lose the debate, then I will adopt his opinion and agree to use Chromium directly instead of WebView2.

The problem is not only the ancient error handling that exists in the WebView2 API.  He points out various other things that also unfortunately make it look like code from Windows 95 instead of 2020, such as `LPCWSTR`.

Unfortunately I know exactly what he means because I've been programming since the days when `LPCWSTR` was the current technique, and I remember that the "L" means a "long pointer".  The concept of "short/near pointers" and "long/far pointers" was something that existed in Win16 days with 16-bit "short/near pointers" and 32-bit "long/far pointers".  This stuff is _decades_ out-of-date, but look at WebView2, a new API being published in the year 2020, and these ancient long pointers are still visible in the API.  He says:

> You can't expect me to have trust and faith in a NEW component that uses short versus long pointer concepts from Win16 from decades ago.  It's like travelling back in time to the 1990's and writing apps for Windows 95.

How can I refute that argument?  I have to be reasonable and empathetic about this.  If I'm genuinely empathetic, then I have to acknowledge that I cannot ask any colleague to have trust or faith in a new component that uses very old programming techniques including:

* Component Object Model (COM) (obsolete tech from 1993, now 27 years old).
* `HRESULT, S_OK, E_INVALIDARG`, etc
* `CHECK_FAILURE(...)`
* `LPCWSTR` as input string
* `LPWSTR*` as output string
* `L"example text"`
* `wil::unique_cotaskmem_string`
* `SIZE_T`
* `wil::com_ptr<...>`
* Excessive use of Win16, also known as Win32 (obsolete tech from decades ago).

Is there any chance of WebView2 being modernized?  The modern software engineering standards are very widely accepted.  What are the reasons for publishing such an old form of API for WebView2 in the year 2020?  Are these reasons truly justifiable?

I would really like to win this debate and use WebView2, but I'm struggling, I'm really struggling.  I'm an honorable debater, so if I lose the debate, then I will change my opinion to reach agreement with my colleague's preference to forget WebView2 and use Chromium directly.

I said to him, if we use Chromium directly, then it doesn't mean we would entirely escape from the obsolete junk, because Chromium also contains obsolete junk regardless of whether it is used via WebView2 or not, so either path involves tedious management of obsolete junk.  His reply is that my argument is a weak argument because a single layer of junk creates less work and less debugging than 2 layers of junk.  He's right; my argument is weak.  

I said that Microsoft has to be careful about **breaking changes** and **backwards-compatibility**, in order to avoid disturbing hundreds of app developers.  He said that's nonsense because WebView2 is a new API therefore breaking changes are non-applicable.  True.  Furthermore, we also use Azure and some Azure Nuget packages introduced breaking changes, and many Nuget packages introduce breaking changes at some point, and nobody complained about these breaking changes, therefore breaking changes can in fact be introduced with minimal disruption to app developers.  The issue of "breaking changes" should be treated in a reasonably balanced manner, not in an extremist manner, because if it is an extremist manner, then it severely hampers progress and advancement.

An idea that WebView2 must be a COM component "for compatibility reasons" isn't actually a logical and believable argument.  WebView2 would inspire more trust if it was published in the form of a modern NuGet package with use of modern software engineering practices.  The visibility of Win16, COM, long pointers, HRESULT, etc in the public API makes a very bad impression and erodes trust and faith in Microsoft.  Indeed WebView2 does look like the code that I wrote back when I started my career decades ago.  I updated my software engineering skills long ago.  It might be helpful to participate in a training course to bring staff members up-to-date with modern software engineering practices such as exception handling, nuget packages, etc.

The debate with my colleague is not ended, and the winner is very uncertain:  It could go either way.  Currently the pros and cons seem to be balanced on a knife edge, but this could change before WebView2 exits alpha or beta stage.  I hope that the next version of WebView2 makes it easier for me to win this debate and get agreement to use WebView2.

**Comment by nmoinvaz** [comment]
Newer isn't always better. Not everybody has the privilege of working on applications where they can always use the latest and greatest software tools. There are many enterprise applications that have requirements that prevent them from doing so. 

The design decisions that were made were probably done so to allow for the maximum number of applications on the Windows platform to take advantage of the new WebView2 control.

**Comment by verelpode** [comment]
@nmoinvaz
Thanks for the idea.  I don't think I'll be able to win the debate with that argument because the people who produce enterprise software are people like ourselves -- we only produce enterprise software.  No enterprises are still using [Windows 3.1](https://en.wikipedia.org/wiki/Windows_3.1x).  Windows 3.1 was released in 1992, that's 27 years ago.  Microsoft has no need to retain compatibility with a 27-year-old version of Windows.

I checked the minimum requirements for Microsoft Edge Insider (corresponding with WebView2/Chromium) and it says Windows 7 as you can see [on this Edge page](https://www.microsoftedgeinsider.com/en-us/download).  Windows 7 does support modern software engineering practices such as exception handling etc, so Windows 7 compatibility is no justification for continuing to use `HRESULT`, `CHECK_FAILURE(...)` etc.  Likewise short versus long pointers are still decades out-of-date even if we view it in terms of Windows 7 instead of Windows 10.  Windows 7 was released in the year 2009, many years after short/long pointers became obsolete.

Exception handling has big benefits.  Professional software engineers know this fact very well.  It's a very widely known fact that exception handling is much better than returning an integer error code.   It's quite surprising to see Microsoft continuing to use `HRESULT` etc in the year 2020, even if Windows 7 compatibility is required.  If I had a staff member who used Win16-style programming techniques today, I would immediately place him/her in a training course in order to update him/her to the modern software engineering practices.

**Comment by nmoinvaz** [comment]
You can't do exception handling in C. 

Besides what difference does it make what the name of the variable type is? Is your co-worker's argument that the interface does not _look_ modern enough? If that is the case then I think you will end up using Chromium even though it will probably be much more work. Does your co-worker not use any third-party library that doesn't have a modern 
interface? You could always write a C++ (or whatever your language is) wrapper around the WebView2 interface if you don't like the look of it.

**Comment by pagoe-msft** [comment]
Hi verelpode, 

Thank you for your feedback. To explain our engineering decisions, we're starting with a COM-like interface for compatibility with older code bases for end developers moving from the mshtml brower control. We're actively working on wrappers for .NET support and WinRT support. 

As you can imagine, there is a large amount of developers each with their own use cases of WebView2. Our engineering decisions have resulted from months of conversations with large and small enterprises as well as the developer community. We have done our best to make engineering decisions that support the greatest amount of scenarios we expect our customers to encounter.

Best of luck in your debate!

**Comment by ukandrewc** [comment]
COM is still the basis of Windows, exception handling is a wrapper and syntactic sugar.
Here are some arguments if you use Chromium:

- You'll be up to your armpits in LPCWSTR and HRESULT
- These methods are all valid in C, it's how it works.
- Chromium is only the basics, not a working browser.
- It doesn't have a licence for formats such as MP4

There is a current .Net wrapper here: https://github.com/michael-russin.

**Comment by verelpode** [comment]
@pagoe-msft
Unfortunately this issue was closed without any resolution.  Would you consider reopening the issue?  I would be happy to explain in further detail, if you are interested in receiving this feedback.  If the issue remains closed, then it adds considerable weight to my colleague's arguments and sadly I'll probably be forced to concede that I lose the debate, and I'll have to adopt my colleague's opinion that we should use Chromium directly instead of my preferred plan to use WebView2.

**Comment by ukandrewc** [comment]
@verelpode Has your colleague tried to build a browser from the Chromium source?

**Comment by verelpode** [comment]
@ukandrewc 
Good point, but as I mentioned, I began my career with Win16/32 programming, so we possess the necessary knowledge and experience to successfully accomplish the use Chromium, despite the fact that use of Chromium involves serious disadvantages like you indicated.  
You wrote "build a browser", but we don't want a WebBrowser component, rather we want a WebView.  Originally, years ago, we thought we wanted a WebBrowser component, but through experience we quickly discovered that a WebBrowser component causes endless problems for us, thus I say we want a "Web-View" rather than a "Web-Browser".  In addition, this WebView should be the form of a modern .DLL or NuGet package, not ancient COM and Win16/32.

You made good points and I'd like to continue the discussion, but I feel that it is pointless to continue the discussion because apparently the WebView2 team is unwilling to modernize WebView2 and a Microsoft staff member has already closed this issue.
